### ISSUE TITLE
Add an `afterEachMounted` hook

### ISSUE THREAD

**Issue by glen-84** [vuejs/vue-router-next#1005]
### What problem does this feature solve?
I need to execute code once the route component has mounted. `afterEach` runs straight after routing, and doesn't wait for the component to be mounted.

Adding a `mounted` hook to every route component separately would be painful, and doing it via a mixin or similar would require distinguishing between route- and non-route components, triggering another event, etc.

This code seems to work, but isn't well typed and might not be supported:

```ts
router.afterEach(async (to) => {
    // @ts-expect-error -- TODO: ...
    to.matched[0].components["default"].mounted = (): void =>
        console.log("afterEachMounted");
});
```

Would it be possible to add an `afterEachMounted` hook to make this more formal? It would be really useful.

### What does the proposed API look like?
```ts
router.afterEachMounted(async (to, from) => {
    console.log("afterEachMounted");
});
```

**Comment by posva** [comment]
Navigation is disconnected from the component lifecycle. Therefore if you need to add something to components that are mounted, it's not something that should go in vue router's code. You could still create a userland API for that or add it to components that are used in `routes` by patching them (which would be typed).

**Comment by glen-84** [comment]
Augmenting components added to the router would be a manual step that would have to be repeated for every single route. I need a generic way of running code once a route component is mounted, not something in userland.

The router seems like the most logical place to put this, but there's no plugin system or other way of getting access to the route component (besides the method that I show above).

If you won't add either, then could there at least be a more type-safe way of accessing the matched component?
