### ISSUE TITLE
企业微信内无法跳转

### ISSUE THREAD

**Issue by yang867381349** [vuejs/vue-router-next#1008]
### Version
4.0.9

### Reproduction link
[https://m.qingjishe.cn/FormFinancing?id=340100,340200,340300&title=%E5%90%88%E8%82%A5%E5%B8%82%E9%9C%80%E6%B1%82%E8%B0%83%E7%A0%94%E8%A1%A8](https://m.qingjishe.cn/FormFinancing?id=340100,340200,340300&title=%E5%90%88%E8%82%A5%E5%B8%82%E9%9C%80%E6%B1%82%E8%B0%83%E7%A0%94%E8%A1%A8)

### Steps to reproduce
https://m.qingjishe.cn/FormFinancing?id=340100,340200,340300&title=%E5%90%88%E8%82%A5%E5%B8%82%E9%9C%80%E6%B1%82%E8%B0%83%E7%A0%94%E8%A1%A8

### What is expected?
希望能够像其它浏览器一样进行跳转。

### What is actually happening?
跳转。发生了阻断。

---
提交的网址是本人测试服务器开发的东西。随便填写内容后，点击提交按钮。

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

Open issues in English with a boiled down reproduction

**Comment by 850680822** [comment]
使用hash模式进行授权后进行路由校正后使用
