### ISSUE TITLE
Failed to match empty sub route  in named routing mode

### ISSUE THREAD

**Issue by phpjavac** [vuejs/vue-router-next#1011]
### Version
4.0.10

### Reproduction link
[https://jsfiddle.net/8o4j701a/](https://jsfiddle.net/8o4j701a/)

### Steps to reproduce
```
  routes: [
    { path: '/', redirect: '/foo' },
    { path: '/foo', component: Foo },
    { path: '/bar',name:'bar', component: Bar,children:[
    {
    path:'',
     component: Foo
    }
    ] },
  ]
......
router.push('/bar') -> ✅ 
router.push({name:"bar"}) ->  ❌ :Failed; Normal after refreshing page


```

### What is expected?
normal matching sub route

### What is actually happening?
unmatched to empty sub route

**Comment by posva** [comment]
This is intended behavior. Put the name in the child instead or use two different names.
Refreshing the page makes the router resolve `/bar` instead of `{ name: 'bar' }`


Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!
