### ISSUE TITLE
fail to passing route name as prop to page

### ISSUE THREAD

**Issue by horans** [vuejs/vue-router-next#1018]
### Version
4.0.10

### Reproduction link
[https://codepen.io/horan/pen/zYZbOxw](https://codepen.io/horan/pen/zYZbOxw)

### Steps to reproduce
1. pass current route name as prop `page` with `<router-view :page="$route.name" />`.
2. access `page` in route component.

### What is expected?
each route component automatically gains its own prop `page` base on their name defined in routes

### What is actually happening?
1. working with npm dev env, fail in prod env. (`page` is undefined)
2. not working with cdn dev/prod env. (check codepen sample)

---
1. `$route.path` works just fine.
2. was working with vue v3.0.11, failed when upgraded to vue v3.1 .
3. not working with `$router.currentRoute._value.name` or `_rawValue.name` either.

**Comment by posva** [comment]
You should either use the `props` option in route records:

```js
props: to => ({ link: to.path, page: to.name }),
```

or use the `v-slot`:

```vue
<router-view v-slot="{ Component, route }">
  <component :is="Component" :extra="route.name"></component>
</router-view>
```

PS: don't use `_value` nor `_rawValue`, they are internal

**Comment by horans** [comment]
@posva thanks for quick reply.
option 2 works for me, sweet~

btw, was using `_value`/`_rawValue` only for demo purpose.
