### ISSUE TITLE
Possibility to use a nested object for query parameters

### ISSUE THREAD

**Issue by TobiasGraml11** [vuejs/vue-router-next#1019]
### What problem does this feature solve?
We have a search parameter structure in the backend, where all filter attributes are in one nested object with:

```js
attrib: {
    cat: ['Category1'],
    color: ['Red', 'Blue'],
},
```

Currently, I would need to make a key `attrib[cat][0]` with the value `Category1`, to even give the possibility of providing one filter value in the URL the same as I need for the backend request.

When using a nested object, the URL just looks like `attrib=[object Object]`.

### What does the proposed API look like?
```js
const params = {
    query: '',
    count: 10,
    attrib: {
        cat: ['Category1'],
        color: ['Red', 'Blue'],
    },
} as LocationQuery;

router.push({
    path: 'search',
    query: params,
});
```
would parse to:
`?query=&count=10&attrib[cat][0]=Category1&attrib[color][0]=Red&attrib[color][1]=Blue`

**Comment by posva** [comment]
This has been proposed before. Vue Router's query parsing is purposely light. You should use `parseQuery`/`stringifyQuery` to provide a custom implementation for this: https://next.router.vuejs.org/api/#parsequery.

**Comment by stefusilviu** [comment]
@posva I have to use nested objcts instead of arrays for query parameters so I ended up using qs package through `parseQuery` and `stringifyQuery`. I still have an issue using typescript as the qs returning type (nested) is not compatible with what `parseQuery` is expecting, namely `parseQuery`. I had to `// @ts-ignore` it. Any solution for this? Thanks.

**Comment by trooffEE** [comment]
@stefusilviu hi any work around ts issue with your approach? I tried to implement with declare override but didn't come to solution for now. But indeed i have the same behavior as yours
