### ISSUE TITLE
replace/push/resolve do not seem to handle encoded paths correctly

### ISSUE THREAD

**Issue by olivoil** [vuejs/vue-router-next#1020]
### Version
4.0.10

### Reproduction link
[https://github.com/olivoil/vue_router_bug_repro](https://github.com/olivoil/vue_router_bug_repro)

### Steps to reproduce
- clone the provided reproduction repo
- run `pnpm install` to install dependencies
- run `pnpm run dev` to run the project
- visit localhost:3333/foo/bar
- the page will call `router.replace({ query: { baz: 'bim' } })` (as can be seen in https://github.com/olivoil/vue_router_bug_repro/blob/main/src/pages/%5B...all%5D.vue#L9)

### What is expected?
the url displayed in the browser should be /foo/bar?baz=bim

### What is actually happening?
the url displayed in the browser is now /foo%2Fbar?baz=bim

---
The documentation states that "When using push, resolve, and replace and providing a string location or a path property in an object, it must be encoded (like in the previous version).", but it doesn't look like that's the case?

**Comment by posva** [comment]
There is because the catch all route has been defined without a repeated param. I opened https://github.com/hannoeru/vite-plugin-pages/pull/69
