### ISSUE TITLE
How to get type declaration of RouterLink's slot

### ISSUE THREAD

**Issue by bowencool** [vuejs/vue-router-next#1024]
### What problem does this feature solve?
TS7031: Binding element 'isActive' implicitly has an 'any' type.
```
    60 |             <RouterLink to={currentPath} custom>
    61 |               {{
  > 62 |                 default: ({ isActive, navigate }) => (
       |                             ^^^^^^^^
    63 |                   <el-menu-item
    64 |                     index={currentPath}
    65 |                     class={isActive ? 'is--active' : ''}
```

### What does the proposed API look like?
Expose type declaration or automatic prompts

**Comment by standbyoneself** [comment]
Could you provide a repository?

**Comment by bowencool** [comment]
> Could you provide a repository?

[router-link.zip](https://github.com/vuejs/vue-router-next/files/6770819/router-link.zip)

**Comment by standbyoneself** [comment]
First of all, create a repository on GitHub as you already have an account, then provide a link for this.

Secondly, I really don't understand why are you return an arrow function that returns a piece of JSX from the `setup`? Where are the docs you have learned by?

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by bowencool** [comment]
> First of all, create a repository on GitHub as you already have an account, then provide a link for this.
> 
> Secondly, I really don't understand why are you return an arrow function that returns a piece of JSX from the `setup`? Where are the docs you have learned by?

https://v3.vuejs.org/guide/composition-api-setup.html#usage-with-render-functions

**Comment by standbyoneself** [comment]
In order to use that you need to return the `VNode` created by the `h()` method. `h()` accepts `type`, `props` and `children`. See the [reference](https://v3.vuejs.org/api/global-api.html#h).

Keep it simple. You simply could do this using SFC.

**Comment by bowencool** [comment]
> In order to use that you need to return the `VNode` created by the `h()` method. `h()` accepts `type`, `props` and `children`. See the [reference](https://v3.vuejs.org/api/global-api.html#h).
> 
> Keep it simple. You could simply do this using SFC `<template>`.

Thanks, but the reason I didn't use `<template>` was because of another confusion about it:
How to insert `VNode` in `<template>`, such as `meta.title`:
``` vue
<script lang="tsx">
import { defineComponent } from "vue";
import { RouteRecordRaw, RouterLink } from "vue-router";
// import { routes } from "@/router";

const routes: Array<RouteRecordRaw> = [
  {
    path: "/",
    name: "Home",
    component: () => import("@/views/Home.vue"),
    meta: {
      title: <i style="color: red">Home</i>,
    },
  },
  {
    path: "/about",
    name: "About",
    component: () => import("@/views/About.vue"),
    meta: {
      title: "About",
    },
  },
];

export default defineComponent({
  setup() {
    return () => {
      return (
        <>
          <div id="nav">
            {routes.map((route: RouteRecordRaw) => (
              <RouterLink to={route.path} key={route.path} custom>
                {{
                  default: ({ navigate }) => (
                    <span onClick={navigate}>
                      {typeof route.meta.title === "string" ? (
                        <span>{meta.title}</span>
                      ) : (
                        meta.title
                      )}
                    </span>
                  ),
                }}
              </RouterLink>
            ))}
          </div>
          <router-view />
        </>
      );
    };
  },
});
</script>
```
