### ISSUE TITLE
如何在vue服务端渲染中处理vue-router的重定向？

### ISSUE THREAD

**Issue by masx200** [vuejs/vue-router-next#1025]
### What problem does this feature solve?
如何在vue服务端渲染中处理vue-router的重定向？

### What does the proposed API look like?
https://reactrouter.com/web/guides/server-rendering

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
