### ISSUE TITLE
Vite build breaks navigation

### ISSUE THREAD

**Issue by makurtu** [vuejs/vue-router-next#1030]
### Version
4.0.10

### Reproduction link
[https://codesandbox.io/s/vue-router-4-reproduction-s1sqc](https://codesandbox.io/s/vue-router-4-reproduction-s1sqc)

### Steps to reproduce
1. Take this sample code:

```js
import { createRouter, createWebHistory } from "vue-router";

const Layout = () => import("@/views/Layout.vue");
const Home = () => import("@/views/Home.vue");

const routes = [
    {
      path: `/home`,
      component: Layout,
      children: [
        {
          path: "",
          component: Home,
          name: "Home",
        }
      ]
    },
];

const router = createRouter({
    history: createWebHistory(),
    routes,
  });
```

2. Build this code with `vite build` and upload it to your server, it works as expected.
3. Rebuild it with `vite build` again and upload to your server.
4. Now, Vue-Router triggers an error.

### What is expected?
Vue-router  should be able to handle all "rebuilded" components by default and be able to navigate through App as expected.

### What is actually happening?
Vue-router works as expected if you don't push any new code to your server. But if you make a new build of your code, Vite assigns a new chunk to Lazy loaded components and then, Vue-router can't find expected component and an error is triggered:

*"Error loading dynamically imported module"*

**Comment by posva** [comment]
This is likely a cache issue on your server. It will happen with any lazy-loaded import and is not related to the router.

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂

**Comment by makurtu** [comment]
> This is likely a cache issue on your server. It will happen with any lazy-loaded import and is not related to the router.

It's not a cache issue, simply when I build first time Vite produces `/assets/index.9c928e92.js`  and in next build, Vite produces `/assets/index.3824f68d.js` (you can see that there is different chunk on filename). So Vue-route triggers *Error loading dynamically imported module*.
