### ISSUE TITLE
The fact that the `children` property of routes returned by getRoutes does not update when routes are dynamically added or removed should be documented.

### ISSUE THREAD

**Issue by dospunk** [vuejs/vue-router-next#1031]
### What problem does this feature solve?
According to [this comment](https://github.com/vuejs/vue-router-next/issues/600#issuecomment-731055795) on #600, "The children property of routes in getRoutes is the initial value, it's not the current children". This still seems to be the case in the current version, but this behavior is not documented anywhere. I am opening an issue instead of just submitting a PR because I'm not sure whether it would be better suited for the [RouteRecordNormalized](https://next.router.vuejs.org/api/#routerecordnormalized) section, the [getRoutes](https://next.router.vuejs.org/api/#getroutes) section, or both. 

### What does the proposed API look like?
n/a

**Comment by posva** [comment]
Let's add it along in the API section: https://next.router.vuejs.org/api/#children-1
