### ISSUE TITLE
我应如何在不刷新的情况下，将动态添加的路由树，重置回创建 Router 时传递的原始配置对象

### ISSUE THREAD

**Issue by Minitiai** [vuejs/vue-router-next#1034]
### What problem does this feature solve?
路由name为undefined时，无法通过removeRoute删除

### What does the proposed API look like?
可重置为初始化状态的routes

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

You can use the returned function of addRoute to remove it: https://next.router.vuejs.org/api/#addroute

**Comment by Minitiai** [comment]
even even feat !

**Comment by Minitiai** [comment]
> 您好，感谢您的关注，但 Github 问题仅针对错误报告和功能请求。您可以在[论坛](http://forum.vuejs.org/)、[Discord 服务器](https://vue-land.js.org/)或[StackOverflow](http://stackoverflow.com/tags/vue.js)上提问。
> 
> 您可以使用 addRoute 的返回函数将其删除：[https](https://next.router.vuejs.org/api/#addroute) ://next.router.vuejs.org/api/#addroute[](https://next.router.vuejs.org/api/#addroute)

I hope I can add an initialization function

**Comment by tomoat** [comment]
我有同样的问题，有解决办法吗？ @Minitiai M
