### ISSUE TITLE
在 routes: RouteRecordRaw[] 里面component为什么是必须参数，为什么不是可选参？

### ISSUE THREAD

**Issue by Haloxylon** [vuejs/vue-router-next#1035]
### What problem does this feature solve?
在 RouteRecordRaw 里面component为什么是必须参数，为什么不是可选参？当菜单有子菜单时，父级菜单通常都是没有对应页面的，为什么还需要component

### What does the proposed API look like?
RouteRecordRaw   里面的 component 是否可以改成可选

**Comment by PeterAlfredLee** [comment]
Hi, @Haloxylon 
Components are not required.
When defining `redirect` in `routes`, there cannot be `component` or `components`
Because it will never be rendered.
Please check the address:
https://github.com/vuejs/vue-router-next/blob/a55854113b116d5e559f89796df1e229eeb87fef/src/types/index.ts#L311

**Comment by posva** [comment]
Please use the forum or chat for questions
