### ISSUE TITLE
Using the new syntax `Declaring Additional Options` of `vue 3.1.4`, an error will be reported at startup

### ISSUE THREAD

**Issue by jiangmaniu** [vuejs/vue-router-next#1036]
Using the new syntax [Declaring Additional Options](https://github.com/vuejs/rfcs/blob/master/active-rfcs/0040-script-setup.md#declaring-additional-options) of `vue 3.1.4`, an error will be reported at startup

### Version
vue-router: 4.0.10
vue: 3.1.4

### Reproduction link
https://github.com/jiangmaniu/vue-router-setuup-demo

Error location ：

Link the `HelloWorld.vue`  file of the repository

![image](https://user-images.githubusercontent.com/50100681/125202386-f7372680-e2a5-11eb-9f76-35acd85de854.png)

### Steps to reproduce
Pull the warehouse code and run it directly

### What is expected?
normal operation

### What is actually happening?

When the project is started, when installing `vue-router-next`, the following error will occur:

![image](https://user-images.githubusercontent.com/50100681/125202299-94de2600-e2a5-11eb-81d6-2a39bd9d407b.png)

---

**Comment by posva** [comment]
You have to put the regular script before the setup one, like in the rfc

**Comment by jiangmaniu** [comment]
It turned out to be like this. Thank you very much for solving the problem that has bothered me for two days. I never knew that this grammar would require order. 😁
