### ISSUE TITLE
Object as params not working

### ISSUE THREAD

**Issue by Lalrinfela** [vuejs/vue-router-next#1038]
### Version
4.0.10

### Reproduction link
[https://codesandbox.io/s/bold-flower-wnx4h](https://codesandbox.io/s/bold-flower-wnx4h)

### Steps to reproduce
$router.push({name: 'contact', params: {username: user.name, age: user.age, phone: user.phone}}) // This is working (Eg: About Page)

$router.push({name: 'contact', params: {user}}) // This is not working. Output [object] [object] (Eg: Contact Page)

### What is expected?
In the Contact.vue page, the props show be supplied the user object

### What is actually happening?
In the Contact.vue page, the props value is blank object

---
This works in previous versions. It stops working in version 4. Passing direct Options API data object with many properties is important in cases where we have a list of posts, and when going to the post detail page, we can directly pass the post object from the params.

**Comment by posva** [comment]
All params must be declared in the path of the route record and can only be strings or array of strings for repeatable params. Like in the examples of the docs

**Comment by Lalrinfela** [comment]
Ok. Thanks.

I just convert to JSON String and then Parse back to object in the contact page. Wish we can still directly pass object. 
Using Stringify or defining all params in the route path is cumbersome for many use cases.
