### ISSUE TITLE
route cannot be mouted

### ISSUE THREAD

**Issue by norangit** [vuejs/vue-router-next#1039]
### Version
4.0.10

### Reproduction link
[https://tw.hycdc.top:8443/setting/requirement](https://tw.hycdc.top:8443/setting/requirement)

### Steps to reproduce
```
step 1: open the link https://tw.hycdc.top:8443/setting/requirement

step 2: switch clicking left nav between 设置 -> 部门工时类型，设置 -> 部门人员 and 设置 -> 需求设置, then console throw error, say - TypeError: Cannot read property 'insertBefore' of null, but the others route just worked fine

and it is ok in dev mode, but not working after build prod
``` 
after I debug, I found that the router can not find router view dom, but the dom is just there, I don't know what I missed? please help me, how should I pick up the key point

### What is expected?
the route can been work fine

### What is actually happening?
route dose not work fine as expected

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by norangit** [comment]
why do you think this is not a bug?
