### ISSUE TITLE
conditional rendering of component on route

### ISSUE THREAD

**Issue by andredewaard** [vuejs/vue-router-next#1044]
### What problem does this feature solve?
rendering a different page based on if a user can access that page or not

### What does the proposed API look like?
```
const allowed = ref(false)

export const useAuthState = () => {
  const setAllowed = () => {
    allowed.value = !allowed.value
  }
  return {
    allowed,
    setAllowed
  }
}

const routes = [
  {
    path: '',
    name: 'Home',
    component: () => { 
      const { allowed } = useAuthState()
      if (allowed.value) {
        return import('../views/Allowed.vue')
      } else {
        return import('../views/NotAllowed.vue')
      }
    },
    meta: { requiresAuth: true }
  }
]
```

This is a very simplified version of what i want to achieve but to explain a bit more.
I want to have permissions on the authState that states if the user that is logged in can access an certain page or not. if not and the user is trying to visit the page instead of redirecting the user i would like to render a different page where the user can subscribe so the user can visit the page. but the component function is not updating the returned component if the allowed variable is updated. 

Of course i can also handle this in each page seperately but i hoped this would be an option.

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

You can use a navigation guard to redirect the use to a different page. Handle the display at the App.vue level to toggle between a custom forbidden component and the router-view. Use `meta` fields, to track which routes are special or not, etc
