### ISSUE TITLE
 Avoided redundant navigation to current location

### ISSUE THREAD

**Issue by wangweiqiangs** [vuejs/vue-router-next#1047]
### Version
4.0.8

### Reproduction link
[https://github.com/vuejs/vue-router-next/issues](https://github.com/vuejs/vue-router-next/issues)

### Steps to reproduce
failed navigation Error: Avoided redundant navigation to current location: "/dashboard".
    at createRouterError (vue-router.esm-bundler.js:826)
    at pushWithRedirect (vue-router.esm-bundler.js:2969)
    at Object.push (vue-router.esm-bundler.js:2915)

### What is expected?
null waring

### What is actually happening?
push

**Comment by wangweiqiangs** [comment]
How to solve ？

**Comment by posva** [comment]
This error is documented. Please use the chat for questions
