### ISSUE TITLE
How to use router-view :route props

### ISSUE THREAD

**Issue by legcc** [vuejs/vue-router-next#1052]
### Version
4.0.10

### Reproduction link
[https://codesandbox.io/s/charming-feather-08l13?file=/src/pages/Home/index.vue](https://codesandbox.io/s/charming-feather-08l13?file=/src/pages/Home/index.vue)

### Steps to reproduce
https://codesandbox.io/s/charming-feather-08l13?file=/src/pages/Home/index.vue

### What is expected?
normal work

### What is actually happening?
can not work

---
Hope to provide usable cases

**Comment by posva** [comment]
See https://github.com/vuejs/vue-router-next/issues/1048

**Comment by legcc** [comment]
Like this? But an error will be reported in the google browser：Uncaught (in promise) TypeError: Cannot read property 'parentNode' of null

This is my approach：
https://codesandbox.io/s/charming-feather-08l13?file=/src/pages/Home/index.vue

**Comment by legcc** [comment]
Like this? But an error will be reported in the google browser：
Uncaught (in promise) TypeError: Cannot read property 'parentNode' of null

This is my approach：
https://codesandbox.io/s/charming-feather-08l13?file=/src/pages/Home/index.vue

**Comment by legcc** [comment]
@posva 
Like this? But an error will be reported in the google browser：
Uncaught (in promise) TypeError: Cannot read property 'parentNode' of null

This is my approach：
https://codesandbox.io/s/charming-feather-08l13?file=/src/pages/Home/index.vue

**Comment by posva** [comment]
yeah, that works in that scenario. 
Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!
