### ISSUE TITLE
When unmounting my vue app i get an error

### ISSUE THREAD

**Issue by danielgran** [vuejs/vue-router-next#1055]
### Version
4.0.10

### Reproduction link
[https://random.link](https://random.link)

### Steps to reproduce
Unmount an vue router app

### What is expected?
proper unmount

### What is actually happening?
not unmounting, error is thrown
removeHistoryListener is not a function

---
vue-router.esm-bundler.js?6c02:3347 Uncaught TypeError: removeHistoryListener is not a function
    at Object.app.unmount (vue-router.esm-bundler.js?6c02:3347)

**Comment by danielgran** [comment]
![image](https://user-images.githubusercontent.com/6535118/127744334-a0110124-9b83-41d4-80c0-532ba3ed19a0.png)

**Comment by danielgran** [comment]
I actually tried it with no routes (empty array) and i get the same issue

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by danielgran** [comment]
@posva yo that is a bug

**Comment by posva** [comment]
The provide a boiled down repro

**Comment by danielgran** [comment]
https://jsfiddle.net/vqkjf6s0/1/

**Comment by danielgran** [comment]
just take a look at the javascript console

**Comment by danielgran** [comment]
<img width="504" alt="image" src="https://user-images.githubusercontent.com/6535118/127748006-cc50e229-96f2-40c9-a5d0-d60dcab0a18e.png">

**Comment by danielgran** [comment]
without the vue router this issue does not appear
https://jsfiddle.net/bakmLtc6/5/

Let me know if you need any additional information!

Best Regards, Daniel

**Comment by danielgran** [comment]
@posva
