### ISSUE TITLE
Unmounting Vue Root Instance fails

### ISSUE THREAD

**Issue by danielgran** [vuejs/vue-router-next#1056]
### Version
4.0.10

### Reproduction link
[https://jsfiddle.net/vqkjf6s0/1/](https://jsfiddle.net/vqkjf6s0/1/)

### Steps to reproduce
Make Vue use the router, and after app.mount('#app') instantly unmount via app.unmount() (Reproduction jsfiddle below)

### What is expected?
No error and at least proper unmount of the root vue instance, which is not happening

### What is actually happening?
RemoveHistoryListener Not found, still displaying the vue root component (no unmount), i think at that point the vue instance is broken

Error thrown in JS console

Uncaught TypeError: removeHistoryListener is not a function
    at Object.app.unmount (vue-router@next:3359)
    at ?editor_console=:177

**Comment by danielgran** [comment]
the problem is that the complete unmount method fails and does not get through left with still displaying the whole app

**Comment by posva** [comment]
What is the case to unmount the app before it's even running?

In practice, this shouldn't fail. You can wait for the router to be ready before unmounting the app: `router.isReady().then(() => app.unmount())`

**Comment by danielgran** [comment]
I totally agree that this should not fail in practice. BUT (as always...) the single thing where I faced this issue (and can imagine other will trip over it, too) was stopping and starting my whole frontend in some unit tests or conditional unmounting right after the start (for whatever reason). I would love to see at least an proper error from the router to really get why my `.unmount()` fails and therefore proper error messages in possible unit tests. The best would - oc imo - be when the `.unmount()` would wait for any plugin to be ready or abort and just kill all plugins (I know the internals of vue far to less to evaluate that, I only assume) - but I think that's not in your hands, isn't it?
In any case, let me know if you need any additional information.
Best Regards, Daniel Gran

**Comment by posva** [comment]
The usage of unmounting right away is still wrong but it shouldn't be a problem in the next release with d8fb7d0 which will be out in a week or two
