### ISSUE TITLE
[Feature Request] The `$route.key` property is a unique string associated with current route

### ISSUE THREAD

**Issue by liho98** [vuejs/vue-router-next#1065]
### What problem does this feature solve?
The $route.key property is a unique string associated with this location. On the initial location, this will be the string default. On all subsequent locations, this string will be a unique identifier.

This can be useful in situations where you need to keep track of 2 different states for the same URL. For example, you could use this as the key to some network or device storage API.

React router package has this feature as well. https://github.com/ReactTraining/history/blob/master/docs/api-reference.md

### What does the proposed API look like?
$route.key //some hash string eg.6cfa79

The has value persist when refresh the tab, but is different when open new tab with same route. (Example usecase: checking same instance is declared between tabs on same browser).

**Comment by posva** [comment]
Do you have more information apart from that document about use cases?

This can be implemented in user land with navigation guards, so it could be a cookbook page if there are real scenarios the router can't cover in its current state
