### ISSUE TITLE
support multiple router instance in one page

### ISSUE THREAD

**Issue by agileago** [vuejs/vue-router-next#1071]
### Version
4.0.11

### Reproduction link
[https://github.com/agileago/vite-mfe](https://github.com/agileago/vite-mfe)

### Steps to reproduce
check repository readme

### What is expected?
vue-router should keep history right

### What is actually happening?
not right

**Comment by posva** [comment]
You should probably share the history instance with both routers. Regarding the PR You submitted, if this can be done extending the history implementation, then it should be an external package

**Comment by agileago** [comment]
@posva I think `vue-router` should consider micro front end situation like single-spa. because vue-router depend `history.state` deeply. so it is hard to integrate with other router in one page. like react-router...., i think we should keep library   
no effect

**Comment by posva** [comment]
Vue router works in micro frontends. The history sharing should make it the desired behavior. You could also reuse the whole router in both apps and use named views.

Relying on the state is necessary for many features and won't change but one can implement a different history that uses history state differently. This is however specific to your application and note that coming here to ask me to develop it for you is not acceptable.
Micro frontends vary heavily and unfortunately we cannot cater for all the use cases out of the box, we can, and we do open the api enough for people to develop the own abstractions that fits their need.

**Comment by agileago** [comment]
I am sorry for disturbing you. it is just a user case. i think we can change tiny code to adjust this case. i am a user too.
