### ISSUE TITLE
Catch issue with "isAsyncWrapper"

### ISSUE THREAD

**Issue by AbdullaevTimur** [vuejs/vue-router-next#1083]
### Version
4.0.11

### Steps to reproduce
When I try to pash new route, always catch error associated with "isAsyncWrapper";
`
async goToRoute({name}) {
  try {
     await this.$router.push({name})
  } catch (err) {
    throw new Error(`Problem handling something: ${err}.`);
  }
},
`

### What is expected?
$router should resolve navigation

### What is actually happening?
Navigation peorcess broken with error "Uncaught (in promise) TypeError: i.type is undefined"

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by jjag3r** [comment]
@AbdullaevTimur I had the same issue. The problem was that I loaded whole `ref` variable to some element (in my case `<td>`) and router somehow didn't know how to destroy that.

Hope that helped...
