### ISSUE TITLE
onError handler params `undefined`

### ISSUE THREAD

**Issue by logustra** [vuejs/vue-router-next#1085]
### Version
4.0.11

### Reproduction link
[https://codesandbox.io/s/sad-sun-yulj2?file=/src/utils/routerGuard.ts](https://codesandbox.io/s/sad-sun-yulj2?file=/src/utils/routerGuard.ts)

### Steps to reproduce
1. Define two async routes
```
const router = createRouter({
  history: createWebHistory(),
  routes: [
    {
      path: '/home',
      name: 'home.index',
      component: () => import('./views/home.vue')
    }
    {
      path: '/about',
      name: 'about.index',
      component: () => import('./views/about.vue')
    }
  ]
})
```

2. Use onError handler 
```
router.onError((error, to, from) => {
  console.log(error)
  console.log(to) 
  console.log(from)
})
```

3. run `pnpm build:dev && pnpm serve`
4. go to `localhost:3000`
5. open `about.vue`, and change the text
5. split terminal, run `pnpm build:dev` again and make sure `about.[hash].js` different from the previous build
6. go back to `localhost:3000` and without refresh the browser click `about`
7. error message shown
```
// console.log(error)
Couldn't resolve component "default" at "/about"

// console.log(to)
undefined

// console.log(from)
undefined
```

### What is expected?
show `RouteLocationNormalized` value onError handler
```
router.onError((error, to, from) => {
  console.log(error)
  console.log(to) // RouteLocationNormalized
  console.log(from) // RouteLocationNormalized
})
```

### What is actually happening?
`RouteLocationNormalized` onError handler undefined

**Comment by posva** [comment]
Vue Router only takes the error that is thrown and gives it to you: https://jsfiddle.net/hsnyto2x/
If you need/want to handle this kind of error, make sure your lazy imports throw a specific error you want to handle if they fail so you can check for it in the `onError()`.
We cannot add any specific handling of `undefined` errors as one could intentionally `throw undefined`.
