### ISSUE TITLE
链接中query参数在hash之前，route.query取不到值

### ISSUE THREAD

**Issue by yyj961010** [vuejs/vue-router-next#1086]
### Version
4.0.11

### Steps to reproduce
在浏览地址栏输入http://localhost:8010/?a=1#/，然后用route.query，取到的是个空对象
将query放在hash后面，就可以正常取到值了：http://localhost:8010/#/?a=1

### What is expected?
{a:1}

### What is actually happening?
{}

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
