### ISSUE TITLE
组合式为什么没有onBeforeRouteLeave,由什么替代？我需要进入页面时把弹窗框显示出来

### ISSUE THREAD

**Issue by GavinChain** [vuejs/vue-router-next#1096]
### What problem does this feature solve?
组合式为什么没有onBeforeRouteLeave,由什么替代？我需要进入页面时把弹窗框显示出来

### What does the proposed API look like?
组合式为什么没有onBeforeRouteLeave,由什么替代？我需要进入页面时把弹窗框显示出来

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
