### ISSUE TITLE
usage of useLink() in a <script setup> kills the entire application

### ISSUE THREAD

**Issue by ZainW** [vuejs/vue-router-next#1111]
### Version
4.0.11

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/github/ZainW/uselink-reproduction/tree/main/?file=/src/App.vue)

### Steps to reproduce
go to reproduction link, uncomment line 10, wait for hmr/reload, you will now witness that the application is completely broken

### What is expected?
I expect things like isActive to not break the app and be an accessable property in my component

### What is actually happening?
it crashes the entire application

---
this happens with all properties from useLink() from what i can tell, i just did the minimum for the reproduction

**Comment by posva** [comment]
You need to pass an argument to useLink like shown in docs

**Comment by ZainW** [comment]
My apologies for wasting your time
