### ISSUE TITLE
params in route-link is not work ok

### ISSUE THREAD

**Issue by Silentdoer** [vuejs/vue-router-next#1113]
### Version
4.0.11

### Reproduction link
[http://localhost:8080/](http://localhost:8080)

### Steps to reproduce
`<route-link :to="{path: '/about', params: {jump: 'goto'}}">`
when i click the route-link, i can not catch params in router.beforeEach by to.params

### What is expected?
console.log(JSON.stringify(to.params)) should print {'jump': 'goto'}

### What is actually happening?
prints {}

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
