### ISSUE TITLE
Router View and Suspense together break Reactivity

### ISSUE THREAD

**Issue by Subwaytime** [vuejs/vue-router-next#1114]
### Version
4.0.11

### Reproduction link
[github.com](https://github.com/Subwaytime/suspense-router-bug)

As seen in this other [reproduction via sfc](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCBDb21wb25lbnQgZnJvbSAnLi9Db21wLnZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuXG5jb25zdCBwZXJjZW50YWdlID0gcmVmKDApXG5cbmNvbnN0IGRvbmUgPSAoKSA9PiB7XG4gIGNvbnNvbGUubG9nKCdkb25lJylcbn1cblxuY29uc3QgbG9hZGluZyA9ICgpID0+IHtcbiAgY29uc29sZS5sb2coJ2xvYWRpbmcnKVxuICBcbiAgc2V0SW50ZXJ2YWwoKCkgPT4ge1xuICAgIHBlcmNlbnRhZ2UudmFsdWUgKz0gMVxuICB9LCAxMDAwKVxufVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPHN1c3BlbnNlIHRpbWVvdXQ9XCIwXCIgQGZhbGxiYWNrPVwibG9hZGluZ1wiIEByZXNvbHZlZD1cImRvbmVcIj5cbiAgICA8dGVtcGxhdGUgI2RlZmF1bHQ+XG4gICAgICA8Y29tcG9uZW50IDppcz1cIkNvbXBvbmVudFwiIC8+XG4gICAgPC90ZW1wbGF0ZT5cbiAgICA8dGVtcGxhdGUgI2ZhbGxiYWNrPlxuICAgICAgPGRpdj5cbiAgICAgICAgPGgxPkxvYWRpbmcge3sgcGVyY2VudGFnZSB9fSA8L2gxPlxuICAgICAgPC9kaXY+XG4gICAgPC90ZW1wbGF0ZT5cbiAgPC9zdXNwZW5zZT5cbjwvdGVtcGxhdGU+IiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJDb21wLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgQ2hpbGRcbjwvdGVtcGxhdGU+XG48c2NyaXB0IHNldHVwPlxuYXdhaXQgbmV3IFByb21pc2UoKCkgPT4ge30pXG48L3NjcmlwdD4ifQ==) created by @skirtles-code, this does only occur when `router-view` is added not on `suspense` only.

### Steps to reproduce
Using `suspense` and `router-view` as mentioned from the official Vue 3 Docs it runs into the issue that an increasing counter loses all reactivity inside the `#fallback` area of suspense. Without `router-view` everything works fine.

### What is expected?
Expected is that any variable (prop, ref etc) is holds its reactivity inside the `#fallback` slot same as default area. With or without `router-view`.

### What is actually happening?
Adding `router-view` around suspense breaks reactivity on `#fallback` slot.

**Comment by posva** [comment]
Can you create a new git repo without the node_modules folder?

**Comment by Subwaytime** [comment]
Oh sorry! Didnt see that it got commited, let me just remove them quickly!

**Comment by Subwaytime** [comment]
Its cleaned up now! Same Repo, with gitignore and npmignore. Sorry for the inconvenience

**Comment by posva** [comment]
Your package.json doesn't have any deps, can you create a proper project with vite to show the problem?

**Comment by Subwaytime** [comment]
Uff sorry again, having a bad day! Updated the packages now!

**Comment by posva** [comment]
Fixed un Vue
