### ISSUE TITLE
Does not define linkActiveClass on route link

### ISSUE THREAD

**Issue by atach** [vuejs/vue-router-next#1117]
### Version
4.0.11

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/vue3x-route-subpage-wjnwm)

### Steps to reproduce
This is a simple example where "router-link-active" does not work on parent elements.

Its Vue2 example (its working):
https://codesandbox.io/s/vue2x-route-subpage-wzp9w

Exactly the same example on Vue3  (not working):
https://codesandbox.io/s/vue3x-route-subpage-wjnwm

### What is expected?
Parent link is tagged with class

### What is actually happening?
nothing

**Comment by posva** [comment]
This is covered in the migration guide in docs

**Comment by white-gecko** [comment]
I assume you are referencing https://router.vuejs.org/guide/migration/#removal-of-the-exact-prop-in-router-link, but I don't get based on this, how to get the original behavior as explained in https://github.com/vuejs/router/issues/1117#issue-996388356 is there any other resource explaining this in depth?
