### ISSUE TITLE
Route not matched properly after browser refresh

### ISSUE THREAD

**Issue by Metalmi** [vuejs/vue-router-next#1123]
### Version
4.0.11

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/angry-sea-v3fxh?file=/src/components/Blog.vue)

### Steps to reproduce
1. Open "Blog Post" route (it is matched correctly)
2. Refresh browser window (it wrongly matches "Blog" route)

### What is expected?
It is expected to match the correct route after browser refresh, as with in-app navigation.

### What is actually happening?
It matches the wrong route.

---
I also checked on Path Ranker (https://paths.esm.dev/?p=AAMeJYyAwQYc7ALcA-ANgVPgUABABwMmCVA_QFAAwBABsqDZpi0A5Q..&t=/blog/some-article) and there it works fine.

**Comment by posva** [comment]
This is because you are using end: false, so it matches the one with the custom regexp. Remove that option, you most likely don't need it.
It's there for dynamic routing but some rankings are still incompatible.

**Comment by Metalmi** [comment]
Thank you, it works as it should without it.

**Comment by ZouJiu1** [comment]
this is my answer, it may be helpful [https://stackoverflow.com/a/79302293/17601704](https://stackoverflow.com/a/79302293/17601704)

In vue router 4 for vue3

## first 
try to find the mounted APP.vue, when you refresh the webpage, the App.vue will be loaded firstly. So make sure you don't mounted `this.$router.push("/")`

```Javascript []
  mounted() {
     this.$router.push("/");
}
```
**the correct thing**
```javascript
mounted() {
    this.loading();
},
methods: {
  loading() {
    if(document.URL=="http://localhost:9000/" || document.URL=="https://zoujiu.com.cn/"
          || document.URL=="http://zoujiu.com.cn/" || document.URL=="http://localhost:9000/#/"
          || document.URL=="http://zoujiu.com.cn/#/"|| document.URL=="https://zoujiu.com.cn/#/"
        ) {
          this.$router.push({ path: '/'});
        }
  }
}
```

## deployment
I use this history with nginx ssl https
```javascript
const router = createRouter({
  // history: createMemoryHistory(),
  history: createWebHashHistory(),
  // history: createWebHistory(),
  routes:constantRoutes,
})
```

## development
I use this history 
```javascript
const router = createRouter({
  // history: createMemoryHistory(),
  // history: createWebHashHistory(),
  history: createWebHistory(),
  routes:constantRoutes,
})
```

this is myown website [http://zoujiu.com.cn](http://zoujiu.com.cn).
