### ISSUE TITLE
 Dynamically added child with an empty path isn't being rendered

### ISSUE THREAD

**Issue by Namysh** [vuejs/vue-router-next#1124]
### Version
4.0.11

### Reproduction link
[stackblitz.com](https://stackblitz.com/edit/vue-router-next-issue?file=src/main.js)

### Steps to reproduce
Go to the path of the dynamically added child of **Root** (as it is an empty path, stick to the default url in the provided reproduction environment)

### What is expected?
**Test.vue**  should be rendered in **App.vue**'s `router-view` and  **B.vue** should be rendered in **Test.vue**’s `router-view`

### What is actually happening?
**Test.vue** is properly rendered in **App.vue**'s `router-view` but **B.vue** isn't rendered in **Test.vue**'s `router-view`

---
This issue only occurs when using an empty path for the dynamically added child. With a non empty path and adding the child dynamically, it works. It works too with an empty path when the child is not added dynamically but defined directly in **Root**'s `children` property

**Comment by posva** [comment]
All root paths must start with a leading slash. There should be a warning about it in the console

**Comment by Namysh** [comment]
I don't see a warning but I added it anyway, thanks. That done, the main issue still remains. Or maybe it's the expected behavior and so not an issue 🤔

**Comment by posva** [comment]
You also need to renavigate after adding routes like shown in docs

**Comment by Namysh** [comment]
A solution I found is to check that the matcher that is going to be inserted is not a child of the current itterated matcher here :
https://github.com/vuejs/router/blob/8744ea77eb71a876cc1e0e2675904c76578fb025/src/matcher/index.ts#L214-L220

So with this function :
```js
  function isChildOf(child: RouteRecordMatcher, parent: RouteRecordMatcher): Boolean {
    return parent.children.some(currChild => {
      if (currChild === child) return true

      return isChildOf(child, currChild)
    })
  }
```
Adding `!isChildOf(matcher, matchers[i])` as another condition in the while loop works.

What do you think about it ?
