### ISSUE TITLE
Router#resolve inside `computed` causes re-run during navigation

### ISSUE THREAD

**Issue by glen-84** [vuejs/vue-router-next#1130]
### Version
4.0.11

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/lucid-boyd-7yixn?file=/src/App.vue)

### Steps to reproduce
1. Click `Home` and `About` a few times.
2. Check the console, and note that the computed is re-triggering on each navigation.

### What is expected?
A method like `Router#resolve` should not have "side-effects". It's not usable inside computed/composition functions, as it causes a re-run.

### What is actually happening?
It's causing a re-trigger of the computed method.

---
I could be wrong, but I think it's because `resolve` is reading from `currentRoute`, and `currentRoute` is being written to during navigation.

Would it be possible to read the values from `currentRoute` without triggering dependencies?

**Comment by posva** [comment]
This is intentional and necessary for correct resolving. If you don't care about the current location, you can use `START_LOCATION`:

```js
import { START_LOCATION } from 'vue-router'

router.resolve('/about', START_LOCATION)
```
