### ISSUE TITLE
当使用动态添加路由时，页面上已经存在的 router-link 会因为匹配不到因权限限制而不能添加到路由系统的路由时，会报错

### ISSUE THREAD

**Issue by jiankafei** [vuejs/vue-router-next#1132]
### What problem does this feature solve?
router-link 不应该在这种情况下报错，但可以打印提示，并且在 v-slot 里返回是否存在该路由的标识字段，以便开发者通过该字段响应式的显示和隐藏 router-link 内部的元素。不仅没有了不友好的报错，而且可以把这种情况做成一种功能，何乐而不为呢！

### What does the proposed API look like?
在 v-slot 中提供 hasRoute 字段，表示该路由当前是否存在，并且是响应式的，可以做到跟随路由系统动态显示和隐藏内部元素。

```js
<router-link
  to="/about"
  custom
  v-slot="{ navigate, hasRoute}">
  <div @click="navigate" v-if="hasRoute">导航</div>
</router-link>
```

**Comment by posva** [comment]
You are free to create your own router link abstraction and add `hasRoute` by calling `router.resolve()` to check for existing links but this is app-specific and router-link is meant to stay light and generic.

**Comment by jiankafei** [comment]
@posva I know that I can use the resolve method to determine whether the route exists, but how to solve the error reported by the router link itself?

**Comment by jiankafei** [comment]
@posva Moreover, I use "router-link" instead of "router. push()", so I can't use the "resolve()" method.
