### ISSUE TITLE
Type checking for route component props – is it possible?

### ISSUE THREAD

**Issue by zigomir** [vuejs/vue-router-next#1134]
### What problem does this feature solve?
With `volar`, `vue-tsc` and [defineEmits](https://v3.vuejs.org/api/sfc-script-setup.html#typescript-only-features) TypeScript story for Vue become quite amazing.

I'm wondering if you think it would be possible to type check route props? i.e. if component defines props and is used as a route component, could we make TS check if right props are being passed to it?

### What does the proposed API look like?
I suppose `_RouteRecordProps = boolean | Record<string, any> | ((to: RouteLocationNormalized) => Record<string, any>)` would need to somehow be changed to take a more specific type than `Record<string, any>`.

**Comment by posva** [comment]
Do you mean exposing an interface that can be extended to **manually add all** possible props? Is that really useful?

**Comment by zigomir** [comment]
I don't think so. Imagine if component has required props defined and 

a) you forget to set `props: true`, you get type error
b) you specify props on the route, but omit required prop or make it a wrong type, you get type error

This I think would be useful. Type checking would ensure you're passing all required props of correct type to the component.  Like what `volar` or `vue-tsc` do when you use component and either forget to specify required prop or pass a wrong value type to it.

Again, I don't know if that's possible / feasible, but it would imo be quite nice to have.

**Comment by posva** [comment]
I don't think this is feasible because there is nowhere to connect both types: the ones from the route and the props of the component.
What I do plan on adding are helpers to generate those types and make navigation type safe like the existing PR from @pikax but as automatic as possible, making the user only add the needed types to create the missing connections and infer as much as possible.

**Comment by zigomir** [comment]
Nice. I was mostly just curious if it's even feasible – thank you for the answer and all your work on the `vue-router`! ❤️

**Comment by nicooprat** [comment]
We figured out a way to do it, it's a bit cumbersome but works great. You must share the props object alone to be able to extract its types like this:

```ts
import type { ExtractPropTypes } from 'vue';

const FooProps = {
  category: {
    type: String as PropType<string>,
    default: null,
  },
} as const;

const routes = [{
  path: 'foo',
  props: ({ params }) =>
    ({
      category: 1, // error because it's not a string
    }) as ExtractPropTypes<typeof FooProps>,
  name: 'Foo',
  component: () => import('@/pages/Foo.vue'),
}]
