### ISSUE TITLE
vue-router from version 4.0.7 onwards, in Chrome 57, the console reports an error: Uncaught SyntaxError: Unexpected token ...

### ISSUE THREAD

**Issue by lileiseven** [vuejs/vue-router-next#1136]
### Version
4.0.7

### Reproduction link
[jsfiddle.net/hvepxno1/](https://jsfiddle.net/hvepxno1/)

### Steps to reproduce
use vue-router 4.0.7.

### What is expected?
no console error.

### What is actually happening?
console reports an error: Uncaught SyntaxError: Unexpected token ...

**Comment by posva** [comment]
I tested on chrome 49 and 57 with the code you provided and it works without a syntax error.
If you have the line where the syntax error is, it should be easier to fix. Probably a very straightforward PR too 🙂

**Comment by yuxuewen** [comment]
Error in Android 7.0 WebView。

Error Message: Unexpected token ...     at Object../node_modules/@vue/devtools-api/lib/esm/proxy.js

**Comment by posva** [comment]
Added it at https://github.com/vuejs/devtools/commit/e6b2f05eeef3839f9fba34532dcceaeb665eba1a

If you see any of those, it's an easy PR in vue-devtools repository but this cannot be fixed here
