### ISSUE TITLE
In nested routes, links to parent routes don’t receive router-link-active class

### ISSUE THREAD

**Issue by timpulver** [vuejs/vue-router-next#1138]
### Version
4.0.11

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/vue-router-nested-params-issue-x5944)

### Steps to reproduce
When using a nested route, which can have many children (*) the parent routes don’t receive the active class.
In the codesandbox demo click on the `/files/a/b/c` link.

### What is expected?
In the codesandbox example, I would expect, that clicking on the link `/files/a/b/c` results in all `/file` links receiving the `router-link-active` class.

### What is actually happening?
Only the link to the current route receives the `router-link-active` class, but not links to parent routes.

---
I tried different variations, including regex, `+`, `*`, but nothing worked – only the current route receives the `router-link-active` class.
I also read the migration guide and every related issue and think this might be a vue-router bug.

**Comment by posva** [comment]
This is mentioned in the migration guide and in other issues as well.

Please, search existing issues and pull requests before opening issues, it saves maintainers a lot of time 🙏

**Comment by timpulver** [comment]
> Please, search existing issues and pull requests before opening issues, it saves maintainers a lot of time 🙏

I had a look at various other issues and the migration guide before, but couldn’t find a solution.

For others, the following works for me for correct placement of `router-active-link` classes on parent links for nested routes :
```
route   -> component
----------------------
/a         -> MyView.vue (redirect to /a/b)
/a/b      -> MyView.vue
/a/b/c   -> MyView.vue
...
```

_router/index.ts:_
```typescript
import { h } from "vue";
import {
  createRouter,
  createWebHistory,
  RouteRecordRaw,
  RouterView,
} from "vue-router";
import MyView from "../views/MyView.vue";

const routes: Array<RouteRecordRaw> = [
  {
    path: "/a",
    name: "MyView",
    props: true,
    component: { render: () => h(RouterView) },
    children: [
      { path: "", redirect: "/a/b" },
      {
        path: ":base",
        component: { render: () => h(RouterView) },
        children: [
          { path: "", component: MyView },
          {
            path: ":sub+",
            component: MyView,
          },
        ],
      },
    ],
  },
];

const router = createRouter({
  history: createWebHistory(process.env.BASE_URL),
  routes,
});
```

The `a` part is static, the `b` and `c` part are available as props in the view (unescaped). `b` as a string, `c` as an array of strings, because it is a repeatable path segment.

The important part seems to be to create one route entry with `children`, because route matching is done via the route record and not any more via the path as it was before. If two individual route records are being created, the parent won’t match in Vue Router 4.

_MyView.vue:_

```html
<template>
  ...
</template>

<script setup lang="ts">
import { withDefaults } from "vue";

interface Props {
  base: string;
  sub?: string[];
}

const props = withDefaults(defineProps<Props>(), {
  baseFolder: "",
  folders: () => [] as string[],
});
</script>
```
