### ISSUE TITLE
Scroll behavior not respecting offset on hashchange

### ISSUE THREAD

**Issue by vincerubinetti** [vuejs/vue-router-next#1147]
### Version
4.0.0

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/cool-wildflower-qqoef)

### Steps to reproduce
In the reproduction:

Click on the pound sign link next to test heading. The scrollBehavior function is called, but the offset provided is not respected. Reload the page with the hash still in the url. The offset is respected.

Changing the "a" component to a "router-link" component seems to make the issue go away.

### What is expected?
The offset (when providing an target element and a top/left) should be respected.

### What is actually happening?
It is not being respected. It's as if no offset were applied. The scrollBehavior function is being called properly (even using an "a"), so I believe the intent is to support this behavior.

---

I cannot make use of "router-link" in this case because I am creating the pound sign links with a custom vue directive, which can only create regular html elements.

**Comment by vincerubinetti** [comment]
Wow thanks for looking into this. That's pretty unfortunate... I seem to run into these small bugs in Chromium all the time but never firefox.

Luckily I'm working on a product that wont be release for sometime, so I'm just going to ignore this and hope it's fixed by that time. Though this will undoubtedly be useful information to someone. And I'll keep it handy in case they never fix it!

**Comment by posva** [comment]
I opened https://bugs.chromium.org/p/chromium/issues/detail?id=1260895 as they might want to align with Firefox and Safari
