### ISSUE TITLE
meta data provided to children meta

### ISSUE THREAD

**Issue by ijcnvv** [vuejs/vue-router-next#1183]
### Version
4.0.12

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/busy-water-sjcow?file=/src/App.vue)

### Steps to reproduce
{
  name: 'a',
  meta: {
    title: 'a title'
  },
  children: [{
    name: 'b',
  }]
}

### What is expected?
b.meta.title is undefined

### What is actually happening?
b.meta.title is 'a title'

**Comment by posva** [comment]
This is intended and documented in the breaking changes section.
