### ISSUE TITLE
Why type `RouteMeta` and `RouteRecordName` allows `symbol`?

### ISSUE THREAD

**Issue by n0099** [vuejs/vue-router-next#1185]
### What problem does this feature solve?
It cause me hard to null coalescing `route.name`.
> TS2345: Argument of type 'RouteRecordName' is not assignable to parameter of type 'string | undefined'.   Type 'symbol' is not assignable to type 'string | undefined'.

![](https://user-images.githubusercontent.com/13030387/139787576-1c4bd094-6061-4dbb-924a-185e5a4eeadb.png)
https://github.com/vuejs/vue-router-next/blob/22739c3918f1ce28e845a72019f85290bed9629d/src/types/index.ts#L194
https://github.com/vuejs/vue-router-next/blob/22739c3918f1ce28e845a72019f85290bed9629d/src/types/index.ts#L266

### What does the proposed API look like?
Remove `symbol` from these types.

**Comment by n0099** [comment]
And due to the limited scope of type guard, I can't 
![](https://user-images.githubusercontent.com/13030387/139788181-cae4b885-18b6-4d67-ae6d-0b6e0c44373a.png)
instead I have to write: `(_.isString(route.name) ? route.name : '') + '+p'`, or write a type guard function like
```js
const routeNameString = () => _.isString(route.name) ? route.name : '';
```
then replace `route.name` with `routeNameString()` everywhere.

**Comment by posva** [comment]
It's to allow creating routes without giving them a name so they can be referenced anyway

**Comment by n0099** [comment]
> It's to allow creating routes without giving them a name so they can be referenced anyway

But this feature let me hard to narrowing type of `route.name`, I don't want to write so many ternary type guards with `_.isString(route.name)`
