### ISSUE TITLE
[Vue warn]: injection "Symbol([vue-router]: route location)" not found. 

### ISSUE THREAD

**Issue by u007** [vuejs/vue-router-next#1187]
### Version
4.0.12

node v14.18.1

### Reproduction link
[github.com](https://github.com/u007/vuerouterissue1)

### Steps to reproduce
package depencies:
"dependencies": {
    "vue": "^3.2.16",
    "vue-router": "^4.0.12"
  },

import { ref } from 'vue'
import { useRouter, useRoute } from 'vue-router'

const route = useRoute()
console.log('route?', route);// this returned undefined

### What is expected?
useRoute should return route ob

### What is actually happening?
route? undefined

[Vue warn]: injection "Symbol([vue-router]: route location)" not found. 
  at <HelloWorld msg="Hello Vue 3 + TypeScript + Vite" > 
  at <App> runtime-core.esm-bundler.js:6584:16

---
please check on components/login/login.vue for example

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

That's a whole project there... You are likely missing the `app.use(router)` or calling `useRoute()` before calling `app.use(router)`
