### ISSUE TITLE
Apply optional parameters to children

### ISSUE THREAD

**Issue by fardolieri** [vuejs/vue-router-next#1188]
### Version
4.0.12

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/route-params-vue-router-4-examples-forked-xkddx)

### Steps to reproduce
Click '/users/3/4', then 'Show'

### What is expected?
I would expect the optional parameter `info` to be applied to the `user-show` route the same way `id` is applied.

### What is actually happening?
Instead it vanishes when I navigate using the named path.

---
If I use named paths to navigate, my params are automatically applied to any child routes, which is a very nice feature. But optional parameters are somehow ignored. I wonder if that is a bug or the expected behavior.

Will I need to explicitly add the params to all my router-links like so?
```
<router-link :to="{ name: 'user-show', params: $route.params }">Show</router-link>
```
In my opinion that is a little verbose and gets even messier when trying to actually change a parameter:
```
<router-link :to="{ name: 'user-show', params: { ...$route.params, id: 17 }">Show</router-link>
```

**Comment by posva** [comment]
This is intended. Optional parameters must be **explicitely** set because that way you can omit them when navigating to a location that also accepts that param and they won't be kept. It was discussed in previous issues in vue-router repo where you will be able to find the full rationale.
