### ISSUE TITLE
nested route not render 

### ISSUE THREAD

**Issue by TyTTT-T** [vuejs/vue-router-next#1199]
### Version
4.0.12

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/elastic-water-hx32f?file=/src/App.vue)

### Steps to reproduce
Mobile 1 router-link use named route to navigation to Mobile component
Mobile 2 router-link use literal string  to navigation to Mobile component

in router.js file, the Mobile route has property children, and there are a route with path: '', name: 'First'

### What is expected?
After click Mobile 1 and Moblie 2, the url is matched,  First.vue will be rendered inside  Moblie's router-view.

### What is actually happening?
By literal string router-link, First.vue will be rendered inside Moblie's router-view.
By named route router-link, First.vue will `not` be rendered inside Mobile's router-view

**Comment by posva** [comment]
This is working as expected and is documented

**Comment by TyTTT-T** [comment]
> This is working as expected and is documented
I don't understand what your mean, is it right that it will  not be rendered inside router-view with named route router-link way?
