### ISSUE TITLE
Passing props to route component

### ISSUE THREAD

**Issue by cexbrayat** [vuejs/vue-router-next#120]
Note: https://new-issue.vuejs.org/?repo=vuejs/vue-router-next is not displaying `vue-router-next`

`vue-router` allows to specify `props: true` in a route to pass the params as props to a route component. After playing a bit with it, I think this is not the case in `vue-router-next`? Is it not implemented yet or do you plan to drop this feature?

**Comment by posva** [comment]
It's not yet implemented :)

**Comment by posva** [comment]
This is implemented on master
