### ISSUE TITLE
Both the pushState and replaceState methods are triggered!

### ISSUE THREAD

**Issue by banlify** [vuejs/vue-router-next#1209]
### Version
4.0.12

### Reproduction link
[stackblitz.com](https://stackblitz.com/edit/vitejs-vite-dsc3kk?devtoolsheight=33&file=src/main.js)

### Steps to reproduce
Click router-link to jump to the page

### What is expected?
Only the pushState event is raised, not the replaceState event

### What is actually happening?
Both pushState and replaceState events are raised

**Comment by posva** [comment]
This is an implementation detail necessary to provide proper information like the navigation direction and other useful and widely requested features. Note `replaceState()` is the only way to modify the history state of the current entry

**Comment by banlify** [comment]
> This is an implementation detail necessary to provide proper information like the navigation direction and other useful and widely requested features. Note `replaceState()` is the only way to modify the history state of the current entry (which is why it is called in this scenario in vue router)

This is normal in vue2 and will only trigger `pushState()` but not `replaceState()`
