### ISSUE TITLE
Could routerView slot provide depth property

### ISSUE THREAD

**Issue by LoveofRedMoon** [vuejs/vue-router-next#1217]
### What problem does this feature solve?
When component with <router-view /> in, when it used multiplex, it is difficut to get depth in this router-view

https://jsfiddle.net/o0sLnzwj/2/

### What does the proposed API look like?
normalizeSlot(slots.default, { Component: component, route, depth }) ||
                  component)

**Comment by posva** [comment]
What is the use case?

**Comment by LoveofRedMoon** [comment]
> What is the use case?

For example, user can provide meta data: 'useScrollBar' property, this means i will auto wrap a el-scrollbar outside it.
But `$route.meta` or `route.meta` which property in default router-view slot does not show current depth's meta info:
```js
const route = [{
    path: '/',
    component: WrapView,
    meta: {
        useScrollBar: false
    }
    children: [{
        path: '/a',
        component: WrapView,
        meta: {
            useScrollBar: true
        }
    }]
}]
```
`$route.meta` or `route.meta` all shows `useScrollBar: true`; But first component WrapView should get `useScrollBar: false`

**Comment by posva** [comment]
but in that scenario, you know the depth of each view already, so you can do `$route.matched[0].meta`

**Comment by LoveofRedMoon** [comment]
> but in that scenario, you know the depth of each view already, so you can do `$route.matched[0].meta`

as the example above, some components might multiplexing（WrapView component）and in this component, i did not know the depth of this view

**Comment by posva** [comment]
Rather than providing the depth, which is very low level and even an implementation detail, I think exposing the matched routeRecord (`$route.matched[i]`) makes more sense. This needs further investigation though, as using it could trigger the render in unexpected ways.

**Comment by LoveofRedMoon** [comment]
> Rather than providing the depth, which is very low level and even an implementation detail, I think exposing the matched routeRecord (`$route.matched[i]`) makes more sense. This needs further investigation though, as using it could trigger the render in unexpected ways.

This property will not be used unless in frames. Provide property depth can easily access such as `$route.matched[depth - 1]` and provide primitive type `number` may have less impact.

**Comment by posva** [comment]
Note you can currently inject it: https://github.com/vuejs/vue-router-next/blob/master/src/index.ts#L29

**Comment by LoveofRedMoon** [comment]
> Note you can currently inject it: https://github.com/vuejs/vue-router-next/blob/master/src/index.ts#L29

thanks！I have not pay attention to which key I can inject.

**Comment by awacode21** [comment]
> https://github.com/vuejs/vue-router-next/blob/master/src/index.ts#L29

This is a dead link, but i really need to get that info. Did only the url change or is the example no longer available?

**Comment by posva** [comment]
I updated the link. the variable is `viewDepth` in case the link dies in the future, the variable should be easy to find in source code

**Comment by awacode21** [comment]
thank you!

**Comment by awacode21** [comment]
works perfectly for me and saved my day!
