### ISSUE TITLE
404页面 /.1+1 不能重定向/

### ISSUE THREAD

**Issue by 0773** [vuejs/vue-router-next#1218]
### Version
4.0.12

### Reproduction link
[10.0.0.88/abc/.1+1](http://10.0.0.88:1180/abc/.1+1)

### Steps to reproduce
代码如下，两种写法都不能重定向到 /

{

    // path: '/:catchAll(.*)',
        
    path: '/:pathMatch(.*)*',

    redirect: '/'
}

找不到与以下网址对应的网页：**http://10.0.0.88:1180/abc/.1+1**，3.0版本就没有这个问题

### What is expected?
希望 http://10.0.0.88:1180/abc/.1+1 能重定向到 http://10.0.0.88:1180/abc/

### What is actually happening?
/.1+1 无法重定向 /

**Comment by 0773** [comment]
history 模式下能复现bug，hash模式正常

**Comment by posva** [comment]
That's not a valid reproduction.
