### ISSUE TITLE
router.beforeEach中重定向时，一直警告：Missing required param "pathMatch"

### ISSUE THREAD

**Issue by AK47-dadada** [vuejs/vue-router-next#1224]
### Version
4.0.12

### Reproduction link
[github.com](https://github.com/vuejs/vue-router-next)

### Steps to reproduce
1. 动态加载路由
2. addRoute方法添加路由
3. 在addRoute完成之后重定向

### What is expected?
正常运行

### What is actually happening?
报错
vue-router.esm-bundler.js?6c02:72 [Vue Router warn]: Unexpected error when starting the router: Error: Missing required param "pathMatch"
    at Object.stringify (vue-router.esm-bundler.js?6c02:1006)
    at Object.resolve (vue-router.esm-bundler.js?6c02:1424)
    at resolve (vue-router.esm-bundler.js?6c02:2908)
    at eval (vue-router.esm-bundler.js?6c02:3036)
warn @ vue-router.esm-bundler.js?6c02:72
eval @ vue-router.esm-bundler.js?6c02:3378
Promise.catch（异步）
install @ vue-router.esm-bundler.js?6c02:3376
use @ runtime-core.esm-bundler.js?5c40:3110
eval @ main.js?56d7:20
./src/main.js @ app.js:2257
__webpack_require__ @ app.js:854
__webpack_require__ @ app.js:854
checkDeferredModules @ app.js:46
---

      // 检测是否有accessRoutes
      const accessRoutes = store.getters.accessRoutes
      const hasAccessRoutes = accessRoutes && Object.keys(accessRoutes).length > 0

      // 如果没有accessRoutes则动态获取
      if (!hasAccessRoutes) {
        const asyncRoute = await store.dispatch('permission/getRoutes')
        router.addRoute(asyncRoute)
        // 重定向
 
        next({ ...to, replace: true })
        nprogress.done()
      } else {
        next()
        nprogress.done()
      }

**Comment by posva** [comment]
That's not a valid repro.

---

Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by asasugar** [comment]
You need to addRoute before the app is not mounted, you can refer to https://github.com/vuejs/router/issues/643
