### ISSUE TITLE
vue-router4.0不支持android7+chrome54

### ISSUE THREAD

**Issue by worldflyingct** [vuejs/vue-router-next#1226]
### Version
4.0.12

### Reproduction link
[github.com](https://github.com/worldflyingct/vue-router-badprj)

### Steps to reproduce
在android7+chrome54这个环境下测试：
使用vue create testapp创建一个vue3工程，编译可以打开，但是手动添加npm install vue-router@next，然后打包vue工程发现无法打开了，通过weinre调试，发现为空，但是没有打印任何错误的log。
但是在最新的android9以上系统正常，最新的pc版chrome也正常。

### What is expected?
在低版本的android上能正常使用。

### What is actually happening?
目前什么都不显示。

**Comment by posva** [comment]
Duplicate of https://github.com/vuejs/vue-router-next/issues/1136
