### ISSUE TITLE
ref() variables from setup script are undefined in beforeRouteEnter guard (only in production).

### ISSUE THREAD

**Issue by iyashpal** [vuejs/vue-router-next#1228]
### Version
4.0.12

### Steps to reproduce
```javascript
<template>...</template>

<script>
export default {
	beforeRouteEnter: (to, from, next) => {
		axios.get("/api/connections").then(({ data: resources }) => next(vm => {
			vm.connections = resources.data;
		}));
	}
}
</script>

<script setup>
import { reactive, ref } from "vue";
import ConnectionCard from "./Components/ConnectionCard.vue";
import CreateConnectionModal from "./Components/CreateConnectionModal.vue";

const vaults = ref([]);
const connections = ref([]);

const shouldShowCreateConnectionModal = ref(false);



function onConnectionCreateSuccess(connection) {
	connections.value.unshift(connection);
}
</script>
```

### What is expected?
When I run the application in production mode it should set the connections data to `vm.connections` in `next` callback.

### What is actually happening?
In development mode, I am getting data from API and it's reflecting on the page view which is perfectly fine. But when I make a production build of my application it stopped working. And after spending some hours I find out the `vm.connections` is coming up as `undefined` in production. While in development mode its working fine.

---
If I use option API it's working fine (in development mode and also in production mode). But I don't like option API much. Please provide a solution here.

**Comment by posva** [comment]
You need to use defineExpose()
