### ISSUE TITLE
resetRouter

### ISSUE THREAD

**Issue by guaijie** [vuejs/vue-router-next#1237]
### What problem does this feature solve?
Each user has different menu permissions. When switching users, you may need to remove the routes added later and restore the routes to the initial state. In this way, you can easily add routes for new users

### What does the proposed API look like?
```js
const routes = [ // ...]
const router = createRouter({
  routes,
  history: createWebHashHistory(),
});
router.addRoutes('newRoute')
router.hasRoute('newRoute') // true
router.resetRouter() 
router.hasRoute('newRoute') // false
router.getRoutes() // routes
```

**Comment by posva** [comment]
This is something that must be built by the user because, in most scenarios, users don't need it. Note that `addRoute()` returns a method to remove that route (https://next.router.vuejs.org/guide/advanced/dynamic-routing.html#removing-routes)
