### ISSUE TITLE
can't support ios11?

### ISSUE THREAD

**Issue by cunzaizhuyi** [vuejs/vue-router-next#1244]
### Version
4.0.12

### Reproduction link
[http://www.baidu.com/aa](http://www.baidu.com/aa)

### Steps to reproduce
page will be white screen

### What is expected?
page onload right

### What is actually happening?
page will be white screen

**Comment by cunzaizhuyi** [comment]
createRouter can't invoke. otherwise page will white screen

**Comment by posva** [comment]
Vue 3 doesn't support IE. Use Vue 2 with Vue Router 3 for legacy apps that require IE support (it works for IE9+)
