### ISSUE TITLE
Identifier 'pluginnamearr' has already been declared

### ISSUE THREAD

**Issue by Victor-dreamer** [vuejs/vue-router-next#1250]
### Version
4.0.12

### Reproduction link
[github.com](https://github.com/Victor-dreamer/vue3-demo)

### Steps to reproduce
1、create a vue3 project(with vue-router) using vue-cli
2、run it and switch page routing

### What is expected?
no error message

### What is actually happening?
it will console this when the route change:
Uncaught SyntaxError: Identifier 'pluginnamearr' has already been declared

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by leeQD-210** [comment]
Is this error already handled bro? I also meeted this error

**Comment by leeQD-210** [comment]
check your vue devTools bro,i already handled it
