### ISSUE TITLE
onBeforeRouteUpdate not working by composition API

### ISSUE THREAD

**Issue by exworth** [vuejs/vue-router-next#1251]
### Version
4.0.12

### Reproduction link
[stackblitz.com](https://stackblitz.com/edit/vitejs-vite-xybaha?devtoolsheight=33&file=src/App.vue)

### Steps to reproduce
step1: open reproduction link in Chrome
step2: execute `yarn && yarn dev ` if auto start
step3: click 「About」

### What is expected?
console.log(to, from)

### What is actually happening?
nothings happen.

**Comment by posva** [comment]
`onBeforeRouteUpdate()` triggers on the same route (e.g. changing query, params, or hash). BTW you can and should remove the `alias: ''` on your fallback route.

---

Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!

**Comment by orinoco** [comment]
Update for 2023, you can use the force api to do this: https://github.com/vuejs/vue-router/issues/974
