### ISSUE TITLE
group routes by self need create normalize route record, but `vue-router-next` not expose

### ISSUE THREAD

**Issue by FoxDaxian** [vuejs/vue-router-next#1253]
### What problem does this feature solve?
we can create normalize route record on demand and maintain them, this is convenient if `normalizeRouteRecord` exposed

### What does the proposed API look like?
expose `normalizeRouteRecord`

**Comment by FoxDaxian** [comment]
I can create PR if this is reasonable~

**Comment by posva** [comment]
I think this fits better in a library because it disconnect from how routes are really handled
