### ISSUE TITLE
Empty nested route does not work with named parent

### ISSUE THREAD

**Issue by iamandrewluca** [vuejs/vue-router-next#1254]
### Version
4.0.12

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/dawn-brook-ucsfs?file=/src/main.ts)

https://youtu.be/xFELsyUpNv8 (video is processing)

Sandbox is created from this repo: https://github.com/iamandrewluca/issue-vue-router/blob/main/src/main.ts

### Steps to reproduce
- Click `/projects/the-id` link, `Project` is not rendered
- Refresh coesandbox preview frame, `Project` is rendered

### What is expected?
When navigating to `/projects/the-id`,  `Project` component registered as `''` (empty path) is rendered as nested index path

### What is actually happening?
When navigating to `/projects/the-id`,  `Project` component registered as `''` (empty path) is not rendered as nested index path. But is rendered if the page is refreshed

---
This is seems to happend when parent route has `name`, if I move parent `name` to child (with empty path), then it works.

I simplified the example as much as possible, in my case I have some levels of nested routes.

In example below `{ path: '', component: ProjectOverview },` is not rendered

```ts
export const routes: RouteRecordRaw[] = [
  {
    path: '/',
    component: App,
    children: [
      { path: '/:pathMatch(.*)*', component: NotFound },
      { path: '', component: Dashboard },
      {
        path: 'projects',
        component: RouterView,
        children: [
          { name: 'project-list', path: '', component: ProjectList },
          {
            name: 'project-details',
            path: ':id',
            component: ProjectDetails,
            children: [
              { path: '', component: ProjectOverview },
              { name: 'project-tasks', path: 'tasks', component: ProjectTasks },
              {
                name: 'project-technologies',
                path: 'technologies',
                component: ProjectTechnologies,
              },
              { name: 'project-team', path: 'team', component: ProjectTeam },
              { name: 'project-edit', path: 'edit', component: ProjectEdit },
              {
                name: 'project-timeline',
                path: 'timeline',
                component: ProjectTimeline,
              },
            ],
          },
        ],
      },
    ],
  },
  {
    path: '/auth',
    component: Auth,
    children: authRoutes,
  },
]
```

**Comment by posva** [comment]
This is expected behavior and you **do need** to put the name on the child:

```js
{
		path: '/projects/:id',
		component: RouterView,
		children: [{ name: 'project-details', path: '', component: Project }],
}
```

**Comment by iamandrewluca** [comment]
Thanks @posva! 🚀 
That's what I also did. Moved the name to child.
