### ISSUE TITLE
在地址被解析前对地址进行解码 Decodes the address before it is parsed

### ISSUE THREAD

**Issue by Xyuan-abs** [vuejs/vue-router-next#1258]
### What problem does this feature solve?
如：当地址栏输入http://localhost:3000/%23/detail时，路由会被解析为http://localhost:3000/%23/detail#/,
导致路由页面只能跳转到首页
希望能够在解析路由前进行解码

For example, if http://localhost:3000/%23/detail is entered in Internet explorer, the route is resolved to http://localhost:3000/%23/detail#/.
The routing page can only be redirected to the home page
hop  decode the route before parsing it

### What does the proposed API look like?
不需要api，在路由解析前进行解码
No API required, decoded before route parsing

**Comment by posva** [comment]
Internet explorer is not even supported by Vue 3. If you are using Vue Router 3, note you still need to provide properly encoded paths to your routes array
