### ISSUE TITLE
createWebHashHistory can't work as expected

### ISSUE THREAD

**Issue by linyuhong97** [vuejs/vue-router-next#1261]
### Version
4.0.12

### Reproduction link
[new-issue.vuejs.org/](https://new-issue.vuejs.org/?repo=vuejs/vue)

### Steps to reproduce
const router = createRouter({
  history: createWebHashHistory("/tenant/"),
  routes: [],
});

### What is expected?
http://localhost:8888/tenant/#/

### What is actually happening?
http://localhost:8888/tenant#/

---
When there is a product name after the domain name, it cannot be added in # front/.I tried my best, but I couldn't solve the problem.

![image](https://user-images.githubusercontent.com/52289758/148355388-0b8b54db-4ef2-4756-b8da-869a94099721.png)

![image](https://user-images.githubusercontent.com/52289758/148355471-0d057709-bc22-4fc5-b16c-1665673127a7.png)

**Comment by posva** [comment]
Can't reproduce.
