### ISSUE TITLE
history not working in Android webview

### ISSUE THREAD

**Issue by rppig42** [vuejs/vue-router-next#1263]
### Version
4.0.12

### Reproduction link
[github.com](https://github.com/rppig42/vue-router-minimal-reproduction)

### Steps to reproduce
1. run the repo and put it into any Android web-view
2. click the button on the page to switch between page A and B
3. click go back button

![CleanShot 2022-01-07 at 21 09 19@2x](https://user-images.githubusercontent.com/48581046/148548554-67ce865f-f8f8-455d-8f4d-980c6472c72a.png)

### What is expected?
1. page go back from one to another

### What is actually happening?
1. nothing happened

---
1. I have tried replacing vue-router with page.js and it works fine.
2. vue-router@3 works within the same android webview

**Comment by rppig42** [comment]
Here's an abnormal behavior of android webview. 
If you push a same url with the current url in `windows.history`, it's length becomes 1.

![image](https://user-images.githubusercontent.com/48581046/148631040-4ff9adf8-6f9f-42ac-a922-29b1b157ac9c.png)

**Comment by rppig42** [comment]
Cannot figure out why but after I delete this line https://github.com/vuejs/vue-router-next/blob/4c4c347e9453358cde09266c419fcedbef92a50f/src/history/html5.ts#L283, it works.

**Comment by posva** [comment]
> If you push a same url with the current url in windows.history, it's length becomes 1.

That looks like a huge webview bug 😓 

What version of Android are you using? Is this reproducible by using Chrome or the default browser on any device? Specifically any device from [Browserstack](https://www.browserstack.com) so I can give it a look

**Comment by rppig42** [comment]
After a thorough review, the webview's behavior is modified by some other native code. There's nothing wrong with the webview itself.
