### ISSUE TITLE
通过命名路由跳转一个不存在的路由，出现栈溢出，通过path跳转正常，行为不致？

### ISSUE THREAD

**Issue by chenguzhen87** [vuejs/vue-router-next#1265]
### Version
4.0.12

### Reproduction link
[github.com](https://github.com/parajs/vue3-mobile-template.git)

### Steps to reproduce
1、通过命名路由跳转一个不存在的路由,出现栈溢出
 router.push({
               name: "Video",
           })

2、通过path路由跳转一个不存在的路由,正常

 router.push({
               path: "video",
           })

### What is expected?
通过命名路由跳转一个不存在的路由,不出现栈溢出

### What is actually happening?
出现栈溢出
![image](https://user-images.githubusercontent.com/28331609/149327990-9ee8f434-8594-4cbf-a20a-fbed48cb1164.png)

---
点击首页列表第一个视频项，出现栈溢出

**Comment by posva** [comment]
Your reproduction is not minimal, please read and follow https://new-issue.vuejs.org/?repo=vuejs/vue-router-next#why-repro when reporting a bug. Also please open issues in English
