### ISSUE TITLE
Router adds trailing slash to the 'base'

### ISSUE THREAD

**Issue by Kadeluxe** [vuejs/vue-router-next#1266]
### Version
4.0.12

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/frosty-booth-8yvwn)

### Steps to reproduce
1. Configure router to use base `/base`;
2. open your app `https://your.app/base` (reproduction — [https://8yvwn.csb.app/base](https://8yvwn.csb.app/base));
3. observe how URL changes to `https://your.app/base/` (`https://8yvwn.csb.app/base/`);
4. trailing slash was added and now browser history contains 2 items.

### What is expected?
Router doesn't add trailing slash to the `base` if URL doesn't contain one.

### What is actually happening?
Router adds trailing slash and pollutes browser history.

---
Browsers still save history entry despite using `replaceState`.  
Also this behavior means that if you configure router to use `redirect` from `/` to `/redirected` and then open app without trailing slash, you get 3 history entries:
1. `https://your.app/base`
2. `https://your.app/base/`
3. `https://your.app/base/redirected`

**Comment by posva** [comment]
The history length is 1:

![Screenshot 2022-01-14 at 11 44 15](https://user-images.githubusercontent.com/664177/149502948-69aba771-47d3-4b61-9a5a-341a2493064c.png)
![Screenshot 2022-01-14 at 11 44 27](https://user-images.githubusercontent.com/664177/149502971-e911e889-26d9-4f01-b959-0ba428e32ccb.png)

Note that adding the trailing slash is expected, having 2 history entries wouldn't be though but this is not currently the case.

**Comment by Kadeluxe** [comment]
Firefox:
![2022-01-14-14-42-41-006_firefox](https://user-images.githubusercontent.com/63540878/149511572-0f4078b1-8e0f-4d84-9f00-166fd8641e29.png)
![2022-01-14-14-43-50-710_firefox](https://user-images.githubusercontent.com/63540878/149511577-1e4b1ee5-c1fb-4745-a086-933e1490e42d.png)

Edge:
![2022-01-14-14-44-04-744_msedge](https://user-images.githubusercontent.com/63540878/149511588-0300e643-e0d6-4f2d-9a68-bc8435d4a1cc.png)
![2022-01-14-14-44-12-841_msedge](https://user-images.githubusercontent.com/63540878/149511594-a628f7a1-4189-4f41-877c-12376661b2ac.png)

Video:
![2022-01-14-14-54-07-173_msedge](https://user-images.githubusercontent.com/63540878/149511608-582de9e1-a172-4bce-9210-fab67f93c361.gif)

**Comment by Kadeluxe** [comment]
Clear demonstration of the issue:

![2022-01-14-15-19-53-172_SidebarDiagnostics](https://user-images.githubusercontent.com/63540878/149514632-fd02bbbc-8563-419f-9543-8a98834fe514.gif)

**Comment by posva** [comment]
That's expected native browser behavior because you are manually creating a new navigation. It's unrelated and uncontrollable by the router
