### ISSUE TITLE
Sitemap generator

### ISSUE THREAD

**Issue by jbaubree** [vuejs/vue-router-next#1268]
### What problem does this feature solve?
Hi, is there any way to generate sitemap from vue-router@4?

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
