### ISSUE TITLE
Redirect route name match error

### ISSUE THREAD

**Issue by veaba** [vuejs/vue-router-next#128]
## Version
vue@next
vue-router-next@4.0.0-alpha.1 latest source code

Reproduction link
https://github.com/veaba/vue-router-next/tree/dev-veaba/examples/redirect

## Steps to reproduce
- Use vue-router example redircet demo test vue-router-next 

### vue-router@3.1.6 screenshot: 

![vue2](https://user-images.githubusercontent.com/8652596/75989517-5f496000-5f2e-11ea-9d60-c46d18822399.png)

### vue-router@4.0.0-alpha.1 latest source code screenshot:
![vue3](https://user-images.githubusercontent.com/8652596/75989563-75572080-5f2e-11ea-977c-e3cce868a54e.png)

## What is expected?
It should be the same as the redirection example in vue2

## What is actually happening?
Only part of it can match to the route correctly

**Comment by veaba** [comment]
will continue to test other examples, and the supported cases are as shown in the screenshot
![process](https://user-images.githubusercontent.com/8652596/75990474-e8ad6200-5f2f-11ea-8b8d-5a053954500a.png)

**Comment by posva** [comment]
Thanks for checking this. Most of the tests can be added as unit tests now by instantiating the router and triggering a navigation (router.spec.ts). It should be easier than an e2e
Note that some tests might be intentionally breaking as well but it's great to report those as well so we can list them in the readme 🙂

**Comment by veaba** [comment]
For such high-level operations, I may need to spend some time learning how to use it. 

I complete all the examples first, and I may need them later.

:joy:

**Comment by posva** [comment]
No worries, this is still very helpful! I think writing most of the unit tests should be easier than the e2e. e2e tests only need to exist for features that are browser specific or for browser-specific bugs

**Comment by veaba** [comment]
@posva  Like this?
![image](https://user-images.githubusercontent.com/8652596/76163914-6027ff00-6185-11ea-92f9-1d4d855fa3d5.png)

basic.spec.ts

```typescript
// todo
// e2e see https://github.com/veaba/vue-router-next/tree/dev-veaba/examples/basic

// import fakePromise from 'faked-promise'
// createWebHistory
import { createRouter, createMemoryHistory } from '../../src'
// import { NavigationCancelled } from '../../src/errors'
// components, tick
import { createDom } from '../utils'
import {
  RouteRecord,
  // RouteLocation,
  START_LOCATION_NORMALIZED,
} from '../../src/types'
// import { RouterHistory } from '../../src/history/common'

const routes: RouteRecord[] = []


describe('Router', () => {
  beforeAll(() => {
    createDom()
  })

  it('can be instantiated basic ', function() {
    const history = createMemoryHistory()
    const router = createRouter({ history, routes })
    expect(router.currentRoute.value).toEqual(START_LOCATION_NORMALIZED)
  })
})

```

:joy:

**Comment by posva** [comment]
Not exactly 😆 

They need to be added to existing tests, avoiding duplicates

**Comment by veaba** [comment]
I want to list the test conditions in __test __ / README.md, I will know which one failed the test, and then add test samples to it

I'm not quite sure now which features need to be tested, or whether __test__ covers all features, so I need examples for reference.

I'm not sure, this is right

`__test__/READM.md` :
``` markdown
## guards
## history
## matcher
## main
- [x] encoding.spec
  - [x] Encoding
    - [x] params
      - [x] does not encode safe chars
      - [x] encodes a specific charset
      - [x] encodes non-ascii
      - [x] encodes non-printable ascii
      - [x] does not encode a safe set
    - [x] query params
        - [x] does not encode a safe set
        - [x] does not encode safe chars
        - [x] encodes non-ascii
        - [x] encodes non-printable ascii
        - [x] encodes a specific charset
    - [x] hash
        - [x] does not encode a safe set
        - [x] does not encode safe chars
        - [x] encodes non-ascii
        - [x] encodes non-printable ascii
        - [x] encodes a specific charset
- error.spec
- extractComponentsGuards.spec
- mount.spec
- parseQuery.spec
- router.spec
- RouterLink.spec
- RouterView.spec
- stringifyQuery.spec
- url.spec
- url-encoding.spec
- utils

````

**Comment by veaba** [comment]
@posva Hi. 

Look at this  [commit ](https://github.com/vuejs/vue-router-next/compare/master...veaba:test) .

I worry about breaking it

😂

**Comment by posva** [comment]
I see. Since `redirect` is now transformed into a `beforeEnter` guard, those tests seem to be already covered by guards tests. If not they should be covered there. BTW a redirect must be to an absolute location, `redirect: 'foo'` is not valid, it should warn in dev mode

**Comment by veaba** [comment]
In [vue-router](https://github.com/vuejs/vue-router/blob/dev/examples/redirect/app.js#L19-L29) , is  legal:
```txt
{ path: '/absolute-redirect', redirect: '/bar' },
{ path: '/absolute-redirect-a', redirect:'bar' },
```
`to="/redirect/absolute-redirect"`  -> `/redirect/bar`
`to="/redirect/absolute-redirect-a"`  -> `/redirect/bar`

**Comment by posva** [comment]
I forgot to say relative paths now work. I added a note to the readme about one case that no longer works to make trailing slashes consistent (for SEO).

I don't know what to do with this issue anymore. Are there any tests you want to add to the codebase?

**Comment by veaba** [comment]
> I forgot to say relative paths now work. I added a note to the readme about one case that no longer works to make trailing slashes consistent (for SEO).
> 
> I don't know what to do with this issue anymore. Are there any tests you want to add to the codebase?

Sorry，I forgot that also。:joy:

I need to make a new comparison.

I think you did your job very well.

**Comment by posva** [comment]
Thank you! And thanks for the help. Let's close this one and I will let you create a new issue or pull request if you add new tests!
