### ISSUE TITLE
what version should be used by jsdelivr 

### ISSUE THREAD

**Issue by mika76** [vuejs/vue-router-next#146]
Is there a way to try this directly in html?

I've tried by adding `  <script src="//cdn.jsdelivr.net/npm/@posva/vue-router-next@4.0.0-alpha.0"></script>` but I get the error: "Uncaught SyntaxError: Cannot use import statement outside a module" if I add `type="module"` to the script tag, then I get a different error: "Uncaught TypeError: Failed to resolve module specifier "vue". Relative references must start with either "/", "./", or "../"."

I'm guessing this isn't bundled to be used directly in html?

**Comment by posva** [comment]
To use it in HTML without `type="module"`, you need to use the _global_ build (like with Vue) and I'm realising both, vue and vue-router are not correctly connected to the CDN. For vue-router you need to use the `vue-router.global.js` (same as vue)

```
https://cdn.jsdelivr.net/npm/vue-router@4.0.0-alpha.4/dist/vue-router.global.js
```

(adapt the version)

What I'm unsure is what should be the version pointed by jsdelivr by default, we can change it with `jsdelivr` in the `package.json` file and should be consistent. Previously, in `vue`, we would expose the minified version, that would be `global.prod` instead `global`. Let's keep this open for discussion

**Comment by mika76** [comment]
Hey this is great - thanks - will play around with it now 😄
