### ISSUE TITLE
tag attribute on <router-link> does not seem to be working / a is always used 

### ISSUE THREAD

**Issue by mika76** [vuejs/vue-router-next#148]
Using router alpha.4 and vue alpha.10

```vue
<router-link to="/" tag="li">dashboard</router-link>
```
gives me (notice the tag attribute in the final html)
```html
<a aria-current="page" href="/#/" tag="li" class="router-link-active router-link-exact-active">dashboard</a>
```

v-slot not helping either (taken directly from vue router 3 api docs)...

```vue
<router-link
  to="/"
  v-slot="{ href, route, navigate, isActive, isExactActive }"
>
  <li
    :class="[isActive && 'router-link-active', isExactActive && 'router-link-exact-active']"
  >
    <a :href="href" @click="navigate">{{ route.fullPath }}</a>
  </li>
</router-link>
```
I get the following
```html
<a aria-current="page" href="/#/" class="router-link-active router-link-exact-active">
   <li class="router-link-active router-link-exact-active">
      <a href="/#/">/</a>
   </li>
</a>
```

**Comment by posva** [comment]
The tag prop isn’t implemented yet as it’s almost always a bad practice because it ends up creating a link on an element that’s isn’t a link, loosing most native features like opening in new tabs and out of the box accessibility so I think this should go through an RFC to gather feedback

The v-slot need a way to detect if a scoped slot is being passed or if it’s a regular one, so it wasn’t done yet but will work

**Comment by posva** [comment]
Opened https://github.com/vuejs/rfcs/pull/152 to cover this

**Comment by moniuch** [comment]
@mika76 With regards to `v-slot` usage on `router-link` - I think one should also place the `custom` attribute on the router-link elements. Not sure what it does (docs skip it somehow), but it helps to achieve the expected markup (esp when working with opinionated css frameworks)

**Comment by posva** [comment]
@moniuch you are looking at the v3 docs, which **do have the `custom` attribute**. `custom` has no effect there, it is only added to ease people migration to v4.

The (always up-to-date) link of docs are in this repository homepage
