### ISSUE TITLE
file path is lost when opening a html file directly in browser

### ISSUE THREAD

**Issue by mika76** [vuejs/vue-router-next#163]
I have the following router...

```js
const routerHistory = createWebHashHistory();

const router = createRouter({
  history: routerHistory,
  routes: [
    { path: "/", component: viewDashboard },
    { path: "/home", redirect: "/" },
    { path: "/params", component: viewParameters },
    // ....
  ],
  scrollBehavior(to, from, savedPosition) {
    return { x: 0, y: 0 };
  },
});
```

It works well if served from a http-serve or web server or whatever - but if the dist file is opened as a `file:///...path...to../index.html` directly in the browser, the route automatically changes to `file:///#/` losing the whole file path and name.

**Comment by posva** [comment]
This is indeed a problem. The current usage of hash history assumes a web server and uses the History API with a base of `/#` but that won't work on `file:///`. I will have to investigate that more but for the moment using a Web History with a base of `#` makes it work:

```js
const routerHistory = createWebHistory('#')
```

**Comment by mika76** [comment]
Thanks for the workaround - it works for the moment. It has the hilarious side effect of appending /# on each refresh 🤣

**Comment by mika76** [comment]
Hey @posva think you could create an npm alpha release so I can play with this fix please?
