### ISSUE TITLE
export 'markNonReactive' was not found in 'vue'

### ISSUE THREAD

**Issue by CaiPeng1989** [vuejs/vue-router-next#179]
### Version
4.0.0-alpha.5

### Reproduction link
[https://github.com/vuejs/vue-next/blob/master/CHANGELOG.md](https://github.com/vuejs/vue-next/blob/master/CHANGELOG.md)

### Steps to reproduce
Upgrade `vue-next` to `3.0.0-beta.1`

### What is expected?
Run correctly.

### What is actually happening?
Throw an error.

---
`vue-next@3.0.0-beta.1` changelog: `markNonReactive` has been renamed to `markRaw`.

**Comment by Ttou** [comment]
same issue

**Comment by xdslll** [comment]
same issue

**Comment by posva** [comment]
This was renamed in the latest release of Vue. You can tell use vue@3.0.0.alpha-13

**Comment by huangjiahan66** [comment]
okok
