### ISSUE TITLE
redirect route '/' to '/home'，click browser 'goback' button,something is wrong

### ISSUE THREAD

**Issue by zouhangwithsweet** [vuejs/vue-router-next#180]
`vue@3.beta-2`
`vue-router@^4.0.0-alpha.7`

here is my routes
```ts
export const router = createRouter({
  history: routerHistory,
  routes: [
    {
      path: '/',
      redirect: '/home',
    },
    {
      path: '/home',
      component: Home,
    },
    {
      path: '/detail',
      component: DetailPage,
    },
  ],
})

```
i can enter my app on `localhost:8080`, it can redirect to `localhost:8080/home`; it works.
But,when i  use `router.push({ path: '/detail'})` in component `Home`, it goes to `localhost:8080/detail`, then, click the click browser 'goback' button, it goes to `localhost:8080`, it never go to `localhost:8080/home`

**Comment by zouhangwithsweet** [comment]
In vue-router@3.x, we can use`path: '*'` for 404.html, how can i do the same thing in vue-router@4.x?

**Comment by posva** [comment]
Can you provide a reproduction? I couldn't reproduce it: https://jsfiddle.net/posva/3yq6ojLv/5/

**Comment by posva** [comment]
The star path requires a parameter now: https://github.com/vuejs/vue-router-next#breaking-changes-compared-to-vue-router3x

**Comment by zouhangwithsweet** [comment]
You can check this demo https://codesandbox.io/s/vue-router-v4-reproduction-qrgzx
```js
routes: [
    { path: '/', redirect: '/home'},
    { path: '/home', component: Home },
    { path: '/foo', component: Foo },
    { path: '/bar', component: Bar },
]
```
when i enter this app, the url will redirect to `/home`,then click `Foo` go to '/foo', then just click the browser's `<`(goback button),the url just go to `/`,willnot go to the `/home`

**Comment by zouhangwithsweet** [comment]
here is a video https://drive.google.com/file/d/14hWJkUipZokqCWOv0VdzEQlasrRzpfbX/preview

**Comment by cumt-robin** [comment]
> In [vue-router@3.x](mailto:vue-router@3.x), we can use`path: '*'` for 404.html, how can i do the same thing in [vue-router@4.x](mailto:vue-router@4.x)?

I have the same doubt...
