### ISSUE TITLE
vue-router-next not support router.back ?

### ISSUE THREAD

**Issue by lhz960904** [vuejs/vue-router-next#187]
### What problem does this feature solve?
I'm upgrading the project vue3，before that, I can use `$router.back()` , but now  it will error ` router.go is not a function`
```
 const router = useRouter();
 const back = () => {
      router.back();
   };
return { back };
```

### What does the proposed API look like?
useRouter?

**Comment by posva** [comment]
They have not been added yet because in previous versions, `back`, `go` and `forward` all were just calling their respective functions in `window.history`. If you were calling `$router.back()`, you can call `history.back()` instead
