### ISSUE TITLE
"Failed to resolve component: router-view" - compatibility with Vite

### ISSUE THREAD

**Issue by akauppi** [vuejs/vue-router-next#203]
Trying out Vite (a week old tool for building buildless Vue components) took me to Vue 3 beta and vue-router-next.

I am currently facing this:

`Failed to resolve component: router-view`

Not sure whether it's due to Vue 3 beta or something Vite specific. Decided to open this issue in order to gather discussions, if others are facing something similar.

<img width="619" alt="resolve fails" src="https://user-images.githubusercontent.com/1297734/80519302-7043aa00-8990-11ea-9f86-263438dfd698.png">

 My code base is at: https://github.com/akauppi/GroundLevel-es6-firebase-web/tree/vite-maybe

Use the `vite-maybe` branch.

**Comment by akauppi** [comment]
note: this is likely my own making.

**Comment by NickMcBurney** [comment]
@akauppi did you manage to resolve the issue?

**Comment by ggayowsky** [comment]
This problem seem to be related to not calling use on the application instance with the Router.

Need to change my main.js file to be

```
const app = createApp(App);
app.use(router);
app.mount('#app');
```

**Comment by posva** [comment]
I have an example with Vite and tailwind at https://github.com/posva/vite-tailwind-starter. It might help people trying to scaffold projects

**Comment by thedb** [comment]
'app.use(router)'
must before then
'app.mount('#app')'

**Comment by johnshu666** [comment]
I use this follwing code in my parent.js file, but still the same error
createApp({
    render: () => h(App)
}).use(store, router).mount('#app')

**Comment by prakashkumarbhanja** [comment]
yes, to solve this issue u should maintain this line of cod structure in main.js file.
const app = createApp(App);
app.use(router);
app.mount('#app');

**Comment by jaiko86** [comment]
I want to add to this. Make sure you're do `app.use(router)` before `app.mount('#app')`

**Comment by phpjscoding** [comment]
maybe you just forgot to include this code in router/index.js  : 
const router = createRouter({
    history: createWebHistory(),
    routes,
})

**Comment by cdll** [comment]
same issue here with vite-plugin-ssr

**Comment by hyang-gi** [comment]
`const app = createApp(App);
app.use(router);
app.mount('#app');`

On making this change, I'm seeing an error: `Uncaught TypeError: Cannot destructure property 'options' of '(0 , vue__WEBPACK_IMPORTED_MODULE_1__.inject)(...)' as it is undefined.`

**Comment by linzhilin125** [comment]
> `app.use(router)` 必须在那之前 `app.mount('#app')`
Thank you so much

**Comment by chuSS** [comment]
i just wrote in one line
`createApp(App).use(router).mount('#app')`
instead
```
createApp(App)
  .use(router)
  .mount('#app')
```

**Comment by hakan07ant** [comment]
maybe use in router.js  export default { router }; to => ( export default router; )

**Comment by Aleksandr-JS-Developer** [comment]
> maybe you just forgot to include this code in router/index.js : const router = createRouter({ history: createWebHistory(), routes, })

Thanks! Its solved my problem!

```
vue ^3.2.45
vue-router: ^4.1.6
vite: ^4.0.0
```

Why they don`t creating error in console - is a question.
