### ISSUE TITLE
isActive not working as expected with v-slot API

### ISSUE THREAD

**Issue by jakedohm** [vuejs/vue-router-next#207]
### Reproduction
https://github.com/jakedohm/router-link-slot-bug-reproduction

### Expectation
When I use the v-slot API on a router-link, I'm able to use the isActive property to set classes on the link, like so:
```
<router-link
  v-slot="{ isActive }"
  :class="[isActive ? 'bg-red' : 'bg-blue']"
  active-class="underline"
  to="/"
  >Home</router-link
>
```

### What's really happening
The isActive property doesn't appear to be set on initial render, causing the `bg-blue` class to always be set, even if that link is active. Vue throws this warning:
<img width="680" alt="Screenshot 2020-05-01 09 06 10" src="https://user-images.githubusercontent.com/20726308/80807391-12c77d00-8b8b-11ea-852f-65de79215229.png">

**Comment by posva** [comment]
@jakedohm when you use `v-slot`, the data is available on the children of the component, you need to create the `a` tag and add the different attributes yourself
