### ISSUE TITLE
vue beta.7 may be causing problems with vue-router and vuex

### ISSUE THREAD

**Issue by ais-one** [vuejs/vue-router-next#211]
### Version
4.0.0-alpha.9

### Reproduction link
[https://github.com/ais-one/vite-eg/tree/master/test](https://github.com/ais-one/vite-eg/tree/master/test)

### Steps to reproduce
npm i
npm run dev
navigate to 127.0.0.1:3000

error will appear on console.log

### What is expected?
should work without error

### What is actually happening?
router view throws an error

---
It is ok in vue 3 beta 4

Please also see the following link for more info

https://github.com/vuejs/vite/issues/44

**Comment by posva** [comment]
Closing in favor of https://github.com/vuejs/vue-router-next/issues/209
