### ISSUE TITLE
Error from RouterView: matched undefined

### ISSUE THREAD

**Issue by chenxeed** [vuejs/vue-router-next#212]
### Version
3.0.0-beta.7

### Reproduction link
[https://github.com/chenxeed/vue3-boilerplate](https://github.com/chenxeed/vue3-boilerplate)

![Screenshot from 2020-05-04 13-59-44](https://user-images.githubusercontent.com/3530355/80939528-8bd70680-8e0f-11ea-8f39-093c02ae5392.png)

### Steps to reproduce
1. Install the package with `yarn install`
2. Run the app locally with `yarn serve`
3. BOOM, app not running

### What is expected?
The app should run as usual and the page rendered

### What is actually happening?
Page not rendered, and there's an error from the console.

`TypeError: Cannot read property '0' of undefined`

---
It was fine when I was using Vue beta-3. Perhaps something breaks between beta 4-7.

**Comment by posva** [comment]
https://github.com/vuejs/vue-router-next/issues/209

Note: please boil down reproductions when reporting a bug (no typescript, no jest, etc)
