### ISSUE TITLE
How about export the `routerKey`？

### ISSUE THREAD

**Issue by zouhangwithsweet** [vuejs/vue-router-next#222]
![image](https://user-images.githubusercontent.com/21095710/81169891-38f67e00-8fcc-11ea-9385-14d07004c406.png)

**Comment by posva** [comment]
Use useRoute

**Comment by zouhangwithsweet** [comment]
Obviously, I want to build some components that they are not children of the app. 
Like this:
![image](https://user-images.githubusercontent.com/21095710/81282540-e1b8e200-908d-11ea-8531-792dc44f99b4.png)
Unfortunately, I cannot get the `app._context.provides[Symbol(r)]`

**Comment by zouhangwithsweet** [comment]
I thought of some ways, like bind the component `this` to the app’s child.
