### ISSUE TITLE
Cannot get location when add @click at <router-link>

### ISSUE THREAD

**Issue by zzh97228** [vuejs/vue-router-next#223]
### Version
4.0.0-alpha.10

### Reproduction link
[https://codesandbox.io/s/blissful-agnesi-jv5l3?file=/src/App.vue](https://codesandbox.io/s/blissful-agnesi-jv5l3?file=/src/App.vue)

### Steps to reproduce
Click 'About' link in browser.

The page shows 'Cannot GET /about' error.

### What is expected?
Get the page

### What is actually happening?
Cannot get location when add @click at <router-link>, but when I remove '@click' it works.

**Comment by posva** [comment]
What are you trying to do? Previously any click listener would be ignored.
 Are you aware of the `v-slot` api that allows you to attach a click listener on your own

**Comment by zzh97228** [comment]
OK I will try `v-slot` api
