### ISSUE TITLE
Consider exporting the full type of the RouterLink and RouterView component for TypeScript

### ISSUE THREAD

**Issue by mehcode** [vuejs/vue-router-next#226]
### What problem does this feature solve?
As it stands now, attempting to use `RouterLink` or `RouterView` in TSX fails with:

```
TS2604: JSX element type 'RouterLink' does not have any construct or call signatures.
```

This is because the type is erased here:

https://github.com/vuejs/vue-router-next/blob/096d86498e954345c6bd4d8e82fe54c37d3f869b/src/RouterLink.ts#L140

Is there something blocking the full type being exported? 

### What does the proposed API look like?
Removing the `as unknown as Component`.

**Comment by posva** [comment]
> Is there something blocking the full type being exported?

Not anymore!

**Comment by livevsonline** [comment]
@posva Do not seem to be fixed for me?

I just installed Vue 3 and am testing out type hinting with `vue-tsc` package, and I am now getting this error? Its a totally fresh project with Vue 3.2

**Comment by ad-on-is** [comment]
> @posva Do not seem to be fixed for me?
> 
> I just installed Vue 3 and am testing out type hinting with `vue-tsc` package, and I am now getting this error? Its a totally fresh project with Vue 3.2

Same here, did you find any solution?

**Comment by jakobluthman** [comment]
> > @posva Do not seem to be fixed for me?
> > I just installed Vue 3 and am testing out type hinting with `vue-tsc` package, and I am now getting this error? Its a totally fresh project with Vue 3.2
> 
> Same here, did you find any solution?

You can import RouterView and RouterLink from vue-router and define them as components in your component, which will give you correct typings and resolve the errors you are getting.

//
import { RouterView, RouterLink } from 'vue-router'

//
components: {
  RouterView,
  RouterLink
}

Do note that this is not a permanent fix, just a workaround.

**Comment by livevsonline** [comment]
> 

That works, i now just have an error with the whole App import in App.vue:

Module '"C:/Users/Christian/PhpstormProjects/vue-sales-running-attempt-3/src/App.vue"' has no default export.
