### ISSUE TITLE
vue-router : RouteConfig declaration and export not found in current module release ?

### ISSUE THREAD

**Issue by cbdiesse** [vuejs/vue-router-next#230]
Module '"../../../../../../work_sts/kclient/ascli-5/node_modules/vue-router/dist/vue-router"' has no exported member 'RouteConfig'.
`  > 1 | import { RouteConfig, createRouter, createWebHistory } from 'vue-router';`

**Comment by josh-hemphill** [comment]
@cbdiesse I opened a new issue through the issue helper #264
