### ISSUE TITLE
项目打包后 无法正常运行 提示 Cannot read property 'currentRoute' of undefined

### ISSUE THREAD

**Issue by ayuxinyi** [vuejs/vue-router-next#232]
### Version
3.0.0-beta.10

### Reproduction link
[https://github.com/ayuxinyi/testDemo.git](https://github.com/ayuxinyi/testDemo.git)

### Steps to reproduce
打包项目 直接运行

### What is expected?
能够正常打包运行

### What is actually happening?
通过getCurrentInstance（）方法获取到的ctx，在打包后无法获取到当前路由分段，在本地运行时能够正常运行

Works in development but errors after building for production

**Comment by posva** [comment]
Use `useRoute` inside of `setup`. Also keep in mind that

```js
ref(ctx.$router.currentRoute.value.meta.keepAlive);
```

won't change when the route change, you need a computed:

```js
let route = useRoute()
computed(() => route.meta.keepAlive)
```

**Comment by ayuxinyi** [comment]
@posva thanks
