### ISSUE TITLE
KeepAlive not working in VueRouter

### ISSUE THREAD

**Issue by andrewspy** [vuejs/vue-router-next#245]
### Version
4.0.0-alpha.11

### Reproduction link
[https://github.com/andrewspy/vite-app-keep-alive](https://github.com/andrewspy/vite-app-keep-alive)

### Steps to reproduce
See `App.vue`

```html
<template>
  <h1>Hello Vite   Vue 3!</h1>
  <p>Edit ./App.vue to test hot module replacement (HMR).</p>
  <p>
    <span>Count is: {{ count }}</span>
    <button @click="count  ">increment</button>
  </p>
  <div>
    <hr />
    <router-link to="/">Home</router-link> |
    <router-link to="/about">About</router-link>
    <hr />
    <!-- XXX: keep-alive not working with vue-router-next -->
    <keep-alive :include="['Home', 'About']">
      <router-view />
    </keep-alive>
  </div>
</template>
```

### What is expected?
`count` in Home view should retain value on change route.

### What is actually happening?
`count` in Home view always reset to 0.

---
I have read the missing features of `KeepAlive` in README, but not sure if it is related, or any workaround for `KeepAlive` for Vue3.

**Comment by andrewspy** [comment]
I shall close it as it's a known missing features at the moment. Thanks!

**Comment by andrisi** [comment]
@andrewspy does it work now? Where is that readme mentioning KeepAlive is a missing feature? Thanks.

**Comment by andrewspy** [comment]
@andrisi See below:
https://next.router.vuejs.org/guide/migration/index.html#router-view-keep-alive-and-transition

**Comment by andrisi** [comment]
@andrewspy thanks for the quick reply. I do use it as describe, but inside a Quasar Framework project, so I might be doing something wrong. Nothing is kept alive for now.

**Comment by andrisi** [comment]
@andrewspy solution at https://stackoverflow.com/questions/66215625/vue-3-keep-alive-cache-routes - says: In Vue 3, put the key on the <component> rather than the <router-view>
