### ISSUE TITLE
path missing from URL

### ISSUE THREAD

**Issue by zhuyankun** [vuejs/vue-router-next#247]
### Version
4.0.0-alpha.11

### Reproduction link
[https://codesandbox.io/s/gallant-matsumoto-smcvl](https://codesandbox.io/s/gallant-matsumoto-smcvl)

### Steps to reproduce

**webpack.config**
```
output: {
    path: path.resolve(__dirname, "./dist"),
    filename: "demo.html",
    publicPath: "/dist/"
  }
```

### What is expected?
https://smcvl.sse.codesandbox.io/demo.html#/about

### What is actually happening?
URL redirected

https://smcvl.sse.codesandbox.io/#/about

**Comment by posva** [comment]
Keep in mind you will have to provide the correct base for it to work (see commit message).
In the future, it will be appreciated if you were clear with the issue by providing actual sentences in Steps to reproduce, what is expected, and what is actually happening. It will make it feel human 🙂
