### ISSUE TITLE
`useRoute` and `useRouter` return undefined if called after an `await`

### ISSUE THREAD

**Issue by jeffreybiles** [vuejs/vue-router-next#257]
```js
async setup(){
  const route = useRoute();
  const id = route.params.id;
  const response = await axios.get(`${postsUrl}/${id}`);
  const router = useRouter()
  console.log(router) // undefined
}
```

**Comment by posva** [comment]
This is expected. The is a warning in the console

**Comment by jeffreybiles** [comment]
From the perspective of someone who is new to vue-router-next, this is surprising behavior.

The warning which I think you're referring to is the following:

```
inject() can only be used inside setup() or functional components.
```

Is that correct?

If so, perhaps it could be reworded to more clearly point to the expected behavior?

```
You are using `useRouter` after an `await`.  This will not work.  Because `useRouter` relies on injection, it must be used before the `await`.
```

**Comment by posva** [comment]
I thought I had a dedicated warning like https://github.com/vuejs/vue-router-next/blob/master/src/navigationGuards.ts#L34-L39 Feel free to do a PR to add the warning as well as changing the other message to something that is more adapted:

```
Couldn't ${errorMessage}.If you are using async setup(), make sure to call "${apiName}" before the first await statement.
```

Where `errorMessage` is `retrieve the router instance`/`retrieve the current route`/`add a navigation guard` and `apiName` is the function name `useRoute`, `onBeforeRouteUpdate`, etc

**Comment by jeffreybiles** [comment]
Great, I'll take a look at adding a warning!

In the meantime, I submitted a PR for the README: https://github.com/vuejs/vue-router-next/pull/258

**Comment by codenomnom** [comment]
Well, uhm, I still stumble upon this error message (the `inject() can only be used inside setup() or functional components.` one). I'm using `createGlobalState` from `@vueuse/core` - seems like anything that would delay the setup function would prompt that error? While I get the reason, I don't get the message :)

**Comment by posva** [comment]
@codenomnom that's an inherent problem of `createGlobalState`: it breaks any subsequent `inject()`

**Comment by bartenra** [comment]
Beacuse of this, the type of `useRouter` is wrong.

It should return `Router | undefined`, not `Router`.

**Comment by rafaelytakei** [comment]
Sorry, I'm kinda new to vue 3 and stumbled on this same issue. How can I rewrite a code where I'd normally `await something` then `router.push('something')`?

**Comment by mitar** [comment]
Vue would really need something like `Meteor.bindEnvironment`.
