### ISSUE TITLE
路由设置：打包base路由不自动获取（打包后二级目录无法正常访问）

### ISSUE THREAD

**Issue by wyx11223344** [vuejs/vue-router-next#259]
### What problem does this feature solve?
当在创建路由的时候直接使用createWbeHashHistory()的时候，将打包的工程进行代理访问后，如果不在/根路径的时候会自动访问到根下，并且会导致其他资源访问失败（如：访问http://localhost:8080/assemble/#/     会自动变成http://localhost:8080/#/）。可以解决打包后访问二级目录工程时候路由问题。

### What does the proposed API look like?
hash模式的时候在vue-router.cjs.js中，第200行的normalizeBase方法中添加如果没有传递默认base或者html中没有默认base标签时，获取localtion.pathname作为base路由
```
 base = (baseEl && baseEl.getAttribute('href')) || localtion.pathname; // 第205行
```
在history模式时将在482行的方法createWebHistory中添加强制校验至少需要传递base参数或者<base>标签
```
    if (!base && !document.querySelector('base')) return createRouterError(**, **);
```

**Comment by posva** [comment]
Please open the issue in English and with a boiled down reproduction, there is a starter reproduction at https://new-issue.vuejs.org/?repo=vuejs/vue-router-next

The little I could understand from translation is that you need to use a base of `/assemble/`: `createWebHashHistory('/assemble/')`
