### ISSUE TITLE
It should be supported in routing for uncertain running path after packaging

### ISSUE THREAD

**Issue by wyx11223344** [vuejs/vue-router-next#261]
### What problem does this feature solve?
If I am a developer and don't know which secondary or even tertiary directory the O & M personnel will deploy to, then I will not be able to set the base path in the createwebhashhistory() method, so I need to communicate the location of the project package with the O & M personnel when I pack, and when I deploy to different environments and paths, the modification of the base path will It will make me confused.

### What does the proposed API look like?
I hope vue-router can help me get the base path automatically

**Comment by pikax** [comment]
If you use `hashHistory` the base location should be:
```
const {origin, pathname}= new URL('https://test.ex/my/sub/directory#myrouter'); // location object

const basePath = origin + pathname; // https://test.ex/my/sub/directory
```

**Comment by wyx11223344** [comment]
Thank you for your reply. I just hope vue-router can handle this situation. I have already set this in my project

**Comment by posva** [comment]
@wyx11223344 next time provide a repro using the starter at https://new-issue.vuejs.org/?repo=vuejs/vue-router-next. I had a very hard time understanding the bug you were reporting

**Comment by wyx11223344** [comment]
Thank you very much.I'll describe it more clearly next time
