### ISSUE TITLE
support list all dynamically added routes

### ISSUE THREAD

**Issue by nour-dev** [vuejs/vue-router-next#263]
### What problem does this feature solve?
in the stable vue-router version there is no official function to get dynamically added routes   initiated routes as the total routes of the application.  is this supported in this version ?

### What does the proposed API look like?
```js
$router.getAllRoutes() // will fetch all initiated routes  and dynamically added routes
```

**Comment by posva** [comment]
`router.getRoutes`

**Comment by nour-dev** [comment]
@posva I will test it out .
