### ISSUE TITLE
No exported member 'RouteConfig' 

### ISSUE THREAD

**Issue by josh-hemphill** [vuejs/vue-router-next#264]
### Version
4.0.0-alpha.12

### Reproduction link
[https://codesandbox.io/s/vue-router-v4-reproduction-x9xb4?file=/main.ts](https://codesandbox.io/s/vue-router-v4-reproduction-x9xb4?file=/main.ts)

### Steps to reproduce
Follow the guidelines for starting a new Vue 3 project, and include vue-router (updating to next)

### What is expected?
The standard new project to build

### What is actually happening?
typescript compiling fails

---
If `RouteConfig` is no longer there, should it be mentioned somewhere? And what would the path be for the vue-cli-plugin-vue-next to be able to scaffold the starter project successfully with typescript?

**Comment by cbdiesse** [comment]
@josh-hemphill ,
Thanks for support ... Also may I have a hint on how to create a reproduction Link ...
Also wondering ... Many new Vue 3 declaration : RouteRecord, RouteRecordRaw have been populated. 
Specs and examples are lacking too much ... Hard to break into Vue 3 now.
Never use Vue 2 and want to break directly in vue 3, but vue 2 examples failed to execute ...
