### ISSUE TITLE
Cannot read property of listen of undefined 

### ISSUE THREAD

**Issue by denistsoi** [vuejs/vue-router-next#266]
### Version
4.0.0-alpha.12

### Reproduction link
[https://codesandbox.io/s/vue-router-v4-reproduction-l5fzm?file=/index.html](https://codesandbox.io/s/vue-router-v4-reproduction-l5fzm?file=/index.html)

### Steps to reproduce
How to Reproduce:
When the developer omits the history property when instantiating createRouter function, the above error is shown.

```
const router = createRouter({
  routes: [{
    path: "/",
    component: { template: "<div>Home</div>"}, 
  }, {
    path: "/path2",
    component: { template: "<div>path</div>"}
  }]
})
```

### What is expected?
Error should indicate that the history method is a required field (and suggest one of...)

However, the docs indicate the for client side applications, the default is only createWebHistory (unless this is SSR).

### What is actually happening?

> Uncaught TypeError: Cannot read property 'listen' of undefined
> at createRouter (vue-router.esm-bundler.js:2269)
> at main.js:16
> createRouter @ vue-router.esm-bundler.js:2269
> (anonymous) @ main.js:16
> 

---
How to resolve:
 
Include history property within createRouter options.

```
const routerHistory = createWebHistory()
const router = createRouter({
  history: routerHistory,
  routes: [{
    path: "/",
    component: { template: "<div>Home</div>"}, 
  }, {
    path: "/cv",
    component: { template: "<div>CV</div>"}
  }]
})
```

Suggestion:

The error log should include an improved message that the history field should be createWebHistory() or others that are supported. (Can not suggest as it is not included in tests)

May wish to include that in the docs.

**Comment by posva** [comment]
It's already in the docs: https://github.com/vuejs/vue-router-next#breaking-changes-compared-to-vue-router3x

**Comment by denistsoi** [comment]
Ok @posva 

I’ll look into adding a PR in the coming days, 

Just wondering (apart what other history methods are currently or will be supported in the next release?)

Updating docs should be a quick edit from my end if you’re cool with that.

**Comment by denistsoi** [comment]
Oh wait you just added a doc update (sorry didn’t notice)
