### ISSUE TITLE
Require "redirect" param when init a RouteRecordRaw

### ISSUE THREAD

**Issue by ndr47** [vuejs/vue-router-next#268]
### Version
4.0.0-alpha.12

### Reproduction link
[https://jsfiddle.net/rdshe206/](https://jsfiddle.net/rdshe206/)

### Steps to reproduce
Nothing. It is an error from es-linter.
```
Property 'redirect' is missing in type '{ path: string; component: typeof import("[PATH]/node_modules/vue/dist/vue"); }' but req...
```
```typescript
import { createRouter, createWebHistory, RouteRecordRaw } from 'vue-router';
import Home from '../views/Home.vue';
const routes:RouteRecordRaw[] = [
        // I GOT THE ERROR HERE
	{
		path: '/',
		name: 'home',
		component: Home
	}
];
const router = createRouter({
	history: createWebHistory(process.env.BASE_URL),
	routes: routes
});
export default router;
```
Why redirect is required?

I checked the type and it is 

```typescript
export type RouteRecordRaw =
  | RouteRecordSingleView
  | RouteRecordMultipleViews
  | RouteRecordRedirectRaw
```

so one of the 3 options. But why it picks the RedirectRaw? it should pick the SingleView right?

My setup
```typescript
"vue": "^3.0.0-beta.14",
"vue-router": "^4.0.0-alpha.12",
"vuex": "^4.0.0-alpha.2" 
```

### What is expected?
To pick the RouteRecordSingleView

### What is actually happening?
It picks RouteRecordRedirectRaw

**Comment by posva** [comment]
I couldn't reproduce in vue-router-next repository nor on a new project with TS. We have typing tests in a folder named `test-dts`. If you manage to reproduce it there, please open a pull request. There might be a difference on the `tsconfig.json` as well. This is the one I used for the new project:

```json
{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "moduleResolution": "node",
    "isolatedModules": true,
    "strict": true,
    "noUnusedLocals": false,
    "allowUnreachableCode": true,
    "noUnusedParameters": true,
    "experimentalDecorators": true,
    "lib": ["dom", "esnext"]
  },
  "exclude": ["node_modules", "dist"]
}
```

**Comment by milosjmutavdzic** [comment]
same issue in my case
