### ISSUE TITLE
beforeRouteEnter support or other way of passing data to component

### ISSUE THREAD

**Issue by ggedde** [vuejs/vue-router-next#276]
I see that the "beforeRouteEnter" is listed as a Missing Feature and I am just curious if this is currently being working on and if the normal usage of "beforeRouteEnter" will still apply or will there be a new method to pass data to the component as it renders?
Thanks

**Comment by posva** [comment]
You can use a custom meta field to automatically fetch data in a `beforeResolve`


```js
// { path: '/users/:id', meta: { fetch: fetchUser }, props: to => ({ user: to.meta.data }) }

router.beforeResolve((to, from ,next) => {
  if (to.meta.fetch) meta.data = await to.meta.fetch(to.params)
  next()
})
```

This works well because in v4 `meta` in `to` is a new object every navigation

**Comment by ggedde** [comment]
@posva Hmm, this sounds great, but I am not seeing how the meta.data is getting passed to the component.

**Comment by posva** [comment]
There was a typo 😉

**Comment by ggedde** [comment]
@posva Thanks I got this working now.  I see that I can also do it on beforeEach(), but beforeResolve() makes sense.  

I really like this method and I think I will use it over the per-component beforeRouteEnter() navigation guard, but I can still see a use case for it so just curious if that will still the plan or if there is something else in mind?
Thanks

**Comment by posva** [comment]
`beforeRouteEnter` will still work in v4
