### ISSUE TITLE
Dynamic Router with Regular params throw [A non-empty path must start with "/"] exception

### ISSUE THREAD

**Issue by haydenzhourepo** [vuejs/vue-router-next#277]
### Version
4.0.0-alpha.12

### Reproduction link
[https://jsfiddle.net/esuat8fx/5/](https://jsfiddle.net/esuat8fx/5/)

### Steps to reproduce
import { createRouter, createWebHistory } from 'vue-router';

const routes = [
  { path: '*', redirect: '/404' }
]

const router = createRouter({
  history: createWebHistory(process.env.BASE_URL),
  routes
})

export default router

### What is expected?
redirect to /404 url

### What is actually happening?
 throw [A non-empty path must start with "/"] exception

**Comment by posva** [comment]
Please check the readme, it talks about this
