### ISSUE TITLE
router-link tag property does not do anything anymore

### ISSUE THREAD

**Issue by Pckool** [vuejs/vue-router-next#278]
Doing something like this does not work like it used to:
```html
<router-link :to="{name: 'news-room'}" tag="button">NEWS</router-link>
```
This seems to not replace the `a` tag with a `button` tag as it did in vue2/vue-router3

Setup:
vue_3.0-beta.14
vue-router_4.0-beta.12
webpack_4.43.0

NOTE: If any additional info is needed, please let me know.

**Comment by posva** [comment]
Check the readme for the merged rfcs. Tag was removed in favor of v slot

**Comment by Pckool** [comment]
Ah Yes you are right, thank you
