### ISSUE TITLE
Component Children of `<router-link/>`s are missing `data-v-<id>` Attribute from Parent's Scoped Styles

### ISSUE THREAD

**Issue by eli-crow** [vuejs/vue-router-next#291]
### Version
4.0.0-alpha.12

### Reproduction link
[https://codesandbox.io/s/children-of-router-links-are-missing-data-v-id-attribute-from-parents-scoped-styles-7lj1y?file=/src/App.vue](https://codesandbox.io/s/children-of-router-links-are-missing-data-v-id-attribute-from-parents-scoped-styles-7lj1y?file=/src/App.vue)

### Steps to reproduce
1. Create a vue (3.0.0-beta-14) project with single-file components and vue-router(4.0.0-alpha-12) set up normally.
2. In `App.vue`, Place a child component inside a `<router-link/>`. Give the child component the class `example`.
3. In `App.vue`, add a scoped style tag and create a ruleset for `.example`
4. The scope styles will not be applied to the child component. Non-component children work as expected.

### What is expected?
The scoped styles from `App.vue` should be applied to the child component.

### What is actually happening?
The scoped styles are not being applied to the child component because the `data-v-<id>` attribute from the parent scope is not being applied to the child component.

---
- Ran into this trying to style a component with an SVG root element.
- Non-component children work as expected.
- Not sure if this belongs in vue-router-next or vue-next.

**Comment by posva** [comment]
@sodatea do you know if this comes from vue-loader or vue? I tried out using a regular slot and the problem is still there: the rendered element by component does not have the `data-v-` attribute: https://github.com/posva/bug-vue-loader-slot

**Comment by eli-crow** [comment]
@posva @sodatea, this appears to have nothing to do with vue-router-next. I can confirm this is happening with any component children inside slots.

Updated CodeSandbox to confirm: https://codesandbox.io/s/component-children-of-slot-children-are-missing-data-v-id-attribute-from-parents-scoped-styles-7lj1y?file=/src/App.vue

Closing in favor of this ticket in vue-loader: [https://github.com/vuejs/vue-loader/issues/1685](https://github.com/vuejs/vue-loader/issues/1685)

**Comment by sodatea** [comment]
Vite does not depend on `vue-loader`, so it may be a bug in `@vue/compiler-sfc`. I'll dig into this tomorrow.

**Comment by mkarras** [comment]
Any new findings? I got a similar problem with a custom link component using `vue-router` `4.1.6` under `vue` `3.2.45` with vite plugin `@vitejs/plugin-vue` `4.0.0`:

_LinkComponent.vue_
```
<template>
   <RouterLink custom ...>
      <a ...><slot /></a>
   </Routerlink>
</template>
```

In parent:
```
<template>
    <LinkComponent class="custom-styling">my link</LinkComponent>
</template>

<style lang="postcss" scoped>
   .custom-styling {
       @apply whatever;
    }
</style>    
```

The styling has no effect because of missing scoping (data-v-...) at the a-element of `LinkComponent.vue`. Worked in vue 2 (`"vue": "~2.6.14"`, `"vue-router": "^3.5.1"`, `"vue-template-compiler": "~2.6.14"`, `"vite-plugin-vue2": "^2.0.2"`) before upgrading to vue 3 and vue-router 4.
