### ISSUE TITLE
Provide a mechanism for handling duplicate navigation

### ISSUE THREAD

**Issue by mrts** [vuejs/vue-router-next#302]
### What problem does this feature solve?
A mechanism is needed for handling duplicate navigation.

This has been requested in https://github.com/vuejs/vue-router/issues/974.

The following comment https://github.com/vuejs/vue-router/issues/974#issuecomment-497832619 has received 57 upvotes:

> Vue Router should respect the "default" behavior of any "normal" link.
> 
> On a simple HTML page, when clicking on the link of the page we already are on, the page reload. And I think Vue Router should not alter this default behavior, because it's what most user using the web is expecting.

### What does the proposed API look like?
Another comment https://github.com/vuejs/vue-router/issues/974#issuecomment-541127408 that has received 33 upvotes, suggests providing a new configuration option `duplicateNavigationPolicy` that provides reload, reject and ignore policies for handling duplicate navigation. The proposed API looks as follows:

```js
const router = new Router({
    duplicateNavigationPolicy: 'reload' // or 'ignore', 'reject', or maybe a callable
})
```

**Comment by posva** [comment]
Please don't open duplicates
