### ISSUE TITLE
spread operator compatibility

### ISSUE THREAD

**Issue by JuniorTour** [vuejs/vue-router-next#304]
### Version
4.0.0-alpha.12

### Reproduction link
[https://cdn.bootcdn.net/ajax/libs/vue-router/4.0.0-alpha.12/vue-router.global.js](https://cdn.bootcdn.net/ajax/libs/vue-router/4.0.0-alpha.12/vue-router.global.js)

### Steps to reproduce
`<link>`  and execute the cdn script in `Edge@44`.

### What is expected?
Everything works fine.

### What is actually happening?
Page blank, and got console error: `SCRIPT1028: SCRIPT1028: Expected identifier, string or number
vue-router.global.js (374,15)`

---
May be we need a polyfiill function for spread operator?

**Comment by danyadev** [comment]
Vue uses Object.assign to fix this problem. Using polyfill will add some extra code, which can simply be avoided.

**Comment by BenoitRanque** [comment]
I have run into this issue again. Should I open a new issue?

I have identified the offending lines of code, use of spread operator [here](https://github.com/vuejs/vue-router-next/blob/master/src/warning.ts#L1) and [here](https://github.com/vuejs/vue-router-next/blob/master/src/router.ts#L246)

There is also a dangling comma [here](https://github.com/vuejs/vue-router-next/blob/master/src/router.ts#L579)

Manually removing those from the dist. file fixes the issue for me. I am able to create a PR if need be

**Comment by posva** [comment]
@BenoitRanque Thanks, I removed the spread at 71c28cf. The warning is a bit different, I'm open to proposals to keep it correct in TS and yield a version that works on older Edge versions
The dangling comma is removed when bundled

**Comment by BenoitRanque** [comment]
> @BenoitRanque Thanks, I removed the spread at [71c28cf](https://github.com/vuejs/vue-router-next/commit/71c28cf4d62101fa67f8e1efe972eeb66ca1a5c2). The warning is a bit different, I'm open to proposals to keep it correct in TS and yield a version that works on older Edge versions
> The dangling comma is removed when bundled

The dangling coma is _not_ removed, which is how I found it. Search for `,]` in the CDN

https://cdn.bootcdn.net/ajax/libs/vue-router/4.0.0-beta.7/vue-router.global.js

**Comment by BenoitRanque** [comment]
About the warn method, it is indeed tricky. For now I've got this, but the unused argument is icky, and I still need to type it. Will update asap

```js
function warn (msg) {
	console.warn.apply(console, ['[Vue Router warn]: '].concat(arguments))
}
```

**Comment by posva** [comment]
The dangling comma is fixed at f7ccde0

**Comment by BenoitRanque** [comment]
Update: with help on the discord, came up with this:

```js
export function warn(msg: string, ...arg: any[]): void
export function warn(msg: string) {
  let args = Array.from(arguments).slice(1)
  console.warn.apply(
    console,
    ['[Vue Router warn]: ' + msg].concat(args) as [string, ...any[]]
  )
}
```

Which, on build, gives this output:

```js
// export function warn(msg: string, ...args: any[]) {
//   console.warn('[Vue Router warn]: ' + msg, ...args)
// }
function warn(msg) {
    let args = Array.from(arguments).slice(1);
    console.warn.apply(console, ['[Vue Router warn]: ' + msg].concat(args));
}
```

This should work, but it will need some comments explaining why

If this looks good to you, I can create a PR

**Comment by posva** [comment]
Nice! I had a similar solution but I like yours more and it works better too.
I added you as a co author at cf1fda3e4f260fca76e3a85c9d3e6ff20bc53a61

**Comment by BenoitRanque** [comment]
Awesome! I've just tested it in my project (which uses webview) and it works as expected.
I'm using a locally built version of the file as a dependency until this goes live on npm.

Thanks a bunch!
