### ISSUE TITLE
Redirect in nested children is not honoured when link to a name location

### ISSUE THREAD

**Issue by AlexandreBonaventure** [vuejs/vue-router-next#309]
https://jsfiddle.net/qp1tu5ds/1/

**What is expected ?**
Same behaviour between name-based location link vs path-based location link

**What's happening ?**
When using name-based location children children redirect route record is not hit.

**Comment by posva** [comment]
This is expected: when using the named location you are able to target a parent without rendering its empty children. It was also that way on vue router v3

**Comment by AlexandreBonaventure** [comment]
@posva ok, well fair enough, I did not recall if vue-router@3.x had the same behaviour. However, I guess I was confused because what I usually did in vue-router@3.x was to use `redirect` on the parent route, but that is not allowed anymore as far as I can see: https://jsfiddle.net/zxcqtrsL/

What would be the recommended way to deal with this use-case ?
To recap: I want to have a parent route (with a Parent component) that has children routes. This parent route should never be matched alone, so I want to redirect to a child route per default.
I don't want to link to the nested routes directly because the default route is likely going to change and I don't want to make "public" this implementation details

I think I could use `beforeEnter` but `redirect` use to be more straightforward.
Thanks

**Comment by posva** [comment]
A `beforeEach` or `beforeEnter` should work:

```js
router.beforeEach((to, from, next) => {
  if (to.name === 'foo') next(to.fullPath)
  else next()
})
```

**Comment by AlexandreBonaventure** [comment]
Hey I don't want to be annoying, this workaround works but is there any reasons to remove support for `redirect` for RouteRecord with components ? As far as I can see, there's no mention of it in the breaking changes section of the readme. I use to use that a lot...

**Comment by posva** [comment]
The idea is a `redirect` record is never rendered. I will take a look, though, there is a chance this could be supported without breaking other things. The reason is doesn't work right now is because children in a redirect record are not valid and are ignored, so your route bar is not added

**Comment by posva** [comment]
@AlexandreBonaventure I forgot to give you an update but `redirect` with `children` is supported despite the wrong TS typings

**Comment by AlexandreBonaventure** [comment]
Sweet! I'll try that, thanks for following up
