### ISSUE TITLE
Vue Router Next erases nested URL Public path and redirects to root /

### ISSUE THREAD

**Issue by nomanHasan** [vuejs/vue-router-next#312]
Hello, I'm facing a bug with Vue3 + Vue Router Next + WebHashHistory. If I deploy the app under a nested public path and build the project accordingly - The app when run - rewrites the url Bar and removes the nested path altogether.

I've tested with a vue-cli project. Same problem there. Following steps are for a vite project -

## Reproduction Steps

1. `yarn create vite-app vuerouternextdemo`

2. Create an app with WebHashHistory
>`main.js`
``` javascript
import { createApp } from 'vue'
import App from './App.vue'
import './index.css'

import Home from './components/home.vue';
import About from './components/about.vue';
import { createRouter, createWebHashHistory } from 'vue-router';


export const AppRouter = createRouter({
  history: createWebHashHistory(),
  routes: [
    {
      path: '/',
      redirect: '/home',
    },
    { path: '/home', name: 'home', component: Home },
    { path: '/about', name: 'about', component: About },
  ]
})

const app = createApp(App)
app.use(AppRouter);
app.mount('#app')
```
>`package.json`
```javascript
{
  "name": "viterouter",
  "version": "0.0.0",
  "scripts": {
    "dev": "vite",
    "build": "vite build --base=./"
  },
  "dependencies": {
    "vue": "^3.0.0-beta.14",
    "vue-router": "^4.0.0-alpha.12"
  },
  "devDependencies": {
    "vite": "^0.20.0",
    "@vue/compiler-sfc": "^3.0.0-beta.14"
  }
}
```

3. Build the app with arguments `yarn run vite build --base=./`

4. Run a live-server in the project directory (outside of the dist folder) `live-server .`
5. Go to the nested public path dist `http://127.0.0.1:8080/dist/`

6. Now, public path is erased and the URL is redirected to this **`http://127.0.0.1:8080/#/home`**. The correct url should be **`http://127.0.0.1:8080/dist/#/home`**

**Comment by posva** [comment]
You need to provide the `/dist` base to `createWebHashHistory('/dist')`

**Comment by nomanHasan** [comment]
@posva  Didn't have any idea about that it took publicPath as argument. Thank you very much for your help. 
Now after your answer I tried to apply `./` (passing to both vite and createWebHasHistory) as a relative public path. It used to work with Vue 2. It doesn't seem to work. Please let me know if you have any idea.

**Comment by posva** [comment]
You cannot pass a relative path with `./`, make sure to remove the `.`. Note other changes can be found at https://github.com/vuejs/vue-router-next#known-issues

**Comment by nomanHasan** [comment]
@posva  Thank you very much. In vue 2 relative path could be passed as `publicPath: './',`. No router configuration was needed. 

After deployment the app could be deployed to many subdirectory or many public paths. My requirement is just that - The same app will be deployed to multiple public base path. 

So, in above example - a copy pasted `dist`, `dist2`, `dist3` directory would still be able to serve the app with the proper URL - e.g. `**http://127.0.0.1:8080/dist3/#/home**`. All with a single build.

So passing fixed base path as vite build and routerHistory as Argument is not optimal. A single build with relative path would be the best. Please let me know If you have any idea how to use a relative base path.

**Comment by posva** [comment]
Ah I see, that got fixed at https://github.com/vuejs/vue-router-next/issues/261 but hasn't been released. You won't need to provide any base, it will use the `location.pathname` by default but you can explicitly pass it for now: `createWebHashHistory(location.pathname)`

**Comment by nomanHasan** [comment]
@posva Thank you very much for you help :)

**Comment by posva** [comment]
I released it a few hours ago btw :)

**Comment by nomanHasan** [comment]
@posva Many Thanks ! It works great now. :)
