### ISSUE TITLE
route.fullPath always shows "/" on early stage of Vue app

### ISSUE THREAD

**Issue by mannok** [vuejs/vue-router-next#314]
### Version
4.0.0-alpha.13

### Reproduction link
[https://github.com/vuejs/vue-router-next](https://github.com/vuejs/vue-router-next)

### Steps to reproduce
1. clone vue-router-next repository onto local machine
2. `npm i`
3. add `console.log(route.fullPath);` at line 207 (right before return statement)
4. `npm run dev`
5. visit http://localhost:808x/users/1 and view console panel
6. `fullPath` shown as "/"

### What is expected?
fullPath shown as "/user/1"

### What is actually happening?
`fullPath` shown as "/"

---
route.fullPath always shows "/" whatever I enter in the URL. This only happen at the very early stage when accessing the Vue app. i.e. App.vue.

However, it works well after the router-view's component has been successfully loaded. i.e. I can get the correct route.fullPath in the page which has been loaded by <router-view></router-view>.

Did I missed something? Please help me out.

**Comment by posva** [comment]
This is expected. You can wait for the initial navigation to be finished to mount if you want:

```js
router.isReady().then(() => app.mount())
```
