### ISSUE TITLE
^4.0.0-alpha.0，'markNonReactive' was not found in 'vue'

### ISSUE THREAD

**Issue by hengshanMWC** [vuejs/vue-router-next#327]
### Version
4.0.0-alpha.0

### Reproduction link
[https://github.com/vuejs/vue-next-webpack-preview](https://github.com/vuejs/vue-next-webpack-preview)

npm i -S @posva/vue-router-next

### Steps to reproduce
"@posva/vue-router-next": "^4.0.0-alpha.0"
"export 'markNonReactive' was not found in 'vue'

### What is expected?
`markNonReactive` has been renamed to `markRaw`

### What is actually happening?
"export 'markNonReactive' was not found in 'vue'

**Comment by hengshanMWC** [comment]
![image](https://user-images.githubusercontent.com/45714422/85357766-af334d80-b544-11ea-8c06-db3ecb9202ab.png)
Ok, you have fixed it, look forward to submitting to npm

**Comment by posva** [comment]
Yes, please upgrade the version
