### ISSUE TITLE
Nested views with defined custom scroll element does not reset scroll position

### ISSUE THREAD

**Issue by donnysim** [vuejs/vue-router-next#329]
### Version
4.0.0-alpha.13

### Reproduction link
[https://codesandbox.io/s/frosty-sea-ye8ev](https://codesandbox.io/s/frosty-sea-ye8ev)

### Steps to reproduce
1. Click Foo or Bar
2. Scroll down
3. click Foo or Bar

### What is expected?
#app element scrolls to the top

### What is actually happening?
#app element scroll is unchanged

**Comment by posva** [comment]
I don't understand what you are expecting. The page scrolls to `#app` with an offset of 0

**Comment by donnysim** [comment]
Shouldn't the #app container scroll to the top and the page?

**Comment by posva** [comment]
it **is** scrolling to the top of the page. What browser are you using?

the scroll behavior is following https://github.com/vuejs/rfcs/pull/176

**Comment by donnysim** [comment]
Chrome 83, only body is scrolling.

**Comment by posva** [comment]
yes, that's expected. The `el` property is not to scroll inside of an element but to scroll to a specific element position
