### ISSUE TITLE
`router-view` not rendering correctly in jsdom?

### ISSUE THREAD

**Issue by lmiller1990** [vuejs/vue-router-next#330]
Vue: ^3.0.0-beta.15
VueRouter:  4.0.0-alpha.13
jsdom: ^16.2.2

Hi. I was trying `vue-router-next` with one of my apps, which uses VTU for testing. I found an odd behavior where I cannot get `<router-view>` to render, instead it is rendering `<!-- -->`. I was able to reproduce it without the VTU dependency, too.

```
describe('vue-router', () => {
  const App = {
    render() {
      return (
        h('span', [
          h(RouterView)
        ])
      )
    }
  }

  it('does not render the router-view', async () => {
    const el = document.createElement('div')
    el.id = 'app'
    document.body.appendChild(el)
    const app = createApp(App)
    app.use(router())
    app.mount(el)
    console.log(document.body.innerHTML)
  })
})
```

The `console.log(document.body.innerHTML)` shows:

```html
<div id="app"><span><!----></span></div>
```

The part with `<!---->` should be `<router-view />`.

This should be easy enough to reproduce in this code-base, too, since it is set up with Jest.

**Comment by posva** [comment]
Have you checked the differences with the tests that are written here? You need to wait for the router to be ready (initial navigation) before it can render anything
If you have, a reproduction will help. It can be a pull request with a unit test too

**Comment by lmiller1990** [comment]
Yep, looks like I should have read the docs.

I updated my code and it worked fine. 

```ts
const app = createApp(App)
const router = makeRouter()
app.use(router)
await router.isReady()
app.mount(el)
```

If anyone finds issue, breaking changes (like navigations been async] are documented [here](https://github.com/vuejs/vue-router-next#breaking-changes-compared-to-vue-router3x). I will add an example to the VTU docs for Vue Router, and include this note. Thanks! Everything else is working great, built a few small apps and haven't found any other notable bugs or problems. 👍
