### ISSUE TITLE
Vue Router Next without Webpack

### ISSUE THREAD

**Issue by navinSing** [vuejs/vue-router-next#336]
### What problem does this feature solve?
I have a simple application, and i think using webpack will complicate things in deployment. I tried vue-router without webpack but looks like it isn't supported.

Is there a way to use vue-router next without webpack.

### What does the proposed API look like?
Without webpack index.html would be something like 
```
<script src="vue.js" />
<script src="vue-router.js" />


// define routes 
// init router 
// init app 

```

**Comment by posva** [comment]
Take a look at the reproduction at https://new-issue.vuejs.org/?repo=vuejs/vue-router-next (https://jsfiddle.net/posva/3yq6ojLv/5) and https://codesandbox.io/s/vue-router-v4-reproduction-tk1y7
