### ISSUE TITLE
Router computed emit undefined after component unmounted

### ISSUE THREAD

**Issue by johnsoncodehk** [vuejs/vue-router-next#350]
### Version
3.0.0-beta.18

### Reproduction link
[https://github.com/johnsoncodehk/vue-next-bug](https://github.com/johnsoncodehk/vue-next-bug)

### Steps to reproduce
Click "Page B" to switch page /a to /b

### What is expected?
Console log:
- /a

### What is actually happening?
Console log:
- /a
- undefined

**Comment by posva** [comment]
Created https://github.com/vuejs/vue-next/issues/1525
