### ISSUE TITLE
Infinite beforeRouteLeave

### ISSUE THREAD

**Issue by cexbrayat** [vuejs/vue-router-next#362]
### Version
4.0.0-beta.1

### Reproduction link
[https://github.com/cexbrayat/router-leave-regression](https://github.com/cexbrayat/router-leave-regression)

### Steps to reproduce
The repro link contains a small vite app with the router displaying a `HelloWorld` component with a basic leave guard:
```typescript
    const saved = ref(false);
    onBeforeRouteLeave((to, from, next) => {
      if (!saved.value) {
        const confirmation = confirm('Are you sure you want to leave the current page?');
        if (!confirmation) {
          next(false);
        } else {
          next();
        }
      }
    });
```
The repo uses `4.0.0-alpha.14` and works perfectly: the confirm window is displayed, and we can cancel the navigation to stay on the component.

When bumping the repo to `4.0.0-beta.1` then the confirm window is displayed  right away on cancel.

### What is expected?
We should not see the confirm window on cancelation

### What is actually happening?
The confirm window is displayed  right away on cancel with `beta.1`.

**Comment by posva** [comment]
It seems there was a cache problem when bundling vue-router. I will release a new version

**Comment by posva** [comment]
Should be good now

**Comment by cexbrayat** [comment]
Indeed it works! I tried to manually debug it, but did not understand what was going on. I did not suspect a bundling issue, that explains everything, thank you 👍
