### ISSUE TITLE
router push gives DOMException: Failed to execute 'replace' on 'Location': 'http://localhost:8080undefined' is not a valid URL

### ISSUE THREAD

**Issue by leopsidom** [vuejs/vue-router-next#366]
Using `router.push(path)` but get an error as in the title. When looking at the debugger, it fails at the `changeLocation` line: 

```
    function push(to, data) {
        const currentState = assign({}, history.state, {
            forward: to,
            scroll: computeScrollPosition(),
        });
        changeLocation(currentState.current, currentState, true);    // this is the line that fails
```

I can see in the debugger that `to` has the correct value but `currentState.current` is undefined. What could be the issue?

**Comment by alicemw** [comment]
why this problem is still confused me

**Comment by Viterbo** [comment]
Workaround:

if you use `history.pushState(...) ` directly alone with Vue router navigation you can avoid this problem by adding the current property yourself like this:

```javascript
const new_state = {
   whatever: 'this is your data',
   current: '/'   // this is the workaround
}

window.history.pushState(new_state, '', '/next/path');
```

What was the problems?
I used `history.pushState(...) ` to keep the navigation state on the URL but this way of changing URL does not use the Vue router which sets for itself the current property every time. If you use `history.pushState(...)` directly it does not fail immediately but it does not set the current property. So it fails the next time you try to use the normal Vue router.

**Comment by 9teen90nine** [comment]
This also happens if you push something to history state **before** `createWebHistory`. Router checks only whole state [value](https://github.com/vuejs/router/blob/6a11243915549b80fd0544b1f5d705f1617b1ae9/packages/router/src/history/html5.ts#L189) skipping setting `current` and other router-specific values triggering this bug on any `.push` call.
