### ISSUE TITLE
Watch is triggered from previous route component

### ISSUE THREAD

**Issue by xSorc** [vuejs/vue-router-next#374]
### Version
4.0.0-beta.2

### Reproduction link
[https://jsfiddle.net/pqxarzkL/3/](https://jsfiddle.net/pqxarzkL/3/)

### Steps to reproduce
1. Open jsfiddle
2. Clear console
3. Click button "change route"
4. Watch console

### What is expected?
I expect only one log from active route component.

### What is actually happening?
Console contains 2 logs. One from active route component and another one from already destroyed component.

---
Vue documentation(https://composition-api.vuejs.org/api.html#watcheffect) says, that watchEffect "invoked after all component update effects". But in this case watchEffect invoked after component was destroyed.

**Comment by posva** [comment]
Opened https://github.com/vuejs/vue-next/issues/1603
