### ISSUE TITLE
Initial navigation should keep the search query before the hash

### ISSUE THREAD

**Issue by posva** [vuejs/vue-router-next#378]
### Version
4.0.0-beta.2

### Reproduction link
[https://github.com/vuejs/vue-router-next](https://github.com/vuejs/vue-router-next)

### Steps to reproduce
- `yarn dev:e2e`
- go to http://localhost:8080/hash/?code=foo

### What is expected?
URL to become http://localhost:8080/hash/?code=foo#/

### What is actually happening?
URL becomes URL to become http://localhost:8080/hash/#/

**Comment by shen-zhao** [comment]
@posva 
May I ask when will it be released?
