### ISSUE TITLE
Add tags.json and attributes.json files for Vetur

### ISSUE THREAD

**Issue by posva** [vuejs/vue-router-next#381]
See https://github.com/vuejs/vetur/issues/2046

I think it makes sense to add a folder `vetur` and add the file paths to the `package.json` file like mentioned at https://vuejs.github.io/vetur/framework.html

cc @octref

**Comment by posva** [comment]
@octref let me know if I missed anything!

**Comment by octref** [comment]
It's already working (duplicates because Vetur bundles vue-router tags as well).

![image](https://user-images.githubusercontent.com/4033249/89364288-bda88380-d704-11ea-9586-b2af0d726822.png)

I'll send another PR that updates the tags/attributes.

**Comment by posva** [comment]
Ok, let me add them to current Vue Router as well and release a version in both so you can safely remove them from Vetur
