### ISSUE TITLE
router-link-active on children routes

### ISSUE THREAD

**Issue by xSorc** [vuejs/vue-router-next#384]
### Version
4.0.0-beta.3

### Reproduction link
[https://jsbin.com/sibekoledi/1/edit?html,css,js,output](https://jsbin.com/sibekoledi/1/edit?html,css,js,output)

### Steps to reproduce
1. Open jsbin
2. Click "bar link"

### What is expected?
Only "bar link" is active

### What is actually happening?
Both "foo link" and "bar link" is active

---
Correct me if i mistaken, but according to this [rfc](https://github.com/vuejs/rfcs/blob/master/active-rfcs/0028-router-active-link.md#unrelated-but-similiar-routes)(section Unrelated but similiar routes), only one link should be active

Addition: if we change "path" param of "foo" route to `route: "/"` - it fixes active behaviour, but it breaks initial state(after page reload)

**Comment by posva** [comment]
This is intended because it has an empty path, so it gets assimilated as the parent and is active. You can use exact-active to have the behavior you want
