### ISSUE TITLE
empty route-view cause transition failed

### ISSUE THREAD

**Issue by yoyoys** [vuejs/vue-router-next#385]
### Version
4.0.0-beta.3

### Reproduction link
[https://github.com/yoyoys/vue-router-next-transition-bug](https://github.com/yoyoys/vue-router-next-transition-bug)

### Steps to reproduce
1. switch to Empty test route
2. switch back to any route

### What is expected?
the transition should be effect

### What is actually happening?
nothing happened, but the transition will apply on other component or non-empty route

---
This bug made nest route transition failed.

**Comment by yoyoys** [comment]
@posva is this same issue?

https://github.com/vuejs/vue-next/issues/1697

**Comment by posva** [comment]
I doubt it since this was fixed on Vue Router but I can't tell because you didn't provide any reproduction

**Comment by yoyoys** [comment]
> I doubt it since this was fixed on Vue Router but I can't tell because you didn't provide any reproduction

I actually did reproduction, i'd made 2 repo to reproduction.

vuejs/vue-next#1697 is another problem with transition component

**Comment by yoyoys** [comment]
@posva sorry I'd push 2.x code to reproduction this problem, thanks.
