### ISSUE TITLE
404 Catch-all asterisk not detected

### ISSUE THREAD

**Issue by noook** [vuejs/vue-router-next#406]
### Version
4.0.0-beta.6

### Reproduction link
[https://jsfiddle.net/3z19sev8/](https://jsfiddle.net/3z19sev8/)

### Steps to reproduce
Hit a non-existing route as a logged user to be redirected to default page as logged user

### What is expected?
Subroute should redirect me to the `/calls` route on the `/void` route

### What is actually happening?
[Vue Router warn]: No match found for location with path "/void"

---
I use two layouts, who share the same route path, but they both redirect to the other one if a user is authenticated or not. I define all my routes as children of those two layouts

**Comment by posva** [comment]
Please check the readme: https://github.com/vuejs/vue-router-next#breaking-changes-compared-to-vue-router3x

**Comment by noook** [comment]
Oh thanks I'm sorry, can't tell how I missed this 😓

**Comment by Rolanddoda** [comment]
@posva the link doesn't seem to be working

**Comment by posva** [comment]
It's on the docs migration guide now
