### ISSUE TITLE
parseQuery and stringifyQuery

### ISSUE THREAD

**Issue by tomisicm** [vuejs/vue-router-next#409]
### Version
4.0.0-beta.6

### Reproduction link
[https://github.com/tomisicm/node-micro-stuff/blob/dev/bookie-front-vue3/src/router/index.ts](https://github.com/tomisicm/node-micro-stuff/blob/dev/bookie-front-vue3/src/router/index.ts)

### Steps to reproduce
I apologize for the link to minimal reproduction. I'll update it tomorrow, for now, I only provide a link to the lousy github file.

Steps:
I have tried using qs in the scenario given in the docs vue-router.d.ts line 798

the example is: 

parseQuery: qs.parse,
stringifyQuery: qs.stringify,

I've tried using it with the following query 

const query = {
  categories: ['Science, Fiction and Fantasy', 'Humor and Entertainment', 'Romance' ]
}

the first push (categories is length 1) works. The second push also works. 
But the third push ( adding Romance on top of the previous two query params does not occur with the following code line

this.$router.push({
      name: 'books',
      query: { 'categories': this.selectedCategories }
})

The URL I get from qs seems ok. There is something weird going on with push?

Routing works perfectly fine without the 
parseQuery: qs.parse,
stringifyQuery: qs.stringify

### What is expected?
Expecting url to change after push occurs.

### What is actually happening?
Actual url does not change.
It stays the same as in "second push" when the categories array was of length 2
e.g. 
?categories%5B0%5D=Romance&categories%5B1%5D=Humor%20and%20Entertainment

**Comment by posva** [comment]
Open a new issue once you have the boiled down reproduction. Note Vue Router already supports arrays, you don't need an external library for that
