### ISSUE TITLE
Transition problem. _leaveCb call on null object. (Reproduction attached)

### ISSUE THREAD

**Issue by burs14** [vuejs/vue-router-next#418]
### Version
3.0.0-rc.5

### Reproduction link
[https://codesandbox.io/s/wild-flower-95h7z](https://codesandbox.io/s/wild-flower-95h7z)

Please let us know if the link does not work. We have never used it before. We have tried it ourselves and it appears to work as expected.

### Steps to reproduce
~Replicated this on Chrome. Have not tried other browsers yet.~
Replicated on Chrome and Firefox.

1. Open codesandbox link.
2. Run the sample, and navigate to the root url
3. Go through P2 -> P3 -> P4 -> P5. Please let transitions complete before moving to the next one.
4. When you reach P5, you will see the error in console:

```
Uncaught (in promise) TypeError: Cannot read property '_leaveCb' of null
    at Object.beforeEnter (vue.js:3465)
    at mountElement (vue.js:4847)
    at processElement (vue.js:4792)
    at patch (vue.js:4705)
    at componentEffect (vue.js:5178)
    at reactiveEffect (vue.js:330)
    at effect (vue.js:305)
    at setupRenderEffect (vue.js:5144)
    at mountComponent (vue.js:5102)
    at processComponent (vue.js:5058)
```
The P5 transition does not finish, and further transitions no longer function until the page is refreshed.

Please note that after this we are seeing the console flooded with 

```
[Vue warn]: Avoid app logic that relies on enumerating keys on a component instance. The keys will be empty in production mode to avoid performance overhead. 
  at <Page5 data-v-7467e052="" onVnodeMounted=fn<onVnodeMounted> onVnodeUnmounted=fn<onVnodeUnmounted>  ... > 
  at <RouterView data-v-7467e052="" > 
  at <Anonymous onVnodeMounted=fn<onVnodeMounted> onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy {…} >  ... > 
  at <BaseTransition mode="out-in" appear=false persisted=false  ... > 
  at <Transition name="fade" mode="out-in" > 
  at <RouterView> 
  at <Page3 onVnodeMounted=fn<onVnodeMounted> onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy {…} >  ... > 
  at <BaseTransition mode="out-in" appear=false persisted=false  ... > 
  at <Transition name="fade" mode="out-in" > 
  at <RouterView> 
  at <Page1 onVnodeMounted=fn<onVnodeMounted> onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy {…} > > 
  at <RouterView> 
  at <App>
```

We are not sure why this is happening. We did not see this with the issue in our codebase.

### What is expected?
Transitions should work.

### What is actually happening?
Seeing an error, and the transitioned component does not appear. Further transitions no longer work until the page is refreshed.

---

@posva 

I am writing this for my coworker as his English is not great. He would like to apologise for his earlier issue - he has been attempting to debug the issue for a few hours now and grew frustrated. Please accept our apologies in ignoring the rules for posting issues.

**Comment by posva** [comment]
The problem seems to come from the wrapper at /p3/test. Using

```vue
<template>
  <router-view v-slot="{ Component }">
    <transition name="fade" mode="out-in">
      <component :is="Component" />
    </transition>
  </router-view>
</template>

<style scoped>
.fade-enter-active,
.fade-leave-active {
  transition: opacity 0.1s;
}

.fade-enter-from,
.fade-leave-to {
  opacity: 0;
}
</style>
```

as the component for that route record removes the error. Using a wrapping `div` also solves the issue. Probably related to the inheriting of `refs` but needs more investigation

**Comment by burs14** [comment]
Much appreciated. 

We followed the example in the RFC - https://github.com/vuejs/rfcs/blob/master/active-rfcs/0028-router-active-link.md#unrelated-but-similiar-routes - so we assumed that the issue was elsewhere.

Thanks for following up. Appreciate the work you've put in.

**Comment by burs14** [comment]
@posva Hello, just another update on this one. I have attempted to create a minimal reproduction of this without success, but it appears to be a similar issue. Apologies for the lack of reproduction, we will continue to attempt to reproduce this but we cannot afford to keep dwelling on this as there is a workaround. I hope this assists you in debugging the issue.

I created an intermediate component as a wrapper as you suggested:

```
<template>
  <router-view v-slot="{ Component }">
    <transition name="fade" mode="out-in">
      <component :is="Component" />
    </transition>
  </router-view>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({});
</script>

<style scoped>
.fade-enter-active,
.fade-leave-active {
  transition: opacity 0.1s;
}

.fade-enter-from,
.fade-leave-to {
  opacity: 0;
}
</style>
```

This workaround solves the original issue, however, we observed a case where navigating between routes on the same level as p3 can result in the router-view not being rendered and is stuck in this state until refresh. There are no error messages in this case.

A few of interesting things:

- Navigating within the p3 tree to works without issue.
- Navigating to the p3 tree works without issue.
- Navigating between other routes on the p3 level work fine, the issue only occurs when we navigate to the p3 tree, then back to any of the other routes
- The issue may be related to the modes, changing modes on the base router-view and the wrapper component "solves" the issue with some combinations. Some examples:
  - "out-in" on both, fails
  - no mode on both, succeeds
  - "in-out" on base, "out-in" on wrapper, succeeds
- Wrapping the wrapper in an additional `<div>` appears to serve as a workaround for this issue.

**Comment by posva** [comment]
Upon further investigation, the error is expected. Page3 having

```vue
    <router-view v-slot="{ Component }">
      <transition name="fade" mode="out-in">
        <component :is="Component"/>
      </transition>
    </router-view>
```

while the nested Page4 is just `<router-view/>`. Is the same as writing

```vue
    <router-view v-slot="{ Component }">
      <transition name="fade" mode="out-in">
        <router-view/>
      </transition>
    </router-view>
```

Which is invalid and would trigger the warning about router-view being inside transition. Maybe there is a way to warn against it by looking at the vnodes returned by v-slot
