### ISSUE TITLE
$route and $router type declarations seem to be missing in distributed declaration file

### ISSUE THREAD

**Issue by Aurelius333** [vuejs/vue-router-next#419]
### Version
4.0.0-beta.6

### Reproduction link
[https://github.com/aurelius333/vue-router-next-typing-repro](https://github.com/aurelius333/vue-router-next-typing-repro)

### Steps to reproduce
Open `src/views/index.vue` and look for typing errors.

### What is expected?
Should be typed correctly

### What is actually happening?

Error message:
```
Property '$route' does not exist on type 'ComponentPublicInstance<{}, {}, {}, { theRoutePath(): string; }, {}, Record<string, any>, Readonly<{}>, ComponentOptionsBase<{}, {}, {}, { theRoutePath(): string; }, {}, ComponentOptionsMixin, ComponentOptionsMixin, Record<...>, string>>'.
```

---
It looks like the types appear here: https://github.com/vuejs/vue-router-next/blob/7869764cb5fefcf1fe02521c252b3e1ee35d4180/src/index.ts#L65-L115

However, they don't seem to show up in the final distributed `vue-router.d.ts`: <https://unpkg.com/browse/vue-router@4.0.0-beta.6/dist/vue-router.d.ts>. (I just searched for "`$route`" in this file and it didn't show up.)

**Comment by posva** [comment]
It looks like there is a bug in api-extractor https://github.com/microsoft/rushstack/issues/2090 https://github.com/microsoft/rushstack/issues/1709

I wonder if we can find a workaround in the mean time that isn't appending the content to the final d.ts file

**Comment by tassioFront** [comment]
It works for me:

in `./shims-vue.d.ts` file

```JS
import VueRouter, { Route } from 'vue-router'

declare module '@vue/runtime-core' {
  interface ComponentCustomProperties {
    $router: VueRouter;
    $route: Router;
  }
}
```
