### ISSUE TITLE
transition can not work correctly with vue-router@next

### ISSUE THREAD

**Issue by qietuzi** [vuejs/vue-router-next#447]
### Version
3.0.0-rc.9

### Reproduction link
[ https://github.com/qietuzi/vue3.0.0-rc.9-bug-report]( https://github.com/qietuzi/vue3.0.0-rc.9-bug-report)

#### Vue@2.6.12   Vue-Router@3.4.3 https://jsfiddle.net/823123314/r7q60o4a/8

<img style="max-width: 100%;" src="https://raw.githubusercontent.com/qietuzi/vue3.0.0-rc.9-bug-report/master/other/right.gif" />

#### Vue@3.0.0-rc.9   Vue-Router@4.0.0-0 https://github.com/qietuzi/vue3.0.0-rc.9-bug-report

<img style="width: 100%;" src="https://raw.githubusercontent.com/qietuzi/vue3.0.0-rc.9-bug-report/master/other/error.gif" />

```javascript

export default defineComponent({
  setup() {
    let lastRouteIndex = 0;
    const route = reactive(useRoute());
    const transition = ref("right-slide-in");

    watch(() => route.meta.index, (index: number) => {
      if (index >= lastRouteIndex) {
        transition.value = "right-slide-in";
      } else {
        transition.value = "left-slide-in";
      }
      lastRouteIndex = index;
    });

    return {
      transition: transition
    };
  }
});
```

### What is expected?
router change transion by router index

### What is actually happening?
the transition is not right

---
I am not sure the problem cause by Vue or Vue-Router. It's seems like the transition cached the last value, like this:
<img style="max-width: 100%;" src="https://raw.githubusercontent.com/qietuzi/vue3.0.0-rc.9-bug-report/master/other/guess.png" />

**Comment by posva** [comment]
You need to run the watcher before:

```js
    watch(
      () => route.meta.index,
      (index: number) => {
        if (index >= lastRouteIndex) {
          transition.value = 'right-slide-in'
        } else {
          transition.value = 'left-slide-in'
        }
        lastRouteIndex = index
      },
      { flush: 'pre' }
    )
```

You could also use a navigation guard to handle the change

BTW there is no need to use `reactive` around useRoute
