### ISSUE TITLE
Failed at the vue-router@4.0.0-beta.8 postinstall script.

### ISSUE THREAD

**Issue by ellisonpatterson** [vuejs/vue-router-next#450]
### Version
4.0.0-beta.8

### Steps to reproduce
npm update

---
livestream@roc-hosting:~/webapps/livestream/frontend$ npm update

> vue-router@4.0.0-beta.8 postinstall /home/livestream/webapps/livestream/frontend/node_modules/vue-router
> patch-package

sh: 1: patch-package: not found
npm WARN bootstrap@5.0.0-alpha1 requires a peer of popper.js@^1.16.0 but none is installed. You must install peer dependencies yourself.
npm WARN vue-loader@15.9.3 requires a peer of css-loader@* but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! vue-router@4.0.0-beta.8 postinstall: `patch-package`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the vue-router@4.0.0-beta.8 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/livestream/.npm/_logs/2020-09-01T17_15_02_549Z-debug.log

**Comment by posva** [comment]
Thanks, will have to run the patch manually instead until a new version of vite and vitepress is released

**Comment by posva** [comment]
Should be good now!
