### ISSUE TITLE
Router push not work with lazyload route

### ISSUE THREAD

**Issue by parnus01** [vuejs/vue-router-next#453]
### Version
4.0.0-beta.9

### Steps to reproduce
1. create lazy load router example : 

```
const router = createRouter({
  history: createWebHistory(process.env.BASE_URL),
  routes: [
    {
      path: '/',
      name: 'Home',
      component: Home,
    },
    {
      path: '/about',
      name: 'About',
      component: () => import('@/views/About.vue')
    }
  ],
});
```

2. use router push from Home Page -> About Page 
```
<template>
  <div class="home">
    <img alt="Vue logo" src="../assets/logo.png">
    <a @click="routeToDynamicPage" href="">test router</a>
  </div>
</template>

<script lang="ts">
  import {defineComponent} from 'vue';
  import HelloWorld from '@/components/HelloWorld.vue';
  import router from "@/router"; // @ is an alias to /src

  export default defineComponent({
    name: 'Home',
    components: {},
    methods: {
      routeToDynamicPage() {
        router.push({
          name: 'About'
        })
      }
    }

  });
</script>

```
3. seem like vue load chuck of page, but it's still not redirect to new page

** If use normal route it's work fine

### What is expected?
Can use router.push({}) with lazy route

### What is actually happening?
Cannot use router.push({}) with lazy route

**Comment by parnus01** [comment]
**UPDATE** : I try to use router-link it work correctly, not sure we can use router.push in this version.

**Comment by posva** [comment]
Use à click.prevent or a router link (better) to prevent the regular a behavior
