### ISSUE TITLE
why automatically encode route.hash

### ISSUE THREAD

**Issue by wcycode** [vuejs/vue-router-next#463]
### Version
4.0.0-beta.9

### Reproduction link
[https://codesandbox.io/s/async-leaf-92ezw](https://codesandbox.io/s/async-leaf-92ezw)

### Steps to reproduce
click hash link

### What is expected?
it will be automatically coded hash

### What is actually happening?
no encode

---
in line: https://github.com/vuejs/vue-router-next/blob/7f95f86f71746d031dee4c4fff293b560cca80dd/src/router.ts#L452

In the historical version while not encode route.hash， so we also encode hash before router.push，when in route 4.x it  will be automatically coded to cause history code is no work

**Comment by posva** [comment]
To be consistent across browsers by providing the enconded value while allowing the user to always provide a non encoded version. That way hash is always unencoded, it's consistent

It's definitely open to discussion if there are more important concerns but this is considered an improvement

**Comment by wcycode** [comment]
thank you.  I just worry about historical project migration.  Now I have finished the upgrade.

**Comment by posva** [comment]
Okay! Since it's documented at https://next.router.vuejs.org/guide/migration/#route-properties-encoding, I'm closing this
