### ISSUE TITLE
RouteLink component will refresh page when has @click attr

### ISSUE THREAD

**Issue by wcycode** [vuejs/vue-router-next#464]
### Version
4.0.0-beta.9

### Reproduction link
[https://codesandbox.io/s/peaceful-shannon-powin?file=/index.html](https://codesandbox.io/s/peaceful-shannon-powin?file=/index.html)

### Steps to reproduce
click home link, the browser while refresh

### What is expected?
no refresh

### What is actually happening?
refresh page

**Comment by posva** [comment]
This is expected due to changes in events in Vue. Add a `.prevent` or use something different like `v-slot` since you are overriding the event added by router-link

**Comment by wcycode** [comment]
if use `.prevent` router-link will not jump
