### ISSUE TITLE
Nested router-view transitions hooks are never called

### ISSUE THREAD

**Issue by AgileInteractive** [vuejs/vue-router-next#465]
### Version
4.0.0-beta.9

### Reproduction link
[https://jsfiddle.net/kvwnah80/](https://jsfiddle.net/kvwnah80/)

### Steps to reproduce
Nest a component with router-view within another component with router-view, both with *transition v-on:enter* hooks.

Then route to a target with both main and nested view in one menu click.

### What is expected?
Both parent and nested view to call transition enter

### What is actually happening?
Only parent transition enter is called

---
Regarding the jsfiddle example, the problem is when staying at *1: Home* and navigating to *3: Subpage*.

[Edit]
If the parent router-view is cached (keep-alive), the transition for the nested router-view is actually called along with the parent transition. Keep clicking between *1: Home* and *3: Subpage* in the fiddle below:
https://jsfiddle.net/kvwnah80/1/

**Comment by posva** [comment]
If you want nested transitions to run when a parent component renders, you need to add the `appear` prop (regardless of vue-router). With keep-alive it works the second time because the components are not destroyed

**Comment by AgileInteractive** [comment]
Thank you 👍
