### ISSUE TITLE
Unexpected warning when using route without a component

### ISSUE THREAD

**Issue by mcrapts** [vuejs/vue-router-next#474]
In my app I'm using routes without any components attached to them. This used to work fine without errors and even the documentation shows examples of routes without a component. However, with `vue-router 4.0.0-beta.10` I'm getting the following warning:
```
Unexpected error when starting the router: TypeError: Cannot use 'in' operator to search for 'then' in undefined
    at extractComponentsGuards
```
In my opinion it is a perfectly valid use case to have routes without components, and shouldn't result in a warning. Also, even if there is a warning, the current warning is not clear to the end user. It took me a while to found out what the issue was.

**Comment by posva** [comment]
Can you share the route confit at the very least? Otherwise I can't help 😁

**Comment by mcrapts** [comment]
My route config is very simple:
```
routes: [
    {
      path: '/:type/:window?',
      name: 'view'
    }
  ]
```
I also tried to reproduce the issue in CodeSandbox, but I got a different error this time: https://codesandbox.io/s/objective-sutherland-qydbo?file=/index.html

**Comment by posva** [comment]
You only need to add a component property to the route record. It is required for non redirect records

**Comment by mcrapts** [comment]
I understand, but in this case the documentation is confusing. For example, https://next.router.vuejs.org/guide/essentials/route-matching-syntax.html#custom-regexp-in-params shows a lot of route configurations without any component. I also don't see it explicitly mentioned that a component property is required. I still think the component property should be optional, `vue-router` is already quite useful just for the purpose of extracting route parameters and programmatic navigation with parameters.

**Comment by posva** [comment]
The requirement is said during the getting started section (every route should map to a component). It doesn't always make sense to talk about components and add noise to docs when they do not matter like when we are talking about `path` but I see how there are a few places it should be present and probably a note at the top helps.

**Comment by pdanpdan** [comment]
Hello.
What is the best migration path for cases when the child routes define functional behavior of the parent one (like setting a selected state, or some option).

Should all the path parameters be set as optional on the main route?
But in this case the ease of use of named routes will be lost, and the definition of the path would become very verbose.

Another workaround would be to define a placeholder component for each such route, but it looks like a waste of resources, as the main route would have no RouterView and the component would never be mounted.
