### ISSUE TITLE
Nested #default router-view is not rendered

### ISSUE THREAD

**Issue by SimBioT1954** [vuejs/vue-router-next#475]
### Version
4.0.0-beta.11

### Reproduction link
[https://jsfiddle.net/kmxjbLu2/](https://jsfiddle.net/kmxjbLu2/)

### Steps to reproduce
I used to nest router-view #default into router-view #layout in my project on Vue2 but now it's not working even if I change everything according to the docs.

    <router-view name="layout" #default="{Component:LayoutComponent}">
        <component :is="LayoutComponent">
            <router-view>
            </router-view>
        </component>
    </router-view>

### What is expected?
Display layout router-view and it's content (default router-view)

### What is actually happening?
default router-view is not rendered

**Comment by SimBioT1954** [comment]
Is is supported at all?

**Comment by posva** [comment]
This was indeed never supported, it was a coincidence for it to work on v3. The reason is not supported is because nesting router-views relies on the nesting structure of `children` to know which router component to render.


What was supported and no longer is supported is passing direct slot content:

```html
  <router-view name="layout">
    <div>something</div>
  </router-view>   
```

Because of the new `v-slot` api to work with transitions and keep-alive, it has to be wrapped as well:

```html
  <router-view name="layout" #default="{Component:LayoutComponent}">
    <component :is="LayoutComponent">Some extra content</component>
  </router-view>  
```

I will add it to the migration guide!

**Comment by SimBioT1954** [comment]
@posva thank you for your reply!
Then how can I solve this problem?

I have 
     ` base-layout.vue `
      `dashboard-layout.vue`

Every route (page) of the app has it's layout:
```
{
 path:'/',
 components:{
 default: Component,
 layout: BaseLayout
 },
},
{
 path:'/dashboard',
 components: { 
 default: Component,
 layout: DashboardLayout
 }
}
```
Dashboard layout extends base layout and it is used in the part of the app where authorization is required.
Layouts have different templates as well.

How layouts can be implemented in Vue3?

**Comment by posva** [comment]
Put the layout in the meta field instead and use `<component :is="$route.meta.layout"><router-view /></component>
