### ISSUE TITLE
Your documents are too sloppy

### ISSUE THREAD

**Issue by shijunti19** [vuejs/vue-router-next#479]
### Version
4.0.0-beta.11

### Reproduction link
[https://next.router.vuejs.org/guide/essentials/named-views.html#nested-named-views](https://next.router.vuejs.org/guide/essentials/named-views.html#nested-named-views)

### Steps to reproduce
https://next.router.vuejs.org/guide/essentials/named-views.html#nested-named-views
<router-view class="view left-sidebar" name="left-sidebar"></router-view>
<router-view class="view main-content"></router-view>
<router-view class="view right-sidebar" name="right-sidebar"></router-view>

const router = createRouter({
  history: createWebHashHistory(),
  routes: [
    {
      path: '/',
      components: {
        default: Home,
        a: LeftSidebar,//This is not a and b
        b: RightSidebar,//This is not a and b
      },
    },
  ],
})

### What is expected?
LeftSidebar:LeftSidebar

### What is actually happening?
 a: LeftSidebar,//This is not a and B
        b: RightSidebar,//This is not a and B

**Comment by posva** [comment]
I fixed it at bb61528. As a maintainer, I would expect a pull request for this (there is an Edit this at the bottom of the page 😉 ) and not something like _Your documents are too sloopy_, which is not appreciated at all, we all do typos after all and that was completely unnecessary
