### ISSUE TITLE
The setup method cannot internally fetch the $Route object through the instance returned by getCurrentInstance

### ISSUE THREAD

**Issue by chaorenluo** [vuejs/vue-router-next#492]
### Version
4.0.0-beta.11

### Reproduction link
[https://jsfiddle.net/posva/3yq6ojLv/5](https://jsfiddle.net/posva/3yq6ojLv/5)

### Steps to reproduce
setup() {
const { ctx }:any = getCurrentInstance();
ctx.$route.  //Can't get

}

### What is expected?
You can get $route in setup

### What is actually happening?
Setup does not fetch $route

**Comment by posva** [comment]
Please check the documentation https://next.router.vuejs.org/guide/advanced/composition-api.html
