### ISSUE TITLE
Component error problem

### ISSUE THREAD

**Issue by anncwb** [vuejs/vue-router-next#493]
### Version
4.0.0-beta.11

### Reproduction link
[https://new-issue.vuejs.org/?repo=vuejs/vue-router-next](https://new-issue.vuejs.org/?repo=vuejs/vue-router-next)

### Steps to reproduce
When the component corresponding to the route reports an error, the error message is intercepted by the router, only the following error message is displayed, and no specific error message is visible. This is very troublesome for debugging
```
Uncaught (in promise) Error: Couldn't resolve component "default" for the following record with path "/"
    at vue-router.esm-bundler.js:1884
```

### What is expected?
Display specific error message

### What is actually happening?
Display routing error information

**Comment by posva** [comment]
Use the jsfiddle on the new issue page to provide a repro. Thank you

**Comment by vanoneang** [comment]
Hi @anncwb ,

I meet the same issue, did you resolve it?

**Comment by anncwb** [comment]
This is actually not a problem with the router. Check whether there is a problem with the corresponding page code

**Comment by 1beb** [comment]
I had a similar error, found that there was a problem with one of the imports in the script section of my component.

**Comment by fasalir** [comment]
> This is actually not a problem with the router. Check whether there is a problem with the corresponding page code

You are right, i forgot to add comma between methods

**Comment by cosmoarunn** [comment]
How to resolve if this problem persists when I have an additional url segment on the routes ? 
Eg : 

```
export const routes = [
    { path: '/marketplace.store',  name: 'store.home', component: () => StoreVue },
    { path: '/marketplace.store/products/:slug', name: 'products.show', component: ()=> ShowProductVue },
   . . .
```
I'm working with laravel and vue3 , vue-router 4.x, 
The firsr path is working fine, but the 'products.show' changes the window location but there's nothing changing on the page.

any help would be greatly appreciated. 
thanks in advance.
