### ISSUE TITLE
Bug:  The transition is always performed on the initial render of the node

### ISSUE THREAD

**Issue by boggddan** [vuejs/vue-router-next#496]
### Version
4.0.0-beta.12

### Reproduction link
[https://codesandbox.io/s/infallible-solomon-hoge9](https://codesandbox.io/s/infallible-solomon-hoge9)

### What is expected?
Transition does not always happen on initial rendering of a node if there is no attribute "appear"

### What is actually happening?
The transition is always performed on the initial render of the node.

**Comment by posva** [comment]
This is expected and mentioned in the migration guide!

**Comment by boggddan** [comment]
[solution](https://next.router.vuejs.org/guide/migration/#all-navigations-are-now-always-asynchronous)

Thank's
