### ISSUE TITLE
[ssr] Async route definition isn't compatible with SSR mode

### ISSUE THREAD

**Issue by JounQin** [vuejs/vue-router-next#498]
### Version
4.0.0-beta.12

### Reproduction link
[https://github.com/JounQin/serverless-study/blob/master/src/router.ts#L11](https://github.com/JounQin/serverless-study/blob/master/src/router.ts#L11)

### Steps to reproduce
1. run `yarn dev`, works as expected with `.then(Comp => Comp.default)`
2. remove `.then(Comp => Comp.default)`, `[Vue warn]: Component  is missing template or render function.` will be logged from `@vue/server-renderer`, and no route content will be server rendered, and client side route will do the job

### What is expected?
Without `.then(Comp => Comp.default)`, the async route on sever should also work

### What is actually happening?
Inconsistent between client and server

**Comment by JounQin** [comment]
Seems related to: https://github.com/vitejs/vite/issues/764

**Comment by posva** [comment]
This is an upstream bug as commented in the linked issue. I added a test at 65c18db

**Comment by JounQin** [comment]
@posva The test case seems different, the issue is caused by `Promise<{default: Component}>`.
