### ISSUE TITLE
Expose APi similar to `getRoutes()`, but ignoring nested routes

### ISSUE THREAD

**Issue by jungleBadger** [vuejs/vue-router-next#512]
### What problem does this feature solve?
As of today, I rely on the `this.$router.options.routes` schema. Basically, this is an array of routes from the first level only, nested routes aren't considered on this.

Vue 3.0 brought `this.$router.getRoutes()` which is clean and great, but I still need to be able to fetch the first level of routes to dynamically build a nested menu; I start from level 0 and iterate over the children of each route to build the menu accordingly.

### What does the proposed API look like?
```js
this.$router.getTopLevelRoutes();
```

Or some sort of parameter in the existent `getRoutes` API

```js

this.$router.getRoutes({
    "ignoreChildrenRoutes": true
});
```

**Comment by posva** [comment]
Is there any other use case apart from menus? This is something that can be achieved in multiple ways in user land:

- Filtering out routes if they are also children
- Adding a `meta` field to routes that you want to include in a menu and filter based on that
- Extending the router `instance to overwrite the `addRoute` to automate this

The `getRoutes` was initially thought from a dynamic routing perspective, so having a filtering mechanism attached to it doesn't seem right

**Comment by jungleBadger** [comment]
I'm finding cumbersome to define via array filter which routes don't have a parent, and since this information is already available through the `this.$router.options.routes` I thought it would be easier exposing this officially.

I use the `meta` fields to define those I want to index, therefore display it; I could do the same to say "hey, this is the root level", but again, since this info already exists, it would be awesome to have this exposed through an official API.

Any thoughts on how could I apply a `.filter` on `this.$router.getRoutes()` in a way that would work "universally"?

**Comment by posva** [comment]
> I use the meta fields to define those I want to index, therefore display it; I could do the same to say "hey, this is the root level", but again, since this info already exists, it would be awesome to have this exposed through an official API.

The information doesn't exist though. Note `router.options` is the initial options passed to the router. It's not updated when dynamically adding or removing routes. `getRoutes` intent is to get a list of the currently routes that exist in the application and that can be matched, to be able to add or remove routes accordingly.

You could filter them based on the `meta` field added: `router.getRoutes().filter(route => route.meta.isOnMenu)`. 

If the only use case is to automate displaying menus (which is an application-level feature), the goal of vue router is to enable creating such behavior like it does now: by defining at the routes level extra application-level information through `meta`

**Comment by jungleBadger** [comment]
Thanks for your ideas and insights, @posva. I do agree with you, but I still would find useful and scalable having this option exposed through an official API rather than accessing nested properties like that.

However, I understand & agree this is an app-level functionality and does make sense have a custom processing (e.g., filtering routes through meta info) preparing it.

I will wait a couple of days before closing this to see if there is someone with a different perspective about this.
