### ISSUE TITLE
Dynamically obtain route data and configure the relevant single page. Clicking one of the routing addresses will report an error.

### ISSUE THREAD

**Issue by WangLucy** [vuejs/vue-router-next#517]
### Version
3.0.0

### Reproduction link
[http://xujiawangzhi.com](http://xujiawangzhi.com)

### Steps to reproduce

App.vue:
<template>
  <div id="app">
    <layout />    
  </div>
</template>

 Configured dynamic routing  :

const formatterRoutes = (menu, appPrefix, appName) => {
    const accessedRoutes = []
    menu.map(item => {
        let defaultOpt = {}
       let componentItem = () => import(`@/views${item.path}/index.vue`)       
        defaultOpt = {
            meta: {
                title: item.menuName,
                icon: item.icon,
                appName,
                appPrefix
            },
            path: item.path,
            name: item.name,
           ...
        }
        if (
            item.children && 
            Object.prototype.toString.call(item.children === '[object Array]' && item.children.length)
        ) {
            accessedRoutes.push({
                ...defaultOpt,
                children: formatterRoutes(item.children,appPrefix,appName)
            })
        } else {
            accessedRoutes.push({...defaultOpt})
        }
    })
    return accessedRoutes
}

### What is expected?
Error is reported in "vue-router": "^4.0.0-beta.13", but it can be run in "vue-router": "3.0.6",

### What is actually happening?
in "vue-router": "^4.0.0-beta.13":
Uncaught (in promise) TypeError: Cannot use 'in' operator to search for 'then' in undefined;
No match found for location with path "/system/department"

**Comment by WangLucy** [comment]
hi~ 

In static routing, "matched" has a value, but in dynamic routing, "matched" is empty. I found that "createrouter()" is only executed at initialization time, and does not execute this method again after logging in to get dynamic routing data【 router.addRoute () this method will not call "createrouter()" again 】, so it will issue a warning like "no match found for location with path" / xxx / xxx "every time you click the menu. Can you give me some suggestions?!

**Comment by WangLucy** [comment]
Sorry, the above  URL is false, some of the links provided by the URL I can't visit, so I wrote the fake URL, please don't mind!

**Comment by ZHT131** [comment]
@WangLucy 你好你解决这个问题了吗，我也是动态添加路由就会报警告，但是跳转没问题

**Comment by ZHT131** [comment]
@WangLucy Hello, have you solved this problem? I will also report a warning if I add a route dynamically, but the redirection is okay.
