### ISSUE TITLE
Unexpected Behavior on Nested Routes

### ISSUE THREAD

**Issue by CodingCarter** [vuejs/vue-router-next#520]
### Version
4.0.0-beta.13

### Preview link
[https://vue-books-app.vercel.app/](https://vue-books-app.vercel.app/)

### Reproduction link
[https://github.com/CodingCarter/vue-books-app](https://github.com/CodingCarter/vue-books-app)

### Steps to reproduce
1. Clone the repo (https://github.com/CodingCarter/vue-books-app)
2. `npm install`
3. `npm run serve`
4. go to `http://localhost:8080`
5. Press the `All books` link
6. Click on the book name links and watch as the route changes, but the content stays the same.

### What is expected?
The separate `Book` templates should be displayed.

### What is actually happening?
The route is changing, but the content is remaining static.

### Notes
 - the 404 page is not shown, therefore the route path is valid

### Routes Data
Logging out the `routes` array will show the following data (components are omitted):
```json
[
  {
    "path": "/:pathMatch(.*)*"
  },
  {
    "path": "/"
  },
  {
    "path": "/books",
    "props": {
      "books": [
        {
          "title": "The Help",
          "author": "Kathryn Stockett",
          "slug": "the-help"
        },
        {
          "title": "How to Read Literature Like a Professor",
          "author": "Thomas C. Foster",
          "slug": "how-to-read-literature-like-a-professor"
        }
      ]
    },
    "children": [
      {
        "path": "the-help",
        "props": {
          "title": "The Help",
          "author": "Kathryn Stockett",
          "slug": "the-help"
        }
      },
      {
        "path": "how-to-read-literature-like-a-professor",
        "props": {
          "title": "How to Read Literature Like a Professor",
          "author": "Thomas C. Foster",
          "slug": "how-to-read-literature-like-a-professor"
        }
      }
    ]
  }
]
```

**Comment by posva** [comment]
You are missing `router-view` inside `Books` component: https://next.router.vuejs.org/guide/essentials/nested-routes.html

---

Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!

**Comment by CodingCarter** [comment]
Ahh, very sorry for bother you @posva .  Do you think that the router could include something that allows the route to be a child of the main route, but not use the `router-view`?  It would behave something like this:
```js
const routes = [
  {
    path: "/books",
    component: pages.books,
    props: { books },
    children: books.map((book) => ({
      useView: false,
      path: book.slug, // therefore, it generates `/books/${book.slug}` without using the <router-view> and just creates the code that is shown below
      component: templates.book,
      props: book,
    }))
  },
];
```
which would do the same as the following:
```js
const routes = [
  {
    path: "/books",
    component: pages.books,
    props: { books },
  },
  ...books.map((book) => ({
    path: `/books/${book.slug}`,
    component: templates.book,
    props: book,
  })),
];
```
