### ISSUE TITLE
Documentation is unclear with regards to routing modes

### ISSUE THREAD

**Issue by keithn** [vuejs/vue-router-next#524]
It took me a LONG time to find the hash mode as it is is listed under the "history modes".  I get that structurally that's how it works,  but it's not really how I was thinking of it, to me it just seems like a different mode/configuration/option of routing, and really wasn't expecting it under "Different History modes". It should be something like "Different Routing and History modes".   Hash routing seem completely independent to the concept of history.

**Comment by posva** [comment]
I'm still waiting for Algolia's search index, once there is a search this should be easier to find
