### ISSUE TITLE
router.push(' ') changes and the routing address does not change

### ISSUE THREAD

**Issue by WangLucy** [vuejs/vue-router-next#531]
### Version
4.0.0-beta.13

### Reproduction link
[https://github.com/WangLucy/vue-router-next-pro-demo/tree/master](https://github.com/WangLucy/vue-router-next-pro-demo/tree/master)

### Steps to reproduce
After successful login, the address displayed by the route is still "/ login", "dashboard.vue" is not shown。

### What is expected?
After successful login, enter the “dashboard” page

### What is actually happening?
After successful login, the routing address remains unchanged and the console reports an error：
Uncaught (in promise) Error: Couldn't resolve component "default" at "/system"

**Comment by posva** [comment]
I tried finding something but this is a whole project, I cannot check it. Please, open a new issue if you manage to boil it down to the minimal

**Comment by WangLucy** [comment]
> I tried finding something but this is a whole project, I cannot check it. Please, open a new issue if you manage to boil it down to the minimal

There is a problem with my routing configuration. I have solved it. Thank you!!!
