### ISSUE TITLE
Unexpected behaviour with nested router-view with transitions

### ISSUE THREAD

**Issue by scottasmith** [vuejs/vue-router-next#537]
### Version
4.0.0-beta.13

### Reproduction link
[https://jsfiddle.net/jr4hsqyL/5/](https://jsfiddle.net/jr4hsqyL/5/)

### Steps to reproduce
Open up the JSFiddle provided and then click on one of the User Index and/or User View. Then click home.
From there no components show.

### What is expected?
Should be able to keep click on the UserIndex and/or UserView and click Home and back and relevant component is dispayed

### What is actually happening?
As soon as you hit the last child router-view and go back up the stack (hitting Home) it somehow stops components showing

---
I am not sure if its this view-router or Vue 3 transitions that is at fault. If you use other values than "out-in" in the transition mode it seems to duplicate the components somehow

**Comment by posva** [comment]
Opened https://github.com/vuejs/vue-next/issues/2415
