### ISSUE TITLE
vue-router.esm-bundler.js?6c02:1031 Uncaught Error: Route paths should start with a "/": "**" should be "/**". #3349

### ISSUE THREAD

**Issue by wxwzl** [vuejs/vue-router-next#538]
### Version
4.0.0-beta.13

### Reproduction link
[ http://404]( http://404)

### Steps to reproduce
 { path: "**", redirect: "/404" },

### What is expected?
 { path: "**", redirect: "/404" }, it works;

### What is actually happening?
it does not work ,when i change it to "/**", it can not redirect the not-matched route to "/404"

**Comment by posva** [comment]
I left you a comment on the other issue
