### ISSUE TITLE
Can't show nested router-view

### ISSUE THREAD

**Issue by dxvladislavvolkov** [vuejs/vue-router-next#539]
### Version
4.0.0-beta.13

### Reproduction link
[https://jsfiddle.net/tj6L1byo/](https://jsfiddle.net/tj6L1byo/)

### Steps to reproduce
Open the link and click on a page
You will see only layout content

### What is expected?
I want to see the layout and the page contents

### What is actually happening?
I see the only layout

**Comment by posva** [comment]
This is because you are nesting the router view components while there is no nesting in the routing.
You can implement layouts in many ways, one of them being using `meta` properties: https://jsfiddle.net/a0oxq9vg/

**Comment by softboy99** [comment]
@posva ,could you please upload to another place, https://jsfiddle.net/a0oxq9vg/, can not be opened in china. It seems i have the same problem. Thanks a lot for your great help.

**Comment by softboy99** [comment]
<template>
  <div id="root">
    <div :class="cssClasses">
      <router-view
        name="layout"
        :title="title"
        :is-x-small="screen.isXSmall"
        :is-large="screen.isLarge"
      >
        <div class="content">
          <router-view name="content" />
        </div>
        <template #footer>
          <app-footer />
        </template>
      </router-view>
    </div>
  </div>
</template>

**Comment by softboy99** [comment]
`<template>
  <div id="root">
    <div :class="cssClasses">
      <router-view
        name="layout"
        :title="title"
        :is-x-small="screen.isXSmall"
        :is-large="screen.isLarge"
      >
        <div class="content">
          <router-view name="content" />
        </div>
        <template #footer>
          <app-footer />
        </template>
      </router-view>
    </div>
  </div>
</template>`

**Comment by softboy99** [comment]
If this kind of code are not allowed in vue router 4 for vue3.x, Please update vue router migration docs, thanks.

**Comment by posva** [comment]
```html
<div id="app">
  <div id="nav">
    <router-link to="/home">Home</router-link> |
    <router-link to="/page">Page</router-link>
  </div>
  
  <component v-if="$route.meta.Layout" :is="$route.meta.Layout">
    <router-view></router-view>
  </component>
  <router-view v-else></router-view>
</div>
```

```js

const { createRouter, createWebHistory } = VueRouter
const { createApp } = Vue

const Layout = { template: `<div>home <slot /></div>` }

const Page = { template: `<div>Page1</div>` }



const routes = [
  {
    component: Layout,
    path: '/home',
  },
  {
    path: '/page',
    meta: { Layout },
    component: Page
	},
];

const router = createRouter({
  history: createWebHistory('/'),
  routes,
});

const app = createApp({})
app.use(router)
window.vm = app.mount('#app')
```

This is already documented: https://next.router.vuejs.org/guide/migration/index.html#passing-content-to-route-components-slot

**Comment by softboy99** [comment]
Hi,
it about slot other than router view. why not to make the doc more clear?
