### ISSUE TITLE
Router-view plus key attribute causes keepAlive to fail

### ISSUE THREAD

**Issue by anncwb** [vuejs/vue-router-next#557]
### Version
4.0.0-rc.1

### Reproduction link
[https://codesandbox.io/s/vue-router-next-beforerouteupdate-forked-od2y4?file=/index.html](https://codesandbox.io/s/vue-router-next-beforerouteupdate-forked-od2y4?file=/index.html)

### Steps to reproduce
Delete :key="$route.path" and it works

I saw the (#444) problem, and added: key="$route.path". But it will cause keepAlive to fail. This is very important to me, is there any way to deal with it

### What is expected?
When router-view is keyed, keepalive is used normally

### What is actually happening?
When router-view is keyed, keepalive you can use it normally

**Comment by posva** [comment]
What does rt mean?

**Comment by anncwb** [comment]
Sorry I wrote it habitually。It has been modified

**Comment by posva** [comment]
You need to put the key on the component if you are using v slot

**Comment by anncwb** [comment]
@posva I modified the example because I forgot to add the transition tag. It can work before transition without adding mode="out-in". It won't work after adding

**Comment by anncwb** [comment]
When I switch routes, the page does not render. I mentioned this question in vue-next before, but I am not sure why this problem occurred

**Comment by anncwb** [comment]
can you help me?

**Comment by posva** [comment]
There is no `includes` prop in [keep alive](https://v3.vuejs.org/api/built-in-components.html#keep-alive), but I don't understand why it breaks with it
