### ISSUE TITLE
Passing attributes to view component

### ISSUE THREAD

**Issue by yaquawa** [vuejs/vue-router-next#559]
### What problem does this feature solve?
seems like vue-router can not passing attributes to the view component?

```js
const routes = [
    {
        path: "/dashboard/profile",
        name: "DashboardProfile",
        component: <DashboardProfile foobar="false"/>, // <--- I want to get this available
    },
];
```

### What does the proposed API look like?
```js
const routes = [
    {
        path: "/dashboard/profile",
        name: "DashboardProfile",
        component: DashboardProfile,
        componentAttributes: { foobar: false },
    },
];
```

**Comment by posva** [comment]
Check the option props for routes

**Comment by yaquawa** [comment]
The `props` option pass data to the store instance but not the view component itself right ? Have I missing something?

**Comment by posva** [comment]
https://next.router.vuejs.org/guide/essentials/passing-props.html#passing-props-to-route-components
