### ISSUE TITLE
transition动画只针对当前页面动画，新页面没有动画

### ISSUE THREAD

**Issue by yll1024335892** [vuejs/vue-router-next#571]
### What problem does this feature solve?
<router-view v-slot="{ Component }">
      <transition :name="transitionName">  
        <keep-alive include="Home,Assets,Lotter,My,Report">
          <component class="page" :is="Component" />
        </keep-alive>
      </transition>
    </router-view>
页面的进去都应该有一个平滑的动画，现在的情况是只有当前页面离开有动画，新页面没有动画直接出现(手机端展现)

### What does the proposed API look like?
当前页面离开的有一个动画，新页面出现也应该有一个动画

**Comment by posva** [comment]
Open the issue in English so we can communicate

**Comment by yll1024335892** [comment]
The transition of vue2.x and vue-router3.0.x, jump from one route to another route can set a very smooth transition effect (animation of page switching on the mobile phone)
