### ISSUE TITLE
Package file problem

### ISSUE THREAD

**Issue by anncwb** [vuejs/vue-router-next#573]
### Version
4.0.0-rc.1

### Steps to reproduce
I read the vue-router package file, such as this https://cdn.bootcdn.net/ajax/libs/vue-router/4.0.0-rc.1/vue-router.esm-browser.js

![image](https://user-images.githubusercontent.com/28132598/98203866-dcbae980-1f6f-11eb-868e-62e5bbe143f1.png)

I use vite to build and use online url.

But the direct reference to "vue" does not seem to support

### What is expected?
Use the URL address to obtain the esm module can be used normally

### What is actually happening?
Console error

**Comment by posva** [comment]
You will have to replace that `'vue'` by the link to the vue module link you want to use but we can't decide that for you because depending on where you are, you will want to use different CDNs.

FYI: https://v8.dev/features/modules#mjs

**Comment by anncwb** [comment]
But this link is online, how do I change the content inside
