### ISSUE TITLE
(Fix needed) unexpected 'prototype' error

### ISSUE THREAD

**Issue by mcdmaster** [vuejs/vue-router-next#577]
### Version
4.0.0-rc.2

### Reproduction link
[https://github.com/mcdmaster/covid19/tree/feat/vue3%2Bwebpack5](https://github.com/mcdmaster/covid19/tree/feat/vue3%2Bwebpack5)

### Steps to reproduce
Made up with vue-router-next@latest, vue@3.0.2 and webpack@5.3.0.
The auto-generated router produces an unexpected error: Cannot read property 'prototype' of undefined

### What is expected?
Error is fixed so that app proceeds to rendering

### What is actually happening?
An error which prevents application statrting

### Screenshot
![スクリーンショット 2020-11-07 015623](https://user-images.githubusercontent.com/10361533/98393392-8d260c00-209c-11eb-80d8-cf5d92ff271a.png)

**Comment by LinusBorg** [comment]
Nuxt 2 is not compatible with Vue 3 or Vue Router 4

**Comment by mcdmaster** [comment]
@LinusBorg ,

If it is intended to drop the current (not older) version of `nuxt` as "incompatible", I disagree to it. it is obvious that It would not seem confident for the developers at work in my team either.

From my own end, I am unsure why an old-skool-like `protype` property remains here still. Anyway, I intend to raise a PR. Thank you.

**Comment by LinusBorg** [comment]
Vue 3 is a major release, by definition it contains breaking changes.

Nuxt inbuilt on Vue 2 and needs it's own major release to become compatible with the changes in Vue 3.

That's not something we "declare", it's just technically necessary

**Comment by mcdmaster** [comment]
Thank you for prompt getting back.

I have recognized that aligning `nuxt` to `vue@3` is in progress; we can see it via the work goin on e.g. `nuxt-property-decorator`. If you are fine, please let me know if you think that it is better for me to work with `nuxt` guys than `vue` people. Thanks anyway
