### ISSUE TITLE
`redirect` is ignored when triggered through a popstate

### ISSUE THREAD

**Issue by lqsong** [vuejs/vue-router-next#590]
### Version
4.0.0-rc.2

### Reproduction link
[https://codesandbox.io/s/objective-lehmann-k60pj?file=/src/router.js](https://codesandbox.io/s/objective-lehmann-k60pj?file=/src/router.js)

### Steps to reproduce
```ts
const routes: Array<RouteRecordRaw> = [
  {
    path: '/user',
    redirect: '/user/login',
    component: UserLayout,
    children:  [
       {
          path: 'login',
          component: () => import('@/views/user/login/index.vue'),
      },
      {
          path: 'register',
          component: () => import('@/views/user/register/index.vue'),
      }
     ]
  },

]

const router = createRouter({
  history: createWebHashHistory(process.env.BASE_URL),
  routes
});

export default router;
```
Browser address bar :

  Step 1 、`http://localhost:8000/#/user/register`。

  Step 2 、Modify the `http://localhost:8000/#/user`，No jump to `http://localhost:8000/#/user/login`

### What is expected?
```ts
 {
    path: '/user',
    redirect: '/user/login'
}
```
Expect success ！

### What is actually happening?
`redirect` parameter is invalid

**Comment by posva** [comment]
It does get redirected to `/users/login`...
I tried direct navigation, router-link, web history and web hash history. All work

**Comment by lqsong** [comment]
> It does get redirected to `/users/login`...
> I tried direct navigation, router-link, web history and web hash history. All work

Step 1 、`http://localhost:8000/#/user/register`。

Step 2 、Address bar modify the `http://localhost:8000/#/user `  Enter，does not jump

**Comment by posva** [comment]
I finally managed to reproduce by trying out on a new window
