### ISSUE TITLE
HMR broken with lazy loaded page

### ISSUE THREAD

**Issue by Ercan93** [vuejs/vue-router-next#598]
### Version
3.0.2

### Reproduction link
[https://github.com/Ercan93/for-vue3-issue](https://github.com/Ercan93/for-vue3-issue)

### Steps to reproduce
1. Add new content About.vue on editor
2. View About page on browser
3. Click Home on header
4. Click browser previous button
5. See the old content of the About page

### What is expected?
When the previous button is clicked in the browser, the updated content of the About page should appear.

### What is actually happening?
When the previous button is clicked in the browser, old content of the About page appears.

---
Gif of steps to reproduce:
![vue3-issue](https://user-images.githubusercontent.com/33147661/99194399-2f767b80-2790-11eb-9580-b7028748df95.gif)

Video of steps to reproduce:
https://github.com/Ercan93/for-vue3-issue/blob/main/src/assets/vue3-issue.mp4

**Comment by posva** [comment]
No need, I transfered it @Ercan93

**Comment by posva** [comment]
This got actually fixed in vue core at https://github.com/vuejs/vue-next/commit/9c23ddf9c593dcf6d20bc911ec95d9b674f23dc8
I will revert the commit I added
