### ISSUE TITLE
Nested routes don't work without a full page refresh

### ISSUE THREAD

**Issue by martinszeltins** [vuejs/vue-router-next#603]
### Version
4.0.0-rc.5

### Reproduction link
[https://github.com/martinszeltins/app-scaffolding](https://github.com/martinszeltins/app-scaffolding)

### Steps to reproduce
When using nested routes and then calling ````router.push()```` to go to a new route it renders only the first component (layout) but not the child component. Then when you refresh the page then it loads the nested route component.

In the reproduction link, when you click "Log in" then it should render both "App layout" component and also the "Home" component but only the layout component gets rendered. After refresh both get rendered.

````
import { createWebHistory, createRouter } from "vue-router"

import AppLayout from "./views/layouts/app.vue"
import LoginLayout from "./views/layouts/login.vue"
import Home from "./views/home.vue"
import Login from "./views/login.vue"
import auth from './middleware/auth.js'

const routes = [
    {
        path: "/",
        name: "home",
        component: AppLayout,
        children: [
            {
                path: '',
                component: Home,
            }
        ],
        meta: {
            middleware: [ auth ],
        },
    },

    {
        path: "/login",
        name: "login",
        component: LoginLayout,
        children: [
            {
                path: '',
                component: Login,
            }
        ],
    },
]

const router = createRouter({
    history: createWebHistory(),
    routes,
})
````

### What is expected?
It should render both the "App layout" and "Home" components.

### What is actually happening?
Only the "App layout" component gets rendered.

**Comment by posva** [comment]
Move the `name: 'home'` to the route with `path: ''`.

---

Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!
