### ISSUE TITLE
Cannot switch between aliased paths

### ISSUE THREAD

**Issue by radek-altof** [vuejs/vue-router-next#613]
### Version
4.0.0-rc.5

### Reproduction link
[https://codesandbox.io/s/vue-router-4-reproduction-forked-qxzts](https://codesandbox.io/s/vue-router-4-reproduction-forked-qxzts)

### Steps to reproduce
Have a look at router aliases and try clicking through navigation.

### What is expected?
1) You should be able to navigate between aliased paths, even when they resolve to the current route object (so that the path changes).

2) `<router-link>` should have `router-link-exact-active` class only when the path matches exactly.

### What is actually happening?
1) You can't navigate between aliased paths that resolve to the current route object.

2) `<router-link>` has `router-link-exact-active` class when an entire route object matches (because of alias).

**Comment by ste-xx** [comment]
Workaround:
wrap onBeforeRouteLeave in a onMounted.

**Comment by posva** [comment]
This is expected: https://github.com/vuejs/rfcs/pull/136
Not treating the navigation as duplicated would be inconsistent and confusing with the active behavior

**Comment by radek-altof** [comment]
Ah crap, I'll need to work around then. I was relying on this behavior when using Vue Router 3. Thanks for pointing to the RFC.

**Comment by a0s** [comment]
@radek-altof Did you find the solution? I need to navigate between aliases like `/es/page` and `/nl/page` with switching language in `beforeEach`

**Comment by radek-altof** [comment]
@a0s To be perfectly honest, I don't remember at all, it's been a very long time 😅
