### ISSUE TITLE
Can't push new route in tests

### ISSUE THREAD

**Issue by manuelmazzuola** [vuejs/vue-router-next#615]
### Version
4.0.0-rc.5

### Steps to reproduce
In a vue 3.0.2, jest 24.9.0 test
The first push works, the seconds push trigger the error.

Using a custom RouterHistory makes it work.

```
const routesDefinitions = [
  {
    path: '/login',
    name: 'Login',
    component: { template: 'LOGIN' },
  },
  {
    path: '/home',
    name: 'Home',
    component: { template: 'HOME' },
  },
];

const router = createRouter({
  history: createWebHistory(),
  routes: routesDefinitions,
});

const wrapper = mount({ template: '<router-view />' }, {
  global: {
    plugins: [router]
  }
});

router.push('Login');
await router.isReady();

router.push('Home');
await router.isReady();
```

### What is expected?
Should change route

### What is actually happening?
```
(node:1425725) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '_history' of null
    at Window.get history [as history] (/home/originof/src/control-panel/node_modules/jest-environment-jsdom-fifteen/node_modules/jsdom/lib/jsdom/browser/Window.js:207:79)
    at finalizeNavigation (/home/originof/src/control-panel/node_modules/vue-router/dist/vue-router.cjs.js:2712:41)
    at catch.then (/home/originof/src/control-panel/node_modules/vue-router/dist/vue-router.cjs.js:2599:27)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:1425725) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:1425725) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by posva** [comment]
I couldn't find the link to the issue with the complete explanation but this is due to history being used after the test finishes. So make sure to await the last navigation of `router.push()`.

You should track https://github.com/vuejs/vue-test-utils-next/issues/152

**Comment by vincerubinetti** [comment]
This is very... odd....

I have a `<Tabs>` component that does `await this.$router.replace` when the user changes the active tab.

I sort of get how the history could end up being used after the test finishes. But if that's the case, wouldn't it be fixable by doing `afterAll(async () => await router.isReady());`? I can't get that to work. Instead I have to do `afterAll(async () => new Promise(resolve => window.setTimeout(resolve, 0));`.

Can anyone give any insight to this?
