### ISSUE TITLE
this.$route.query empty

### ISSUE THREAD

**Issue by RealAlphabet** [vuejs/vue-router-next#617]
### Version
4.0.0-rc.5

### Steps to reproduce
    const Home = {
       created() {
           console.log(this.$route.query); // Always empty.
       }
    };

    const router = createRouter({
        history: createMemoryHistory(),
        routes: [
            { path: '/', component: Home, props: console.log }
        ]
    });

### What is expected?
Not empty.

### What is actually happening?
Empty.

**Comment by posva** [comment]
Open issues with reproductions like asked in the helper. There is a starter js fiddle there too. Thanks

**Comment by RealAlphabet** [comment]
Done, I updated the original issue comment.

**Comment by posva** [comment]
That's literally my starter for a repro...
Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!
If you manage to boil it down and reproduce it, read https://new-issue.vuejs.org/?repo=vuejs/vue-router-next#why-repro and open a new issue following the guidelines.

**Comment by RealAlphabet** [comment]
> That's literally my starter for a repro...
> Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!
> If you manage to boil it down and reproduce it, read https://new-issue.vuejs.org/?repo=vuejs/vue-router-next#why-repro and open a new issue following the guidelines.

I copied incorrectly, I realized it 1 minute after posting the comment but you were too quick, sorry.
The link is correct now
