### ISSUE TITLE
this.$route.query empty

### ISSUE THREAD

**Issue by RealAlphabet** [vuejs/vue-router-next#618]
### Version
4.0.0-rc.5

### Reproduction link
[https://jsfiddle.net/m297stx4/](https://jsfiddle.net/m297stx4/)

### Steps to reproduce
    const { createRouter, createWebHistory } = VueRouter
    const { createApp } = Vue

    const App = {
        template: "<div>HelloWorld</div>",

        created() {
            console.log(this.$route.query);
        }
    };

    const router = createRouter({
        history: createWebHistory(),
        routes: []
    });

    createApp(App)
        .use(router)
        .mount('#app');

### What is expected?
Expect than https://jsfiddle.net/m297stx4?query=true fill the this.$route.query object.
`{ query: "true" }`

### What is actually happening?
`this.$route.query` is empty.
`{}`

**Comment by joostdelange** [comment]
I'm not sure if it's clear what `$route.query` is exactly.
In your example it is expected that `this.$route.query` because there does not seem to be any query data in the url.

I modified your example by adding a router push with query data. In the template you can see `$route.query` is now filled with the data I did the push with.

**Comment by RealAlphabet** [comment]
> I'm not sure if it's clear to you what `$route.query` is exactly.
> In your example it is expected that `this.$route.query` is an empty object because there does not seem to be any query data in the url.
> 
> I modified your example by adding a router push with query data. In the template you can see `$route.query` is now filled with the data I did the push with.
> 
> https://jsfiddle.net/kdbhpmy5/1/

I expect than https://jsfiddle.net/m297stx4?query=true fill the `this.$route.query` object.
`{ query: "true" }`

**Comment by joostdelange** [comment]
@RealAlphabet That is not gonna work in JSFiddle since it works using an iframe. The url you are seeing in your browser is not the one the Vue instance is using.
That is also the reason why my example is working, because I'm doing a `$router.push` after the instance is loaded. This modifies the URL of the JSFiddle iframe.

If you test this in a local environment of your own, you will see the behaviour is exactly what you expect.

**Comment by RealAlphabet** [comment]
> @RealAlphabet That is not gonna work in JSFiddle since it works using an iframe. The url you are seeing in your browser is not the one the Vue instance is using.
> That is also the reason why my example is working, because I'm doing a `$router.push` after the instance is loaded. This modifies the URL of the JSFiddle iframe.
> 
> If you test this in a local environment of your own, you will see the behaviour is exactly what you expect.

Fiddle is using the query `?editor_console=true` for the iframe.
Sadly the query object remain empty. **It's not working as expected.**

I'm able to work around the problem by putting it in a `setTimeout` callback but annoying because you can't trigger data changes inside. https://jsfiddle.net/t6xbroz7/

**Comment by joostdelange** [comment]
I just tested this in a local environment and @RealAlphabet seems to be right. It is not something related to JSFiddle.
This problem occurs when you load Vue and Vue router through `<script>` directly (like fiddle does), not when using a Vue CLI or Vite project.

I tried using the `nextTick`, unfortunately that does not work too.

**Comment by posva** [comment]
The query is probably added later by JSFiddle so when the router is initialized, it's not there yet, but this is not a router issue

**Comment by RealAlphabet** [comment]
> The query is probably added later by JSFiddle so when the router is initialized, it's not there yet, but this is not a router issue

We would remake the world with "probably". I checked it's not added later.
Also, If @joostdelange was able to reproduce it, it's not related to JSFiddle either.

**Comment by Unam3dd** [comment]
I have exactly the same problem.
![image](https://user-images.githubusercontent.com/34691959/100394815-ca980c80-303e-11eb-8efc-add824bb4dc0.png)

**Comment by RealAlphabet** [comment]
![tg](https://user-images.githubusercontent.com/23159705/100395277-94f42300-3040-11eb-9edf-ca48ff800054.gif)

**Comment by D0wzy** [comment]
I have the same problem (empty Object)

**Comment by RealAlphabet** [comment]
It's coming from Vue-Router. If I return the result directly by removing this promise it work fine.

![image](https://user-images.githubusercontent.com/23159705/100432211-8ede6080-3099-11eb-8153-282af3b080ea.png)

**Comment by uncodable** [comment]
> I just tested this in a local environment and @RealAlphabet seems to be right. It is not something related to JSFiddle.
> This problem occurs when you load Vue and Vue router through `<script>` directly (like fiddle does), not when using a Vue CLI or Vite project.
> 
> I tried using the `nextTick`, unfortunately that does not work too.

@posva Did you even read the comment above you said before you went ahead and closed this? Someone replicated the issue by not using JSFiddle.

**Comment by posva** [comment]
@uncodable Of course I read the comments. I tried yet, another time, not being able to reproduce the problem described of a query parameter.

FYI It's not okay to treat maintainers like this, most of us do care and spend a very large amount of time reading, answering, listening to feedback, and helping people out (on top of coding). I and other maintainers would appreciate it. It plays on our mental health to have to hear people like you assuming we don't care and without bringing anything to the conversation except for hate.

@RealAlphabet  
In the code you do a `console.log(this.$route.query)` in created, but note that the route won't be initialized until the initial navigation is complete, which is async: https://next.router.vuejs.org/guide/migration/index.html#all-navigations-are-now-always-asynchronous
Waiting for the initial navigation should help you see the correct route but note that in jsfiddle you won't see a query, you will see a url of `/_display/`, there doesn't seem to be a query

If you manage to reproduce the missing query outside of jsfiddle, with an iframe, please open a new issue with reproduction steps (they are supposed to be instructions like go to /xxx, click here, etc. not code. This will greatly help us) so I can take a look
