### ISSUE TITLE
router-view/ router-link cannot work

### ISSUE THREAD

**Issue by eric000** [vuejs/vue-router-next#629]
### Version
4.0.0-rc.6

### Reproduction link
[http://none](http://none)

### Steps to reproduce
start run script

### What is expected?
router-view/ router-link  normal 

### What is actually happening?
const RouterView = RouterViewImpl;
// warn against deprecated usage with <transition> & <keep-alive>
// due to functional component being no longer eager in Vue 3
function warnDeprecatedUsage() {
    const instance = vue.getCurrentInstance();
    const parentName = instance.parent && instance.parent.type.name;
.....

TypeError: Cannot read property 'parent' of null

--------------------------------------------------------------------------------------------------------------------

const RouterLinkImpl =
.....
setup(props, { slots, attrs }) {
        const link = vue.reactive(useLink(props));
        const { options } = vue.inject(routerKey);

 Cannot destructure property 'options' of 'vue.inject(...)' as it is undefined.

**Comment by posva** [comment]
I can't check anything without a repro: https://new-issue.vuejs.org/?repo=vuejs/vue-router-next#why-repro
