### ISSUE TITLE
Feature request: replace routes dynamically 

### ISSUE THREAD

**Issue by 57code** [vuejs/vue-router-next#630]
### What problem does this feature solve?
How to delete routes dynamically，For a detailed description, see the issue below：
https://github.com/vuejs/vue-router/issues/1234

### What does the proposed API look like?
router.replaceRoutes([/* routes */]) 
or
router.reset([])

**Comment by posva** [comment]
https://next.router.vuejs.org/guide/advanced/dynamic-routing.html
