### ISSUE TITLE
Documentation duplicates sections at sidebar

### ISSUE THREAD

**Issue by Rukomoynikov** [vuejs/vue-router-next#640]
### Version
4.0.1

### Reproduction link
[https://next.router.vuejs.org/guide/](https://next.router.vuejs.org/guide/)

### Steps to reproduce
1. Open https://next.router.vuejs.org/guide/
2. On the left side for example you will see two Essentials sections, and other sections duplicated as well . 

### What is expected?
Sections are not duplicated.

### What is actually happening?
Might be a bug in Vitepress.

**Comment by Rukomoynikov** [comment]
How to reproduce:
1. Clone the repository
2. Build documentation - `yarn docs:build`
3. Serve docs via `vitepress serve docs`

Check the guide section.

**Comment by Rukomoynikov** [comment]
The issue has not reproduced at previous version of VitePress. I'm closing. Sorry.

**Comment by posva** [comment]
It is a problem, could be in vitepress but still weird

**Comment by posva** [comment]
I'm rolling back to have a correct version on vue router docs. This bug can be tracked at https://github.com/vuejs/vitepress/issues/177
