### ISSUE TITLE
exports is not defined

### ISSUE THREAD

**Issue by zhanfenghai** [vuejs/vue-router-next#641]
I got an error  when i use the latest version of vue-router with vite。it seems like below
![image](https://user-images.githubusercontent.com/18130809/101565107-5a5a9500-3a07-11eb-99ed-d874a3b76270.png)
my code
![image](https://user-images.githubusercontent.com/18130809/101565150-6c3c3800-3a07-11eb-8267-0cfc9bb0b829.png)

**Comment by chymz** [comment]
@zhanfenghai did you fix your issue ? Same problem here :(
