### ISSUE TITLE
Bring back addRoutes method

### ISSUE THREAD

**Issue by Mikilll94** [vuejs/vue-router-next#643]
### What problem does this feature solve?
In vue-router v3 there was a nice method `addRoutes`. It allowed to multiple routes at once. In vue-router v4 I have noticed that only `addRoute` method is present.

### What does the proposed API look like?
Bring back the `addRoutes` method from vue-router v3. This method was very convenient when adding multiple routes at once.

**Comment by LinusBorg** [comment]
Looping over an array of routes and call `addRoute` on each is a one-liner. I don't think this is reason to broaden the API

**Comment by posva** [comment]
I don't think it is worth broadening the API for this either

```js
router.addRoutes(routes)
// becomes
routes.forEach(route => router.addRoute(route)
```

**Comment by asasugar** [comment]
```ts
const addRoutes = (routes: IRoutes[], parentName = ''): void => {
  routes.forEach(item => {
    if (item.name && router.hasRoute(item.name)) return; // Do not re-add if a route with the specified name exists

    if (item.path && item.component) {
      const route = {
        path: item.path,
        redirect: item.redirect,
        name: item.name,
        component: dynamicImport(item.component),
        meta: item.meta
      };

      parentName ? router.addRoute(parentName, route) : router.addRoute(route);
      if (item.children && item.children.length) {
        addRoutes(item.children, item.name);
      }
    }
  });

  // Add 404 at the end of the route
  if (!router.hasRoute('NotFound')) {
    router.addRoute({
      name: 'NotFound',
      path: '/:pathMatch(.*)*',
      component: () => import('../views/error/error-404.vue')
    });
  }
};
```

**Comment by asasugar** [comment]
```ts
function dynamicImport(component: string) {
  const componentStr = component.replace(/^\/+/, ''),
    componentPath = componentStr.replace(/\.\w+$/, '');
  return () => import('../' + componentPath + '.vue');
}
```

**Comment by mryellow** [comment]
When navigation route `next()` is called in an async manner, each time `addRoute` is called `beforeEach` navigation routes run.

This causes `beforeEach` to run multiple times with incorrect state.

Whereas via `addRoutes`, `beforeEach` is only called after they're all added.

See https://github.com/vuestorefront/vue-storefront/issues/3442
