### ISSUE TITLE
<router-link> tag prop not working

### ISSUE THREAD

**Issue by hellfreezes** [vuejs/vue-router-next#648]
### Version
4.0.1

### Reproduction link
[https://jsfiddle.net/4o1xpqwf/](https://jsfiddle.net/4o1xpqwf/)

### Steps to reproduce
I need to render "router-link" as an "li" tag. So I pass a tag property equal "li" (I also try "div", "span" and "button" - it's does't matter). Just like here: https://router.vuejs.org/api/#tag

### What is expected?
router-link to render as a "li" DOM element

### What is actually happening?
It's render as an "a" DOM element with prop "tag=li" and empty "class"

**Comment by posva** [comment]
https://next.router.vuejs.org/guide/migration/index.html#removal-of-event-and-tag-props-in-router-link
