### ISSUE TITLE
Router access Feature 

### ISSUE THREAD

**Issue by imohuan** [vuejs/vue-router-next#649]
### Version
4.0.1

### Reproduction link
[https://codesandbox.io/s/nervous-architecture-m4ldf](https://codesandbox.io/s/nervous-architecture-m4ldf)

### Steps to reproduce
# Use `vue3   typescript   vuerouter4` 

## 1. Open dynamic routing directly and report an error

``` javascript
Uncaught SyntaxError: Unexpected token '<'
app.js:1 Uncaught SyntaxError: Unexpected token '<'
hm.baidu.com/hm.gif?si=3b231847743b9335bfaccda43a1abc1b&et=0&nv=0&st=4&v=pixel-1.0&rnd=1476081111:1 GET https://hm.baidu.com/hm.gif?si=3b231847743b9335bfaccda43a1abc1b&et=0&nv=0&st=4&v=pixel-1.0&rnd=1476081111 net::ERR_BLOCKED_BY_CLIENT
Image (async)
(anonymous) @ hm.js:14
(anonymous) @ hm.js:15
manifest.json:1 Manifest: Line: 1, column: 1, Syntax error.
```

##  2. `savedPosition` always Null

``` javascript
const router = createRouter({
  scrollBehavior(to, from, savedPosition) {
    // savedPosition is null
    return { top: 0 }
  },
})
```

## 3. `vue-router => dynamic router` 
# Watch is listening for an error

### What is expected?
1. You can go back to the previous scrolling height when switching routes

2. Can go back to the original state when refreshing dynamic routing

### What is actually happening?
1. savedPosition obtained is always null

2. Refresh dynamic routing directly reports an error

---
fighter

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

https://next.router.vuejs.org/guide/advanced/scroll-behavior.html should help
