### ISSUE TITLE
路由切换 导致页面卡死 或是 崩溃

### ISSUE THREAD

**Issue by Bo-LiangD** [vuejs/vue-router-next#660]
### Version
4.0.1

### Reproduction link
[https://gitee.com/boliangd/demo.git](https://gitee.com/boliangd/demo.git)

### Steps to reproduce
技术采用 vue3.0.x vuex4.0.x vue-router4.0.x element-plus1.0.x 
项目安装跑起来以后  点击左侧菜单栏  然后就莫名卡着了   使用 vue2.x 系列 没有问题
不知道 是我写错了 还是什么  比较迷惑......

### What is expected?
麻烦收到 运行一下Demo 看一下 这个问题 什么情况

### What is actually happening?
路由切换 页面卡死

**Comment by posva** [comment]
Open issues in English, thank you

**Comment by Bo-LiangD** [comment]
Oh, I forgot. sorry
