### ISSUE TITLE
spread operator in esm-bundler

### ISSUE THREAD

**Issue by MashiroWang** [vuejs/vue-router-next#670]
### Version
4.0.1

### Reproduction link
[https://cdn.bootcdn.net/ajax/libs/vue-router/4.0.1/vue-router.esm-bundler.js](https://cdn.bootcdn.net/ajax/libs/vue-router/4.0.1/vue-router.esm-bundler.js)

### Steps to reproduce
execute line 2395 made page crash

![image](https://user-images.githubusercontent.com/10394160/102870427-f78de280-4477-11eb-9417-30756dddb18e.png)

### What is expected?
page not crash

### What is actually happening?
page crash

---
esm-bundle should not appear es6 syntax

**Comment by posva** [comment]
Nice catch! This one is easy to fix: it needs to use the `assign` function exported from `utils`. This is a good first contribution, no test needed
