### ISSUE TITLE
Docs: a link in useRouter api redirects to wrong path

### ISSUE THREAD

**Issue by boussadjra** [vuejs/vue-router-next#671]
### Version
4.0.1

### Reproduction link
[https://next.router.vuejs.org/api/#userouter](https://next.router.vuejs.org/api/#userouter)

### Steps to reproduce
when visiting https://next.router.vuejs.org/api/#userouter we read 

>Returns the **router** instance. Equivalent to using `$router` inside templates. Must be called inside of `setup()`.

the bold router word it's an anchor that when we click on it prints `https://next.router.vuejs.org/api/#Router` in the browser address field and it doesn't redirects to any page, but if we focus in the url field and we enter that link we will be redirected to `https://next.router.vuejs.org/api/#useroute`

### What is expected?
it's expected to redirect to `https://next.router.vuejs.org/api/#router-properties`

### What is actually happening?
it redirects to `https://next.router.vuejs.org/api/#useroute`

**Comment by posva** [comment]
Thanks! The actual link should be https://next.router.vuejs.org/api/#router-properties
