### ISSUE TITLE
I wanted to use 'addroutes()', but found that it has been replaced by 'addroute()'

### ISSUE THREAD

**Issue by helloWork996** [vuejs/vue-router-next#676]
### What problem does this feature solve?
Before 4.0, I used to add routes that need permissions asynchronously through` addroutes()`, but now I can't do it through `addroute()`.

### What does the proposed API look like?
Can I keep addroutes()?

**Comment by posva** [comment]
Search addRoutes in existing issues and read the migration guide https://next.router.vuejs.org/guide/migration/index.html

**Comment by huedcode** [comment]
I haven't found it yet, but thank you

**Comment by posva** [comment]
https://github.com/vuejs/vue-router-next/issues?q=is%3Aissue+sort%3Aupdated-desc+addRoutes+is%3Aclosed

**Comment by huedcode** [comment]
routes.forEach(route => router.addRoute(route)

**Comment by huedcode** [comment]
Thank you. I solved my problem by using 
routes.forEach(route => router.addRoute(route) and vuex
