### ISSUE TITLE
Custom regex leaks to subsequent parameters without regex

### ISSUE THREAD

**Issue by dneuschaefer-rube** [vuejs/vue-router-next#679]
### Version
4.0.1

### Reproduction link
[https://paths.esm.dev/?p=AAMeJbiAwB4U7BTA0AGBCQmoAEUduADagKA.#](https://paths.esm.dev/?p=AAMeJbiAwB4U7BTA0AGBCQmoAEUduADagKA.#)

### Steps to reproduce
Define a path with two parameters, the first using a custom a regex and the second without.

### What is expected?
The regex is applied only for the first parameter, the second parameter uses the default regex.

### What is actually happening?
The custom regex is applied to both parameters.

**Comment by posva** [comment]
Thanks!
