### ISSUE TITLE
addRoute dynamically

### ISSUE THREAD

**Issue by xama** [vuejs/vue-router-next#681]
### Version
4.0.2

### Reproduction link
[https://codesandbox.io/s/vue-router-4-reproduction-forked-7le5c?file=/index.html](https://codesandbox.io/s/vue-router-4-reproduction-forked-7le5c?file=/index.html)

### Steps to reproduce
Hi I'm trying to add a new route using the method addRoute on this.$routes but nothing happened. 

thanks for help

### What is expected?
New menu item called Real appears after the other items

### What is actually happening?
nothing added

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

It's ` this.$router.addRoute({ path: '/real', component: Real })` (no array)
