### ISSUE TITLE
Per component  postRouteUpdate route guard

### ISSUE THREAD

**Issue by shoukunhuai** [vuejs/vue-router-next#683]
### What problem does this feature solve?
I'm writing a mixin to persist(or two way binding) component data(part of) into URL query, like kibana did.
When handle browser forward/backward, i realise i need another hook: afterRouteUpdate. I use timeout at present, but i think it will be nice to have a hook like this.

Let me explain why.

My little plugin will
- Action 1: push a new route with encoded query(the same component, but different query) when watched property changed, and
- Action 2: decode query from route and set property if necessary when browser go backward/forward

But the action 2 will trigger a property change and push a new route(action 1) which will erase the browser history(forward direction). So if we can set property when the route has been updated in action 2, then we can do a compare to avoid route push, as the value will always be the same.

I'm not sure if there is already a similar well known plugin, so i decide to create it, and let me know if there is one.

[1] Here is my plugin https://github.com/shoukunhuai/vue-router-state-mixin

### What does the proposed API look like?
```js
afterRouteUpdate(to: Route, from: Route)
```

**Comment by posva** [comment]
Use a watcher on the route inside of the component.

Note that guards in mixins are not supported: https://github.com/vuejs/vue-router-next/issues/454

**Comment by shoukunhuai** [comment]
Thanks for your advise, i tried watch `$route`, it works well.
Also this brings another benefit, components will not have to do state check, the plugin will do itself.
