### ISSUE TITLE
Can't use onBeforeRouteUpdate in Single File Components

### ISSUE THREAD

**Issue by dapperdanman1400** [vuejs/vue-router-next#684]
### Version
4.0.2

### Reproduction link
[https://codesandbox.io/s/quiet-darkness-ocx3u?fontsize=14&hidenavigation=1&theme=dark&file=/src/App.vue](https://codesandbox.io/s/quiet-darkness-ocx3u?fontsize=14&hidenavigation=1&theme=dark&file=/src/App.vue)

### Steps to reproduce
Use the `onBeforeRouteUpdate` function from `vue-router` within the `setup` of a Single File Component

### What is expected?
`onBeforeRouteUpdate` should function normally, performing the callback function when the route updates.

### What is actually happening?
Vue Router throws the following error.
`[Vue Router warn]: onBeforeRouteUpdate must be called at the top of a setup function`

**Comment by posva** [comment]
The message was updated in the latest release to be a bit more specific, this gave me an idea to improve it a bit more! `onBeforeRouteUpdate` is meant to be used inside of a view component or any descendant like `beforeRouteUpdate`.

**Comment by qshjd** [comment]
I have the same problem, so what is the current solution? Any demo
