### ISSUE TITLE
Base tag in head not ignored if parameter to createWebHashHistory is passed

### ISSUE THREAD

**Issue by vitchioto** [vuejs/vue-router-next#685]
### Version
4.0.2

### Reproduction link
[https://github.com/vitchioto/vue3-test](https://github.com/vitchioto/vue3-test)

### Steps to reproduce
1. Build the application
2. Deploy it to a sub-folder of a domain (might need to update publicPath in vue.config.js)
3. Open the subfolder in a browser

### What is expected?
Path in the address bar stays as it is (only with added #/ in the end of the address).

You can see it here: https://test.vladovic.sk/router/

### What is actually happening?
Path in address bar and urls of router links are changed to root (value of base tag)

You can see it here: https://test.vladovic.sk/router-bug/

---
The only difference between those 2 pages is this line:

https://github.com/vitchioto/vue3-test/blob/master/public/index.html#L9

Although, according to documentation, base tag in head should be ignored if parameter is passed to createWebHashHistory (https://next.router.vuejs.org/api/#createwebhashhistory).

**Comment by posva** [comment]
Updated the documentation: the base tag needs to have an appropriate value because it's taken into account by `history.pushState`. In your case, it should have `/router-bug/`

**Comment by vitchioto** [comment]
Hi @posva, thanks for your reply :)

do you know, if there is any workaround?

the problem I have is, that I am just "injecting" Vue app into existing page handled by our corporate CMS. So I am not touching _header_ / _footer_, only _main_ part in between them. Hence, updating value of _base_ tag is not an option for me :/

when I use Vue 2 with (older version of) router, it works as I expected, though...

demo page: https://test.vladovic.sk/router-v2/
git repo: https://github.com/vitchioto/vue2-test

thanks in advance :)

**Comment by posva** [comment]
It used to work because the hash history implementation was different but now that it relies on the HTML5 history to provide many more features.

I realized there is a way to support by checking the existence of the `<base>` element and pushed a fix
