### ISSUE TITLE
set routes with children,  but occurred : TypeError: Failed to fetch dynamically imported module: http://localhost:3000/src/views/assets/Posts.vue

### ISSUE THREAD

**Issue by little3201** [vuejs/vue-router-next#686]
### Version
4.0.2

### Reproduction link
[https://github.com/little3201/abeille-manager](https://github.com/little3201/abeille-manager)

### Steps to reproduce
1. set routes and import it in main.ts
2. yarn dev
3. click Posts or others

### What is expected?
show Posts.vue view

### What is actually happening?
 TypeError: Failed to fetch dynamically imported module: http://localhost:3000/src/views/assets/Posts.vue

**Comment by posva** [comment]
Read https://new-issue.vuejs.org/?repo=vuejs/vue-router-next#why-repro

**Comment by little3201** [comment]
this error i fixed ,  i set a error location when i use some components
