### ISSUE TITLE
There's no `Route` type or interface to use in a custom props function

### ISSUE THREAD

**Issue by TheDutchCoder** [vuejs/vue-router-next#696]
### Version
4.0.2

### Reproduction link
[https://codesandbox.io/s/cold-smoke-nmh9m](https://codesandbox.io/s/cold-smoke-nmh9m)

### Steps to reproduce
When using a function for passing props to routes, there's a `route` prop passed, but there's no type that can be imported and used.

A workaround is creating a custom interface, but that's not right obviously.

Example:
```js
      props: (route: Route) => ({ // this type/interface doesn't exist and needs to be created manually
        params: route.params,
        label: 'Pending',
        filter: { key: 'status', value: 'new_pending' },
      }),
```

### What is expected?
A Route type to be exposed

### What is actually happening?
There's no Route type (or something similar)

---
Posva mentioned using `Route` on Discord, but it simply doesn't exist. Maybe there's a different interface that can be used? But I haven't been successful in finding one.

**Comment by posva** [comment]
Route was in Vue Router 3. It's RouteLocationNormalized on v4

**Comment by TheDutchCoder** [comment]
Ahhhhhh, thanks!
