### ISSUE TITLE
"/:pathMatch()" seems not to work when regex contains group

### ISSUE THREAD

**Issue by shqyking** [vuejs/vue-router-next#697]
### Version
4.0.2

### Reproduction link
[https://jsfiddle.net/b69otxkj/1/](https://jsfiddle.net/b69otxkj/1/)

### Steps to reproduce
Go to the minimal reproduction page and click run. Open console.

### What is expected?
Can correctly parse below regex:

^(?!saml.*$).*

### What is actually happening?
In console, you can see error

vue-router@next:879 Uncaught Error: Invalid custom RegExp for param "pathMatch" (^(?!saml.*): Invalid regular expression: /(^(?!saml.*)/: Unterminated group
    at tokensToParser (vue-router@next:879)
    at createRouteRecordMatcher (vue-router@next:1185)
    at addRoute (vue-router@next:1273)
    at vue-router@next:1423
    at Array.forEach (<anonymous>)
    at createRouterMatcher (vue-router@next:1423)
    at createRouter (vue-router@next:2654)
    at ?editor_console=true:167

---
What I would like to achieve is to catch any no-matching URL except whose starting with "saml", and redirect to 404. But it cannot correctly parse my regex. Looking at the error message, seems the extract regex is missing anything after the first closing parenthesis.

**Comment by posva** [comment]
You can use the [path ranker](https://paths.esm.dev/?p=AAMeJbiAwQEFDBbAkAWNQQoQH0yEgDoDLcA2gNABQAWADlaUFNAAEA..#) to test out the generation. I also added what seems to be what you want to do. If you try the regex you were trying you will see what RegExp is Vue Router trying to create and why it fails: the closing `)` has to be escapeed inside custom regexp

**Comment by takhello** [comment]
A bad design
