### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'created' of undefined

### ISSUE THREAD

**Issue by nikky-kajavadara** [vuejs/vue-router-next#698]
### Version
4.0.0

### Steps to reproduce
route.js

import { createRouter, createWebHistory } from "vue-router";

const routes = [
  {
    path: "/",
    redirect: "/dashboard",
    component: () => import("@/view/layout/Layout.vue"),
    children: [
      {
        path: "/dashboard",
        name: "dashboard",
        component: () => import("@/view/pages/Dashboard.vue"),
      }
    ],
  },
  {
    path: "/",
    component: () => import("@/view/pages/auth/login_pages/Login-1"),
    children: [
      {
        name: "login",
        path: "/login",
        component: () => import("@/view/pages/auth/login_pages/Login-1"),
      },
      {
        name: "register",
        path: "/register",
        component: () => import("@/view/pages/auth/login_pages/Login-1"),
      },
    ],
  },
  {
    path: "/(.*)",
    redirect: "/404",
  },
  {
    // the 404 route, when none of the above matches
    path: "/404",
    name: "404",
    component: () => import("@/view/pages/error/Error-1.vue"),
  },
];

const router = createRouter({
  history: createWebHistory(process.env.BASE_URL),
  routes,
});

export default router;

main.js file

import { createApp } from "vue";
import App from "./App.vue";
import "./registerServiceWorker";
import router from "./router.js";
import store from "./core/services/store/index.js";
import axios from "axios";
import VueAxios from "vue-axios";

const app = createApp(App);
app.use(store);
app.use(VueAxios, axios);
app.use(router);
app.mount("#app");

I set these two files in my project but it's given an error.

### What is expected?
run dashboard.vue file

### What is actually happening?
error on dashboard route and empty page is shown

---
give me some guidelines to use new syntax in vue3

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

Please, also read this https://new-issue.vuejs.org/?repo=vuejs/vue-router-next#why-repro
