### ISSUE TITLE
router instance should expose history

### ISSUE THREAD

**Issue by liuweiGL** [vuejs/vue-router-next#699]
### What problem does this feature solve?
I have a plugin for vue-router and the api likes:
```
import VueRouterPlugin from 'vue-router-plugin'

createApp(App).use(VueRouterPlugin, { router }).mount('#app')
```
And i want to read some informations like `position` `pageScroll` etc.

The problem is that i can't access history from the router, and i don't think i should use `window.history` directly.

### What does the proposed API look like?
router.history or useHistory?

**Comment by posva** [comment]
You can still get the history as an argument like the router.
The history is intentionally not exposed to prevent wrong usage
What is the actual use case?

**Comment by liuweiGL** [comment]
1. That is ugly
> You can still get the history as an argument like the router

2. The history is user pass to router, i don't think this is tenable
> The history is intentionally not exposed to prevent wrong usage

3. I want to maintain history records to a stack so that i can simulate mobile router,  `history.listen` and `history.state.position` is important.

**Comment by posva** [comment]
You can instead create a new history instance that uses one of the `createHistory()` functions exposed by vue router and let the user pass that history instance to router instance.

```js
function createCustomHistory(base) {
  const history = createWebHistory(base)
  // extend history
return history
}
```

**Comment by liuweiGL** [comment]
I'll try.
