### ISSUE TITLE
access to root Vue instance

### ISSUE THREAD

**Issue by ludanxer** [vuejs/vue-router-next#700]
### Version
4.0.2

### Reproduction link
[https://jsfiddle.net/ludanxer/gy9m72xf/1/](https://jsfiddle.net/ludanxer/gy9m72xf/1/)

### Steps to reproduce
``` js
router.beforeEach((to, from) => {
  console.log(router.app)
})
```

### What is expected?
To be able to access root Vue instance via `router.app`. Or document the breaking change if it's expected.

### What is actually happening?
`router.app` undefined

---
I add firebase as a global vue property for authentication, but I can't seem to access it inside router.

**Comment by posva** [comment]
Vue Router can be installed in multiple Vue apps, so having `app` could be misleading while having an array of `app` seems overly complicated. However, this can be added very easily:

```js
app.use(router)
router.app = app
```

A PR to add this to the migration guide is welcome!
