### ISSUE TITLE
how to get current route component instance.

### ISSUE THREAD

**Issue by haishengXie0712** [vuejs/vue-router-next#711]
### What problem does this feature solve?
how to get current route component instance?

### What does the proposed API look like?
https://265sb.csb.app/#/

**Comment by posva** [comment]
```vue
<router-view v-slot="{ Component }">
    <component :is="Component" ref="componentInstance" />
  </router-view>
```

**Comment by ZongYan30** [comment]
hello,I tried it,  but ref still does not work。

`
<template>
  <div class="container">
    <router-link to="/" activeClass="active">首页</router-link>
    <router-link to="/about" exactActiveClass="active">关于</router-link>
    <router-link to="/about/team" activeClass="active">团队</router-link>

    <router-view v-slot="{ Component }">
      <Transition>
        <KeepAlive include="About">
          <component :is="Component" ref="compRef" />
        </KeepAlive>
      </Transition>
    </router-view>
  </div>
</template>

<script setup>
import { ref, onMounted, nextTick } from "vue";
//
const compRef = ref();

onMounted(async () => {
  console.log(compRef.value);
});
</script>
`

result:

![Image](https://github.com/user-attachments/assets/04cbeccb-3495-4ce7-b681-86f3482c842c)
