### ISSUE TITLE
Custom router-link create nested "a" tag

### ISSUE THREAD

**Issue by fabien-ml** [vuejs/vue-router-next#713]
### Version
4.0.3

### Reproduction link
[https://codesandbox.io/s/currying-browser-eupn0?file=/src/App.vue](https://codesandbox.io/s/currying-browser-eupn0?file=/src/App.vue)

### Steps to reproduce
Create a custom router link component

### What is expected?
should render only one "a" tag

### What is actually happening?
It render two nested "a" tag

**Comment by posva** [comment]
You're overriding it with `v-bind`, do

```vue
<router-link v-bind="$props" custom v-slot="{ href, navigate }">
```
