### ISSUE TITLE
How to use <KeepAlive> in <RouterView>?

### ISSUE THREAD

**Issue by wtto00** [vuejs/vue-router-next#716]
### Version
4.0.0

### Reproduction link
[https://codesandbox.io/s/competent-lamport-ycfcj?file=/src/App.jsx](https://codesandbox.io/s/competent-lamport-ycfcj?file=/src/App.jsx)

### Steps to reproduce

```jsx
// App.jsx
import { defineComponent, KeepAlive } from 'vue';
import { RouterView } from 'vue-router';

export default defineComponent({
  render() {
    return <KeepAlive>
        <RouterView></RouterView>
      </KeepAlive>;
  },
});
```

### What is expected?
remove the console warning, and use jsx in render function.

### What is actually happening?
There is a console warning:
```
[Vue Router warn]: <router-view> can no longer be used directly inside <transition> or <keep-alive>.
Use slot props instead:

<router-view v-slot="{ Component }">
  <keep-alive>
    <component :is="Component" />
  </keep-alive>
</router-view> 
```

---
I googled a lot about this, but there is no solution if I use jsx in render function

**Comment by LinusBorg** [comment]
the error message tells you what to do. All you need to know is how to use JSX with render functions/JSX, which is not something vue-router covers.

```jsx
<router-view>
  ({ Component }) => (
    <keep-alive>
      <Component />
    </keep-alive>
  )
</router-view>
```

Please use chat.vuejs.org to ask the community for help if you have trouble with it.
