### ISSUE TITLE
exact prop can not work on <router-link>

### ISSUE THREAD

**Issue by lipengzhou** [vuejs/vue-router-next#717]
### Version
4.0.3

### Reproduction link
[http://localhost:8080/#/editor](http://localhost:8080/#/editor)

### Steps to reproduce

![image](https://user-images.githubusercontent.com/23165266/104699894-58929880-574e-11eb-83d3-bf78d4548d77.png)

### What is expected?
exact prop can not work on <router-link>

### What is actually happening?
exact prop can not work on <router-link>

**Comment by posva** [comment]
https://next.router.vuejs.org/guide/migration/index.html#removal-of-the-exact-prop-in-router-link
