### ISSUE TITLE
Behavior difference when history state changes before app initialization

### ISSUE THREAD

**Issue by wrobbinz** [vuejs/vue-router-next#718]
### Version
4.0.3

### Reproduction link
[https://codesandbox.io/s/boring-sanderson-osiz5](https://codesandbox.io/s/boring-sanderson-osiz5)

### Steps to reproduce
Below are two near-identical apps. (only difference should be vue/vue-router versions and corresponding API changes necessary)

Before Vue is initialized, a `window.history.replaceState` is called in order to set an initial route.

vue 2 / vue-router: https://codesandbox.io/s/confident-microservice-kknmz
vue 3 / vue-router-next: https://codesandbox.io/s/boring-sanderson-osiz5

1. Load the page at the index `<domain>.app`

### What is expected?
The user should land on the `/goodbye` route. (this happens correctly in the vue2 sandbox)

### What is actually happening?
With vue-router-next, the user lands on the index `/` route.

---
I have console.logged for some insight here. Specifically logging:

- before Vue is started.
- After Vue is started.
- During each `router.beforeEach`

Note in the console the differing results.

Context: I am implementing auth0 authentication and I want to change the URL back to what it was when the app was redirected to auth0's universal login. This replaceState logic is running before Vue is initialized so that Vue doesn't flash a rendered route before going to the correct route.

**Comment by posva** [comment]
You need to move `history.replaceState()` of history before

```js
const router = createRouter({
  history: createWebHistory(),
  routes
});
```

Or delay the router + history creation after that with a function.

While the router is running the user should not manually call `history.pushState()` to avoid things getting out of sync and with the new api the router starts earlier so the call has to be moved earlier as well
