### ISSUE TITLE
vue router issue with vite - ` Error: Couldn't resolve component "default" at "/notFound"`

### ISSUE THREAD

**Issue by ShenQingchuan** [vuejs/vue-router-next#719]
### Version
4.0.3

### Reproduction link
[https://github.com/ShenQingchuan/vite-vuerouter-issue-repo](https://github.com/ShenQingchuan/vite-vuerouter-issue-repo)

### Steps to reproduce
Please see my reproduction repo: https://github.com/ShenQingchuan/vite-vuerouter-issue-repo
1. install dependencies with yarn/npm
2. yarn dev
3. type some unknown URL path just like "http://localhost:3000/xxxyyyzzz", anything not involved in `src/router.ts`
4. open Chrome DevTools --> go to `Console` Tab
5. you can see a warning: `vue-router.a68108b7.js:73 [Vue Router warn]: Unexpected error when starting the router: Error: Couldn't resolve component "default" at "/notFound" at vue-router.a68108b7.js:1982`

### What is expected?
expect the error path should redirect to `/notFound`

### What is actually happening?
From the information in Chrome DevTools `Network` panel, 
the `not-found.vue` is actually loaded, but the component seems can not be rendered...

**Comment by posva** [comment]
Can you remove everything that isn't related from the repro like ant design and ts so I can take a look?

**Comment by ShenQingchuan** [comment]
> Can you remove everything that isn't related from the repro like ant design and ts so I can take a look?

It doesn't seem make sense... my `login.vue` page runs just fine... but the `not-found.vue` page isn't...
Nothing matters with `ant design` I think?

**Comment by posva** [comment]
Please read https://new-issue.vuejs.org/?repo=vuejs/vue-router-next#why-repro to understand why I ask for this and open a new issue if the issue still exists without ant design, ts, store or anything unrelated
