### ISSUE TITLE
BeforeRouteEnter event not called for async loaded components

### ISSUE THREAD

**Issue by websmurf** [vuejs/vue-router-next#739]
### Version
4.0.3

### Reproduction link
[https://github.com/websmurf/vue-router-async-test](https://github.com/websmurf/vue-router-async-test)

### Steps to reproduce
Run the provided application in the test repository, and make sure your console is open.

If you click the "Page 1" link, the console shows "Page 1"
If you click the "Page 2" link, the console shows "Page 2"
If you click the "Async Page 1" link, the console shows nothing
If you click the "Async Page 2" link, the console shows nothing

Now, click the Async Page 1 link again, now the console shows 'Async page 2'
Also, when directly visiting the async pages, no beforeRouteEnter event is triggered.

### What is expected?
I would expect the beforeRouteEnter method to be called in every of these cases.

### What is actually happening?
The beforeRouteEnter method is only called for the sync loaded components. Only once the page is loaded once, the beforeRouteEnter method is called

---
We are in the process of migration our old Vue2 application to Vue3 and Vite, hence the usage of vue-class-component (since we use it already and it means converting lesser code).

Not sure if this is actually caused by vue-router; or by vue-class-component; will adjust the example to include a Composition API set as well.

**Comment by websmurf** [comment]
Oki, added a composition api component and it's working instantly there as well; 
That means this issue is most likely caused by vue-class-component I guess?

**Comment by posva** [comment]
@ktsn do I need to update anything at https://github.com/vuejs/vue-router-next/blob/b17be855fa6e1212583cb4844439cfc447247592/src/navigationGuards.ts#L285 ?

**Comment by ygj6** [comment]
Hi @posva , I have submitted a PR to fix this issue https://github.com/vuejs/vue-router-next/pull/743
Will you help to review it?

**Comment by websmurf** [comment]
@posva do you have any indication about a next release of vue-router-next? This is the last issue before I can launch my updated codebase :-)

**Comment by posva** [comment]
Likely next week. You can use a local package patch until then
