### ISSUE TITLE
<router-link> does not provide a way to interact with the created anchor

### ISSUE THREAD

**Issue by andrei-gheorghiu** [vuejs/vue-router-next#740]
### Version
4.0.3

### Reproduction link
[https://codesandbox.io/s/sleepy-cloud-o88oc?file=/src/App.vue](https://codesandbox.io/s/sleepy-cloud-o88oc?file=/src/App.vue)

### Steps to reproduce
Just run the sandbox.

### What is expected?
I'm expecting router link to provide me a method in which to interact with the resulting anchor tag. 

### What is actually happening?
Your documentation led me to believe if I placed an anchor inside the `<router-link>` and used `v-slot`, my content will be used as markup. 
Unfortunately, my content gets wrapped in an anchor, even if itself is an anchor.

---
I ran into this while trying to provide my own logic for active class. I was hoping there was some way to pass my own function to the router-link and tell it when it's active, when it's an active child, etc...

---
I know I could use workarounds such as to give the wrapping anchor `display: contents; ` but it's not cross/browser cross/device. Besides, ultimately, nesting anchors is illegal HTML. It's also quite bad for screen readers. So my only option here would be not to use `<router-link>` at all, which you advise against throughout your docs.

**Comment by posva** [comment]
You need to pass `custom` to remove the wrapping `a`: https://next.router.vuejs.org/api/#router-link-s-v-slot
