### ISSUE TITLE
The parent menu item doesn't have router-link-active class

### ISSUE THREAD

**Issue by dmitrystas** [vuejs/vue-router-next#752]
### Version
4.0.3

### Reproduction link
[https://codesandbox.io/s/ozh3y](https://codesandbox.io/s/ozh3y)

### Steps to reproduce
1. Go to sandbox https://codesandbox.io/s/ozh3y
2. Click to 'About Child' menu item

### What is expected?
The 'About' menu item should have 'router-link-active' class since this menu item is the parent item for 'About Child'

### What is actually happening?
The 'About' menu item does not have 'router-link-active' class 

---
Screenshot also shows the problem https://prnt.sc/y0hgcv

**Comment by posva** [comment]
This is an intended change. See https://next.router.vuejs.org/guide/migration/index.html#removal-of-the-exact-prop-in-router-link and the linked RFC at the bottom of the section
