### ISSUE TITLE
router-view content no change

### ISSUE THREAD

**Issue by liuqian1996** [vuejs/vue-router-next#753]
### Version
4.0.3

### Reproduction link
[https://codesandbox.io/s/test-vue3-router-l8hjh?file=/src/main.js](https://codesandbox.io/s/test-vue3-router-l8hjh?file=/src/main.js)

### Steps to reproduce
click link 'Go to Home'，should show 'Home' text，but not.

### What is expected?
click link 'Go to Home'，should show 'Home' text

### What is actually happening?
always show 'Router-View'

**Comment by posva** [comment]
Your reproduction isn't complete. It doesn't even run.
I still took a look and you should remove the line 11 in routerApp
See https://next.router.vuejs.org/guide/migration/index.html#passing-content-to-route-components-slot
