### ISSUE TITLE
Race-condition when setting query-params

### ISSUE THREAD

**Issue by chessydk** [vuejs/vue-router-next#756]
### Version
4.0.3

### Reproduction link
[https://codesandbox.io/s/wizardly-cohen-9md8b?file=/src/components/HelloWorld.vue](https://codesandbox.io/s/wizardly-cohen-9md8b?file=/src/components/HelloWorld.vue)

### Steps to reproduce
Go to the home route - it renders 5 HelloWorld components that each sets their part of the query. 

### What is expected?
That all the query-parameters that components set are present (?1=1&2=2&3=3&4=4&5=5)

### What is actually happening?
End result is that only the query part from the last component is present in query ((?5=5))

---
This is a breaking change compared to vue router 3 for Vue 2 where all query-parameters are set after run.

The first 4 push gives results like this: Error: Navigation cancelled from "/?5=5" to "/?1=1&5=5" with a new navigation. 

This page https://next.router.vuejs.org/guide/advanced/navigation-failures.html#detecting-navigation-failures  describes the cancel error (A new navigation took place before the current navigation could finish. e.g. router.push was called while waiting inside of a navigation guard.) but we don't have any navigation guards.

If this is intended new behaviour, how do we avoid it? - there's no way of knowing whether a route-change is ongoing and will be cancelled by issuing a push/replace when the change is not synchroneous. Maybe the issue could have special handling when the only change is in query-parameters

**Comment by posva** [comment]
It was only working on vue router 3 **if no guard was used** but now all navigations are asynchronous: https://next.router.vuejs.org/guide/migration/index.html#all-navigations-are-now-always-asynchronous so it doesn't matter. Now things are consistent, you will have to gather all changes to query and trigger them.

I have a sponsors only article that shows how to create reactive query params: https://onlysponsors.dev/@posva/reactive-query-params-that-just-work
At the end you can write the following code:

```js
const search = useQueryParam('search')
const color = useQueryParam('color', { format: v => v || null })
```

And use `search` and `color` as regular `ref`s

**Comment by chessydk** [comment]
Ok, thx. for responding. Although I'm aware you're doing a lot of good things for the Vue community (and really appreciate it), I hope you understand if I choose not to become a patrion just to get a look at your article (which I don't know whether will bring something new to my table). 120$ pr. year for me as a private person is way over the top - and paying once and then cancelling seems rude. If there were an option of paying you a small amount for just the article, that could work for me.
On the other hand I think it would be the best for Vue router, if all best practices were freely shared.
Best, Carsten

**Comment by posva** [comment]
> On the other hand I think it would be the best for Vue router, if all best practices were freely shared.

I agree that's what I do!

> If there were an option of paying you a small amount for just the article, that could work for me.

I guess you can sponsor me for one month... The idea is to help me live and keep working on open source not to pay me for content I create on top of the free software and documentation I've been providing for years. I hope that in the future, things change and open source developers don't have to give even more just to make a low tier salary. 
$10 for some consulting is an extremely low price and if you use this to earn a salary, $120/y is really nothing next to it (< 0.5% of a 35k yearly salary (entry-level salary in France) **after taxes**) and is still an extremely low price for consulting.

So you can sponsor me and then cancel, you won't get access to all the content I publish afterwards but you will be able to read what I've posted so far. I would still appreciate the donation
