### ISSUE TITLE
Setting "tag" attribute on router-link no longer seem to replace default <a>

### ISSUE THREAD

**Issue by uggli** [vuejs/vue-router-next#781]
### Version
4.0.4

### Reproduction link
[https://codesandbox.io/s/gallant-meadow-jgtoh?fontsize=14&hidenavigation=1&theme=dark](https://codesandbox.io/s/gallant-meadow-jgtoh?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
Letting Vue CLI create a default app for Vue 2 or Vue 3, the following content can be found:
```
<div id="nav">
    <router-link to="/">Home</router-link> |
    <router-link to="/about">About</router-link>
</div>
```
Replacing that section with the following (i.e. introducing "tag" attributes):
```
<div id="nav">
  <ul>
      <router-link to="/" tag="li">Home</router-link> |
      <router-link to="/about" tag="li">About</router-link>
  </ul>
</div>
```
The above modification works fine for Vue2, but with Vue3 the expected replacement of the default ```<a>``` tag with a ```<li>``` tag does no longer seem to happen.

### What is expected?
When doing this for Vue2, the code seem to cause a replacement of the default router-link ```<a>``` tag with the expected ```<li>``` tag, as described in the documentation.

### What is actually happening?
With the latest versions of Vue3 and vue-router, the expected replacement generated by the "tag" attribute does no longer seem to happen. The "tag" attribute is seen, but the default ```<a>``` tags unexpectedly remain. 

---
I did not spot any major relevant changes in the related documentation, but maybe I am missing something obvious here? Anyway, I tested using the "tag" attribute for both version 4.0.0 and 4.0.4, without success.

**Comment by LinusBorg** [comment]
https://next.router.vuejs.org/guide/migration/index.html#removal-of-event-and-tag-props-in-router-link
