### ISSUE TITLE
Doesn't work with ESM

### ISSUE THREAD

**Issue by Trojaner** [vuejs/vue-router-next#787]
### Version
4.0.4

### Reproduction link
[https://github.com/openmod/OpenMod.WebServer/tree/master/OpenMod.Dashboard/web](https://github.com/openmod/OpenMod.WebServer/tree/master/OpenMod.Dashboard/web)

### Steps to reproduce
1. Copy files to a web server (e.g. nginx)
2. Open site

### What is expected?
App should show and not generate an error

### What is actually happening?
```
vue.esm-browser.prod.js?module:1 TypeError: Cannot read property 'parent' of null
    at warnDeprecatedUsage (vue-router.esm.js?module:2152)
    at setup (vue-router.esm.js?module:2071)
    at kt (vue.esm-browser.prod.js?module:1)
    at vue.esm-browser.prod.js?module:1
    at vue.esm-browser.prod.js?module:1
    at B (vue.esm-browser.prod.js?module:1)
    at O (vue.esm-browser.prod.js?module:1)
    at b (vue.esm-browser.prod.js?module:1)
    at E (vue.esm-browser.prod.js?module:1)
    at T (vue.esm-browser.prod.js?module:1)
```
![](https://i.imgur.com/2nYCVBs.png)

---
Tested with es-module-shims and Chrome's own ESM implementation, both resulted in the same error

**Comment by posva** [comment]
Not sure if you are referring to this: https://github.com/vuejs/vue-router-next/issues/694.

Otherwise, please read https://new-issue.vuejs.org/?repo=vuejs/vue#why-repro

**Comment by Trojaner** [comment]
This is a different issue and unrelated to #694. I will try to create an online repro, but you can also use the repo I have linked.

**Comment by Trojaner** [comment]
Here is the repro, please reopen the issue: https://plnkr.co/edit/0TYlxtktHJ1MszrL
