### ISSUE TITLE
Doesn't work with ESM

### ISSUE THREAD

**Issue by Trojaner** [vuejs/vue-router-next#789]
### Version
4.0.4

### Reproduction link
[https://plnkr.co/edit/0TYlxtktHJ1MszrL](https://plnkr.co/edit/0TYlxtktHJ1MszrL)

### Steps to reproduce
1. Open repro link
2. Observe error in console

### What is expected?
App should show and not generate an error

### What is actually happening?
```
vue.esm-browser.prod.js?module:1 TypeError: Cannot read property 'parent' of null
    at warnDeprecatedUsage (vue-router.esm.js?module:2152)
    at setup (vue-router.esm.js?module:2071)
    at kt (vue.esm-browser.prod.js?module:1)
    at vue.esm-browser.prod.js?module:1
    at vue.esm-browser.prod.js?module:1
    at B (vue.esm-browser.prod.js?module:1)
    at O (vue.esm-browser.prod.js?module:1)
    at b (vue.esm-browser.prod.js?module:1)
    at E (vue.esm-browser.prod.js?module:1)
    at T (vue.esm-browser.prod.js?module:1)
```

Related code (instance is null here):
![](https://camo.githubusercontent.com/5419e225617951636c61d246551a5647cf143df22b1dee27b99716cc29697b24/68747470733a2f2f692e696d6775722e636f6d2f326e59435642732e706e67)

---
- Recreated #787 since it was missing online repro
- Tested with es-module-shims and Chrome's own ESM implementation, both resulted in the same error
- This is not related to #694

**Comment by posva** [comment]
It's `https://unpkg.com/vue-router@4.0.4/dist/vue-router.esm-browser.js`. The `esm` one is a leftover that hasn't been removed. Directly importing from `https://unpkg.com/vue-router@4.0.4/dist/vue-router.esm-browser.js?module` seems to correct the imports. Proposals are welcome at #694 

---

Regarding the other libraries you are using, remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!

**Comment by Trojaner** [comment]
Thank you
