### ISSUE TITLE
Scroll saved position doesn't work on router view with a key

### ISSUE THREAD

**Issue by lukef** [vuejs/vue-router-next#804]
### Version
4.0.4

### Reproduction link
[https://jsfiddle.net/7uef8wp4/4/](https://jsfiddle.net/7uef8wp4/4/)

### Steps to reproduce
1. Assign a `:key="$route.path"` to your `<router-view>` element
2. Navigate to a page and scroll to a "non-zero" position
3. Navigate to a different page
4. Press the back button on your browser

### What is expected?
The saved scroll position should be restored.

### What is actually happening?
If you create a `router-view` with a `key` attribute (I'm using it because I re-use a component for dynamic routes) then when pressing back, the saved scroll position will not be restored.

**Comment by lukef** [comment]
As a follow-up: Is this a bi-product of just reusing the component? I tried adding a `key` to the top level of the reused route component, then removed the `<router-view>` key value and it has the same result. 

It seems to work fine for all other routes where they have specific components.

**Comment by posva** [comment]
You need to add a `scrollBehavior` function for it to work: https://next.router.vuejs.org/guide/advanced/scroll-behavior.html#scroll-behavior

**Comment by lukef** [comment]
Sorry, I left it off the jsfiddle. I have a scrollBehavior function and it still does not work. I'll add it to the fiddle.

Is it expected that if the same component is being used then the scroll position will reset regardless? I tried digging into the code but is couldn't see where it's being captured. 

Also, I tried implementing a custom scrollBehavior to try something else out and saw that (in my case) that the position wasn't being set unless I clicked the link a *second* time.

**Comment by lukef** [comment]
Forget it. This is a timing issue actually. The content loads in after the scroll position is set (<100ms gap) so it looks like it's being eaten. 

I'll have to work on a solution to store the position so I can restore it when the page has fully loaded.

**Comment by posva** [comment]
You can return a promise too, no need to store the scroll position yourself!

**Comment by lukef** [comment]
In this particular case I want to wait for a callback in the component before setting it. Something like:

```
<MyComponent @loaded="onLoaded" />
```

Then:

```
onLoaded() {
  // restore scroll position
}
```

My initial (rough) implementation is to store the scroll position returned in `scrollBehavior` and the just reuse it later. I then also clear the values when `savedPosition` is `null`. It seems to work pretty well but if you have better ideas then i'm all for it :)

It would be nice if there was a way to retrieve it for use later, but it could be pretty complicated I am guessing without looking into it.
