### ISSUE TITLE
Vuerouter will cause cross domain problems in individual browsers, but it will no longer affect the operation after packaging

### ISSUE THREAD

**Issue by ht-sauce** [vuejs/vue-router-next#821]
### Version
4.0.5

### Steps to reproduce
At present, in the mobile terminal, baidu browser app will change

1. Create a vue3 project arbitrarily, after NPM run serve

2. In the mobile phone Baidu browser app access, page blank

3. Add capture error code

Get row and column 0, error null, script error

### What is expected?
normal operation

### What is actually happening?
Page blank, nothing to access

**Comment by posva** [comment]
Please read and follow https://new-issue.vuejs.org/?repo=vuejs/vue-router-next#why-repro
