### ISSUE TITLE
Calling `window.history.pushState` should trigger SPA navigation for testing purposes

### ISSUE THREAD

**Issue by maximedupre** [vuejs/vue-router-next#822]
### What problem does this feature solve?
When testing (with Cypress, for example), all you can do is trigger a full page reload (e.g. `cy.visit`). In order to test a real SPA navigation scenario, you have access to 'window.history'.

Currently, calling `window.history.pushState, window.history.replaceState` changes the URL, but does not trigger in-app navigation.

If changing the history manually is not the right thing to do, then there should probably be something that allows testing SPA navigation without stubbing the router (which would be needlessly complex).

Thanks!

### What does the proposed API look like?
My proposal does not change the current API.

**Comment by posva** [comment]
This is not technically possible unless we monkey patch the method, which is unreasonable to do only for testing and could also be done in an external package. But definitely not a behavior that we want be default.

The real solution here is to expose the router instance in your e2e tests to call push on it.

I don't think you should stub the the router on e2e tests either

**Comment by maximedupre** [comment]
Thanks for the response. Just so I understand correctly, are you suggesting that I attach the router instance to `window`?

**Comment by posva** [comment]
More or less. Check cypress documentation on how to attach globals and use them in tests

**Comment by maximedupre** [comment]
There doesn't seem to be any Cypress documentation on how to attach globals and use them in tests. The only relevant doc on this matter is the doc related to [`cy.window`](https://docs.cypress.io/api/commands/window.html#Syntax) and the examples are showing just normal properties attached to the window (as I alluded to in my previous comment). What do you mean by "more or less"? Can you elaborate in a sentence or two? Thanks.
