### ISSUE TITLE
why need pre decode the   into space?

### ISSUE THREAD

**Issue by 0x30** [vuejs/vue-router-next#840]
### Version
4.0.5

https://github.com/vuejs/vue-router-next/blob/master/src/query.ts#L54

为什么需要预解码`+`号呢，不是很理解。而且就算是预解码，为什么是把 `+` 转为 空格，而不是 `+` 转为 `%2B`.

这样会引发一个问题，比如 我的链接是 `http://example/#/?value=1+2`,我这个时候想获取到 value 应该为 `1+2`,这个时候会出现为`1 2`.  

如果这个时候，我进行 `encodeURIComponent`,把结果传给别人的话，就会出现和预想的不一样的结果

**Comment by posva** [comment]
See https://github.com/vuejs/vue-router-next/issues/561. Next time, open issues in English, thanks!

**Comment by 0x30** [comment]
Sorry, just pure curiosity. What are the reasons for doing this, such as: "If we don't do this, what problems will it cause?". 

Because I found that `URL` and `URLSearchParams` do the same

````js
(new URL("https://abc.com?a=1+2")).searchParams.get("a")
> "1 2"
10:22:54.627 (new URLSearchParams("?a=1+2")).get("a")
> "1 2"
````

Maybe I should find the answer to this question on stackoverflow.Sorry again
