### ISSUE TITLE
Not setting history option in initial config leads to confusing error

### ISSUE THREAD

**Issue by hay** [vuejs/vue-router-next#843]
### What problem does this feature solve?
I'm trying to build my first Vue 3 project, and i'd like to include the new router as well. One thing i noticed is that you get an error that's a bit confusing when not providing the `history` option in the initial configuration, e.g.:

```
const router = createRouter({
    routes : [{
        path : '/',
        component : ScreenHome
    }]
});
```

Leads to an error:

`Uncaught TypeError: Cannot read property 'location' of undefined`

In the console. When i added the `createWebHashHistory` option everything worked fine. 

I know this is mentioned in the docs, but it's easy to miss, and coming from the Vue2 router (where history is set to hash by default) i think this will probably trip up many people trying to convert existing projects or starting new ones.

### What does the proposed API look like?
I think there would be three possible solutions:
1. Set a default `history` mode (like in v3)
2. Make the `history` option required
3. Provide an error message that's clearer ('Please provide a history option')

I would be really happy with either 1) or 2), but at least a better error message would be very helpful.

**Comment by posva** [comment]
I think a dev only error makes sense for this (option 3)

**Comment by hay** [comment]
Looks nice, thanks @posva and @cheng-github!
