### ISSUE TITLE
Setting an optional parameter to undefined generates a link with `undefined` in the path instead of ommiting the paramater, like in vue-router@3

### ISSUE THREAD

**Issue by rashfael** [vuejs/vue-router-next#855]
### Version
4.0.5

### Reproduction link
[https://jsfiddle.net/7sLubz0q/6/](https://jsfiddle.net/7sLubz0q/6/)

### Steps to reproduce
- click on link "Bar"

### What is expected?
url should show `/bar`, like in vue-router@3 https://jsfiddle.net/9bd0wag6/1/

### What is actually happening?
Url shows `/bar/undefined`.

**Comment by posva** [comment]
You can only pass strings, numbers and arrays of these to params (https://github.com/vuejs/vue-router-next/blob/master/src/types/index.ts#L34). Vue Router 3 only accepts strings: https://github.com/vuejs/vue-router/blob/dev/types/router.d.ts#L193. This is why was never documented as a breaking change.

You can still achieve an empty optional param with an empty string or by omitting the key in the object
