### ISSUE TITLE
router.push doesn't resolve the default nested view

### ISSUE THREAD

**Issue by TheDutchCoder** [vuejs/vue-router-next#865]
### Version
4.0.6

### Reproduction link
[https://codesandbox.io/s/nested-views-vue-router-4-examples-forked-2rj65?file=/src/App.vue](https://codesandbox.io/s/nested-views-vue-router-4-examples-forked-2rj65?file=/src/App.vue)

### Steps to reproduce
When defining a default nested view with `{ path: '', component: Home }`, it will not be matched when using `router.push` to navigate to the route.

See the reproduction:
1. Go to any of the sub routes (like posts)
2. Click the "Test" button, which triggers a `router.push` to the top level
3. Route is not resolved to the default `Home` component

### What is expected?
The default to be resolved

### What is actually happening?
The router only resolves to the top-level, but not the subsequent default child.

**Comment by posva** [comment]
This is intended, only the parent route, User, is displayed. Move the `name: 'user'` to the default child (`path: ''`), if you want to target that route instead of its parent.

**Comment by TheDutchCoder** [comment]
So reloading "redirecting" to the child is then still a bug, no?
