### ISSUE TITLE
Use `useRouter` outside vue component

### ISSUE THREAD

**Issue by sagardspeed2** [vuejs/vue-router-next#868]
### What problem does this feature solve?
I am trying to navigate my route from vuex based on response code from the API,
So when I am useing `useRouter`, it gives me undefined and I can't use `useRouter().push()`

### What does the proposed API look like?
I am trying to access useRouter outside vue component ans somewhere in vuex
```
import { useRouter } from 'vue-router'

const router = useRouter()

console.log(router) // undefined

router.push({name: 'some route name'})
```

**Comment by posva** [comment]
This depends on the version of Vuex (or any other store) you are using and should be documented in the store library. In general:

- if you are not doing SSR (Server Side Rendering), you can directly import it from your `router.js` wherever you need
- else, you will need to inject the router into the store to be able to use it everywhere. e.g. with [Pinia](https://github.com/posva/pinia), you attach it to all the stores:
	```js
	pinia.use(() => ({ router }))
	const app = createApp(...)
	app.use(pinia)
	app.use(router)
	// somewhere else in a store
	defineStore({
		  actions: {
			  doSomething() {
				  this.router
			  }
		  }
	  })
	```
	In Vuex 5, there will likely be an equivalent API. In other versions or other stores, you can always pass the router as a parameter.

**Comment by yinqunbo** [comment]
You can try this with main.ts
