### ISSUE TITLE
Typings error when route only has path and beforeEnter

### ISSUE THREAD

**Issue by IlyaSemenov** [vuejs/vue-router-next#869]
### Version
4.0.6

### Reproduction link
[https://jsfiddle.net/semenov/ex1z0687/5/](https://jsfiddle.net/semenov/ex1z0687/5/)

### Steps to reproduce
Create a router with a single route, featuring `path` and `beforeEnter` **only**:

```ts
import { createRouter, createWebHistory } from "vue-router"

export const router = createRouter({
	history: createWebHistory(),
	routes: [
		{
			path: "/",
			beforeEnter: async (to) => {
				await reportAndRedirect(to.fullPath)
			},
		},
	],
})
```

### What is expected?
No Typescript errors.

### What is actually happening?
Everything works, but there are typing errors:

```
Type '{ path: string; beforeEnter: (this: undefined, to: RouteLocationNormalized) => Promise<void>; }' is not assignable to type 'RouteRecordRaw'.
  Property 'redirect' is missing in type '{ path: string; beforeEnter: (this: undefined, to: RouteLocationNormalized) => Promise<void>; }' but required in type 'RouteRecordRedirect'.ts(2322)
```

---
I agree that this is kind of edge case, but I don't see why it's not supported/prevented by Typescript. I need it because I have a project where some pages are using legacy (non-Vue) tech and some are Vue 3, so I run a flexible redirection engine between the two.

My current workaround is to add empty `components` object:

```ts
export const router = createRouter({
	history: createWebHistory(),
	routes: [
		{
			path: "/",
			components: {
				// Empty object to work around vue-router typings
			},
			beforeEnter: async (to) => {
				await reportAndRedirect()
			},
		},
	],
})
```

**Comment by posva** [comment]
This is intended because there is no guarantee for a `beforeEnter()` to **always redirect** so the `component` being required from a typing perspective makes sense. I think your workaround looks good 👍
