### ISSUE TITLE
RouterLink always adds active classes to anchor links

### ISSUE THREAD

**Issue by mattersj** [vuejs/vue-router-next#870]
### Version
4.0.6

### Reproduction link
[https://codesandbox.io/s/priceless-https-bvip5?file=/src/App.vue](https://codesandbox.io/s/priceless-https-bvip5?file=/src/App.vue)

### Steps to reproduce
Just open the reproduction link and check out the DevTools. Anchor links for some reason always have an active and exact-active classes, but they actually should not.

### What is expected?
Anchor links should not have active classes if current url does not contain exactly the same hash.

### What is actually happening?
Anchor links always have active classes no matter what the current url is.

---
More interesting, latest vue-router 3.x. does not have this problem. Here is another repro: https://codesandbox.io/s/nifty-cache-oorr5?file=/src/App.vue
It adds active classes only when current url does contain that hash.

**Comment by posva** [comment]
See https://next.router.vuejs.org/guide/migration/index.html#removal-of-the-exact-prop-in-router-link and the linked rfcs

**Comment by lupodellasleppa** [comment]
> See https://next.router.vuejs.org/guide/migration/index.html#removal-of-the-exact-prop-in-router-link and the linked rfcs

[link changed](https://router.vuejs.org/guide/migration/index.html#Removal-of-the-exact-prop-in-router-link-)
