### ISSUE TITLE
Memory history

### ISSUE THREAD

**Issue by YuYang019** [vuejs/vue-router-next#871]
### What problem does this feature solve?
just like [react memory history](https://github.com/ReactTraining/history/blob/master/docs/api-reference.md#creatememoryhistory), will vue-router provide this feature ?

### What does the proposed API look like?
```js
import { createMemoryHistory } from 'vue-router'
```

**Comment by posva** [comment]
At least, try searching in the docs, or importing from 'vue-router' with autocompletion, please.

![Screen Shot 2021-04-08 at 09 40 45](https://user-images.githubusercontent.com/664177/113987262-80c1fd00-984e-11eb-8472-e0d84f9d5f53.png)

https://next.router.vuejs.org/api/#creatememoryhistory
