### ISSUE TITLE
Add typed attributes to RouteRecordRaw

### ISSUE THREAD

**Issue by Bluenix2** [vuejs/vue-router-next#881]
### Version

4.0.5

### Reproduction link

See `router/index.ts` and `App.vue` [https://codesandbox.io/s/add-typed-attributes-to-router](https://codesandbox.io/s/add-typed-attributes-to-routerecordraw-7b3gw)

### Steps to reproduce

1. Setup a base repository using `vue-cli` choosing Vue 3, TypeScript, vue-router (I also use Vue-class-component and a few other options, but that shouldn't come to play with this)

2. Go into router/index.ts and attempt to add another attribute (in my case called `icon` that is of type `string` later to be used with `v-bind` to set an element's class)

3. Notice the following error:

```
TS2312: An interface can only extend an object type or intersection of object types with statically known members.
```

4. Adjust; define a new interface extending `RouteRecordRaw` that looks like the following:

```ts
interface RouteRecord extends RouteRecordRaw {
  icon: string
}
```

5. Take note of the following error:

```
TS2312: An interface can only extend an object type or intersection of object types with statically known members.
```

6. Investigate! In my case I want to specifically type `RouteRecordSingleView`, this is not exported...

### What is expected?

Being able to extend RouteRecord to add custom options

### What is actually happening?

Compiler errors but the answer to the problem is not exported

Here is how I want to use the new attribute:

```html
<template>
  <nav id="sidebar" :class="{ 'sidebar-active': $store.state.sidebarActive }">

    <!-- Automatically add the links of all routes -->
    <router-link v-for="route in $router.options.routes" :key="route.path" :to="route.path">
      <span :class="route.icon" />{{route.name}}
    </router-link>

  </nav>
</template>
```

Never repeat yourself! So I want to use the already defined routes instead of writing it at two places, thing is that I want to also have a FontAwesome icon for each route.

The end result for each route should look something like:

```html
<a href="/" class="router-link-active router-link-exact-active">
  <span class="fas fa-house-user">
</a>
```

**Comment by posva** [comment]
This is what `meta` is for: https://next.router.vuejs.org/guide/advanced/meta.html#route-meta-fields
