### ISSUE TITLE
Transition   Suspense, the leave animation is the previous transition name when using `route.afterEach`

### ISSUE THREAD

**Issue by DoradoFlamingo** [vuejs/vue-router-next#886]
### Version
3.0.11

### Reproduction link
[https://codesandbox.io/s/divine-pine-0kr6z](https://codesandbox.io/s/divine-pine-0kr6z)

### Steps to reproduce
- Follow the vue-router-next documentation of dynamic transitions and use route.afterEach in your component to determine animation which is slide-right/slide-left. 
- Then used the element order explained in the Suspense explanation in the documentation.

```
<router-view v-slot="{ Component }" >
                    <transition :name="transitionName">
                        <suspense>
                            <component :is="Component" />
                            <template #fallback>
                                <Loader></Loader>
                            </template>
                        </suspense>
                    </transition>
                </router-view>
```

### What is expected?
- the transition gets set as slide-right
- both components that are leaving/entering use slide-right

### What is actually happening?
- the leaving component uses the previous animation
- the entering component uses the newly assigned animation

---
This might not be a bug as such, so I could be saying something incorrect. Though to me it felt like something's off. It could be that the order of hooks with Suspense aren't explained? When you work with the vue-router documentation for dynamic transitions, the entering/leaving components work with the correctly assigned transitions (e.g. slide-right-leave, slide-right-enter). Once you add suspense into the equation, it changes somehow where the leaving component keeps the previous animation (e.g. slide-left-leave, slide-right-enter).

To fix it to be like "what is expected", I simply changed the route guard to route.beforeEach from route.afterEach inside the `setup()` component.

**Comment by posva** [comment]
@DoradoFlamingo I moved this to the correct repository
