### ISSUE TITLE
Bug of beforeRouteLeave hook

### ISSUE THREAD

**Issue by wuyuweixin** [vuejs/vue-router-next#890]
### Version
4.0.6

### Reproduction link
[https://github.com/wuyuweixin/vue-router-bug.git](https://github.com/wuyuweixin/vue-router-bug.git)

### Steps to reproduce
1.clone repo
2. yarn
3.yarn dev
4.click MyForm button
5.Try again and again to go back to the home page, and the bug will appear.

### What is expected?
The page should stay here all the time, and the browser address will not change.

### What is actually happening?
The page and the browser address have changed.

**Comment by posva** [comment]
This is expected behavior: we cannot trap the user in a page if they click multiple times on the back button. There is nothing we can do with the HTML5 history api to prevent this behavior from happening

**Comment by wuyuweixin** [comment]
But this is OK with 3. X

**Comment by posva** [comment]
No... the confirm message gets closed automatically

**Comment by wuyuweixin** [comment]
https://github.com/wuyuweixin/vue-router-test.git
