### ISSUE TITLE
removeRoute could return a boolean result

### ISSUE THREAD

**Issue by PeterAlfredLee** [vuejs/vue-router-next#894]
### What problem does this feature solve?
Say I got 5 routers to be deleted, and I need to do something after all of them are removed. My code may look like this:
```javascript
$router.removeRoute('A')
$router.removeRoute('B')
$router.removeRoute('C')
$router.removeRoute('D')
$router.removeRoute('E')
if($router.hasRoute('A')&&$router.hasRoute('B')&&$router.hasRoute('C')&&$router.hasRoute('D')&&$router.hasRoute('E')){//Do something.}
```

I can make this a PR but this is a API breaking change. So I want to hear from you guys first. WDYT?

### What does the proposed API look like?
Make `removeRoute` return a boolean result. Then the code may look like:
```javascript
if(router.removeRoute('A')&&$router.removeRoute('B')&&$router.removeRoute('C')&&$router.removeRoute('D')&&$router.removeRoute('E')){//Do something.}
```

**Comment by posva** [comment]
You don't need to check anything after the route is removed
