### ISSUE TITLE
Why the $route is not in the ctx but can be found and parsed in the template

### ISSUE THREAD

**Issue by pdsuwwz** [vuejs/vue-router-next#902]
### Version
4.0.6

### Reproduction link
[https://codesandbox.io/s/vue-router-route-73iju?file=/src/components/CustomComp.vue](https://codesandbox.io/s/vue-router-route-73iju?file=/src/components/CustomComp.vue)

### Steps to reproduce
1.
```html
<template>
  <div>
    <p>{{ $route }}</p>
  </div>
</template>
```

2.

```js
  setup() {
    const { ctx } = getCurrentInstance()
    onMounted(() => {
      console.log('Test $route: ', ctx.$route)
    })
    return {
      say: ref("Hello")
    };
  }
```

I know that `useRoute()` get `$route`, but I want to try use `ctx.$route`.
So I got `ctx` through `getCurrentInstance()` and then found that there is no `$route` field in `ctx` but it can be rendered normally in `<template>`.

I want to know why does it rendered properly in the `<template>` without the `$route` field in `ctx`?

I’m not sure if this is a bug or my usage is wrong. 

### What is expected?
console.log('Test $route: ', ctx.$route)

`ctx.$route` can be printed normally.

### What is actually happening?
console.log('Test $route: ', ctx.$route)

`ctx.$route` is `undefined`

**Comment by posva** [comment]
It's ctx.proxy.$router but you should use useRouter()

**Comment by pdsuwwz** [comment]
> It's ctx.proxy.$router but you should use useRouter()

Please see that what I want to get is `$route`, not `$router`, and I know that routing meta information can be obtained through `useRoute()`. So I want to know why there is only `$router` but no `$route` in `ctx`

**Comment by edison1105** [comment]
@pdsuwwz 
![image](https://user-images.githubusercontent.com/3705199/115994549-0fce6380-a60a-11eb-8b12-2573074e7fc2.png)

**Comment by pdsuwwz** [comment]
> For more information see https://github.com/vuejs/vue-next/blob/master/packages/runtime-core/src/componentPublicInstance.ts#L249

@edison1105 
Hi~ I have a question, why not in the deconstructed ctx, and I only see $router in it, but not $route:

![where-is-route.png](https://i.loli.net/2021/04/26/OhCWarvkSU6DIR5.png)

**Comment by pdsuwwz** [comment]
Reference in: 

https://github.com/vuejs/vue-router-next/blob/c6460f09aab3a834121dc58fc5880c81a65147ef/src/router.ts#L1103-L1106

**Comment by pdsuwwz** [comment]
@posva 

I found that it is because the `$route` set by `Object.defineProperty()` does not define `enumerable: true`
and Vue calls the `createRenderContext()` when adding global properties. This method uses `Object.keys()`. As we all know, `Object.keys()` can only get enumerable types, so `$route` is ignored.

createRenderContext Reference in:
https://github.com/vuejs/vue-next/blob/b46d8578fd7e0cb7f82620d21f2a0ad1094c34af/packages/runtime-core/src/componentPublicInstance.ts#L488

I suggest adding attributes when defining:

```js
Object.defineProperty(app.config.globalProperties, '$route', {
    enumerable: true,
    get: () => unref(currentRoute),
})
```

**Comment by edison1105** [comment]
@pdsuwwz 
Maybe you can file a PR.

```javascript
Object.defineProperty(app.config.globalProperties, '$route', {
    enumerable: true,
    get: () => unref(currentRoute),
})
```
