### ISSUE TITLE
Infinite loop when watch route in RouteView component

### ISSUE THREAD

**Issue by Senasiko** [vuejs/vue-router-next#910]
### Version
4.0.6

### Reproduction link
[https://jsfiddle.net/s0ebm54u/](https://jsfiddle.net/s0ebm54u/)

### Steps to reproduce
1. click `Bar`
2. look console

### What is expected?
just log once

### What is actually happening?
Infinite loop log

**Comment by posva** [comment]
It's 

```js
watch(() => route, () => {
    	console.log('route change');
    	val.value = Math.random();
    });
```

that's also the reason you get the warning in the console.

**Comment by Senasiko** [comment]
@posva thanks, but I think it's not all right.
the `Reactive` type of `watch`'s first params is allowed, and it's deep default. If not, I have to `watch(() => [route.name, route.query, ...])` to watch route changes.
So I think that the issue is in the iterate of `route` rather than the `watch` params
