### ISSUE TITLE
Document advanced/programmatic setter for to.matched[].components

### ISSUE THREAD

**Issue by arivero** [vuejs/vue-router-next#914]
### What problem does this feature solve?
In some occasions one needs to produce a dynamic matching beyond the reach of pattern matching. Not having an authoritative recipe drives programmers to use features that could be unintended and disappear in future patches.

### What does the proposed API look like?
Changes in documentation and tutorials should be enough

A usual recipe for this goal is to use a wildcard pattern,  hook into beforeEach or beforeEnter, analyze the path, and then finally set the value of to.matched[0].components.

to.matched[0].components = {
    default: myComponent
  };

 As far as I have seen, it is not documented if this substitution is allowed nor how does it impact in vue reactivity features.

 Some guides, on the other hand, seems to describe the possibility of using a function to produce the components, but it is not described how this function could have access to the actual path in order to analyze it.

  {
    path: "/*",
    name: "x",
    components: () => {return {default: MyComponent}},
  },

Documentation should describe if both methods are available to alter the components produced by a route. Besides, a proper recipe should explain also how to set the props for the components.

**Comment by posva** [comment]
The `to` and `from` are treated as readonly (except for the `meta` attribute which can be modified in guards). One should not modify the matched array and that's why there is not such examples in the documentation. If you have proposals for improvements we are open to pull requests
