### ISSUE TITLE
Defining functional components in router configuration will cause routing switching errors

### ISSUE THREAD

**Issue by StarFishing** [vuejs/vue-router-next#915]
### Version
4.0.6

### Reproduction link
[https://jsfiddle.net/starfishing/bcst21vg/](https://jsfiddle.net/starfishing/bcst21vg/)

### Steps to reproduce
change foor and bar

### What is expected?
router change is good

### What is actually happening?
vnode.component.isUnmounted has error

---
when a component like this:
```
function empty() {
// or return null
  return <div>hello</div>;
}
export default empty;
```

the router will change error

**Comment by PeterAlfredLee** [comment]
Hi, @StarFishing 
```
// const Bar =()=>{ return <div></div> }
const Bar =()=>{ return null }
```
I don't think that's the right definition of component `Bar`.
It should be a or return a vue component instance.

**Comment by StarFishing** [comment]
@PeterAlfredLee  In the Vue file, the function component is supported to be written in the above form, for example, it is written in test.js
`
export default const Bar =()=>{ return null }
`
Then in the router configuration as follows
`
{
path:'/test',
components:()=>import('./test')
}
`
The current situation is that when the route generated by this functional component and the vue file are switched as the route generated by the component, the logic of the judgment condition vnode.component.isUnmounted will be wrong.

**Comment by edison1105** [comment]
```javascript
const Bar =()=>{ return null }
```
This definition is meaningless. 
Can you provide us with your actual usage scenarios?

If you must do this, you can replace with:
```javascript
const Bar = { render(){ return null} }
```
I believe this will work as expected.

**Comment by posva** [comment]
You need to add a `displayName` to functional components used by the router:

```js
const Bar = () => {
  return null
}
Bar.displayName = 'Bar'
```

This should be documented in the API https://next.router.vuejs.org/api/#routerecordraw as a note

**Comment by StarFishing** [comment]
In some cases, I hope that the content rendered by a route is imported from the outside and manually mounted by me, but I also want to appear in the position of the router-view. In order to maintain routing consistency, I will declare the route but not render the content. . This is my scene. In view of the functional components of vue, I have the above writing method, I hope to be as simple as possible. I tried to return a pair of div tags with no content, and it behaves the same as null. And there is no problem with the route switching that returns to the functional component, but there is a problem when switching between the route returning to the vue component and the route returning to the functional component, because vnode.component is null at this time. @posva 's suggestion is very good. it is good. But there is no guarantee that it will be written in this way, so I hope to add some support

**Comment by posva** [comment]
The functional component needs a `displayName` so it can be differentiated from dynamic imports by the Router

**Comment by StarFishing** [comment]
@posva I found this error message during debugging, but it was not easy to notice. Has been modified so far
