### ISSUE TITLE
Migrating webpack build to vite

### ISSUE THREAD

**Issue by posva** [vuejs/vue-router-next#929]
The existing build for end to end tests should be migrated to Vite. End to end tests

- Replace webpack and its loader with vite
- Replace scripts using webpack with vite commands
- Adapt the e2e runner.js to work with Vite instead of webpack
- Make sure the runner builds the project and serves it when passed the `--local` option (for older browsers)

**Comment by GGwujun** [comment]
What does 'Make sure the runner builds the project and serves it when passed the --local option (for older browsers)'  mean?

**Comment by posva** [comment]
it means that this command https://github.com/vuejs/vue-router-next/blob/master/package.json#L40 should still work and it will require to build the e2e examples and serve them instead of running webpack in dev mode

**Comment by GGwujun** [comment]
ok,i understand.ths

**Comment by GGwujun** [comment]
![Uploading image.png…]()
