### ISSUE TITLE
Migration guide - put reasons before detailed changes

### ISSUE THREAD

**Issue by wenfangdu** [vuejs/vue-router-next#931]
### What problem does this feature solve?
Right now the reasons are put below the changes, it's really hard to read on without knowing the _why_, had to scroll to the reason first for understanding the change. Can we consider putting reasons upfront?

E.g.

![image](https://user-images.githubusercontent.com/28700378/117520431-b6d3d780-afda-11eb-9d08-59fe9062a079.png)

### What does the proposed API look like?
Reasons are put before the detailed changes.

**Comment by posva** [comment]
I disagree. When migrating, I want to see what to adapt first. Some people don't even care about the reason. Thank you for the suggestion!
