### ISSUE TITLE
Redundant ampersand when trying to remove query param

### ISSUE THREAD

**Issue by mattersj** [vuejs/vue-router-next#934]
### Version
4.0.6

### Reproduction link
[https://codesandbox.io/s/priceless-https-bvip5](https://codesandbox.io/s/priceless-https-bvip5)

### Steps to reproduce
1. Open reproduction link, take a look at the url and just wait for 2 timeouts.
2. When second timeout is passed you'll notice unnecessary ampersand sign at the end of the current url.

### What is expected?
When I pass `undefined` or empty array as a query parameter value then I expect query parameter will be **completely** removed from the current url.

### What is actually happening?
Query parameter was properly removed but unnecessary `&` sign still presents at the end of the url.

---
I believe that's because of this line: https://github.com/vuejs/vue-router-next/blob/ecd52e017ac30fa996d4796974371374f65640d1/src/query.ts#L92
It doesn't take into account the passed value and appends `&` sign right away no matter whether the value is null or undefined.

**Comment by posva** [comment]
You are right about the location of the fix: It should apply the & inside the if and also at https://github.com/vuejs/vue-router-next/blob/ecd52e017ac30fa996d4796974371374f65640d1/src/query.ts#L107

**Comment by mattersj** [comment]
@posva ok, I'm going to submit a PR with the fix a little bit later.

To be honest, I feel the current implementation of `stringifyQuery` is slightly verbose so I did a little refactoring and made it more declarative.
What do you think about the following implementation?

```ts
export function stringifyQuery(query: LocationQueryRaw): string {
  return Object.entries(query).reduce((acc: string[], [key, value]): string[] => {
    const values: LocationQueryValueRaw[] = Array.isArray(value)
      ? value.map(v => v && encodeQueryValue(v))
      : [value && encodeQueryValue(value)]
    
    key = encodeQueryKey(key)
    const pair = values.reduce((acc: string[], chunk): string[] => {
      if (chunk === undefined) return acc
      if (chunk === null) return [...acc, key]
      return [...acc, [key, chunk].join('=')]
    }, [])

    return [...acc, ...pair]
  }, [])
    .join('&')
}
```

I think it's more straightforward, we just specify all the edge-cases in the second `reduce` and do not worry about separators anymore as they would be added automatically by joins.
That implementation has passed all tests and also takes into account the issue we were talking about above.

**Comment by posva** [comment]
Let's not refactor with that version for performance and compatibility reasons

**Comment by mattersj** [comment]
No problem. I've submitted a PR with as few changes as possible.
