### ISSUE TITLE
Third party custom-elements (imported web components) do not render in router view

### ISSUE THREAD

**Issue by TomasKulhanek** [vuejs/vue-router-next#946]
### Version
3.5.1

### Reproduction link
[https://codesandbox.io/s/vue-3-router-with-bodylightjs-components-h8v50](https://codesandbox.io/s/vue-3-router-with-bodylightjs-components-h8v50)

### Steps to reproduce
1. create or import third party custom-element
2. register the custom element in index.html
3. add this custom element in some router view. E.g. into Home.vue or another component

### What is expected?
The third party custom-element should be rendered in view.

### What is actually happening?
Third party Custom-element is not rendered

---
Note that this works in VUE2 with router. This works also in VUE3 app without router.

Third party custom-elements are standard web-components. We export set of webcomponents from another framework and this standard makes webcomponents interoperable.

**Comment by posva** [comment]
@TomasKulhanek  Transferred to the correct repository.

You need to tell Vue to ignore the components. This is not Vue Router specific. See https://v3.vuejs.org/guide/migration/custom-elements-interop.html#overview

**Comment by TomasKulhanek** [comment]
The commands to ignore elements are already there in vue.config.js. For codesandbox example I added runtime config ` app.config.isCustomElement = (tag) => tag.startsWith("edit-");`. 

Updated codesandbox example shows the error on top of the rendered page - working custom-elements on bottom where router renders it's content - the error. Router in VUE3 tries to render custom-elements despite the config.

![1xFiYVrfWl](https://user-images.githubusercontent.com/1429487/118258920-be025600-b4b0-11eb-9568-c2153029ac3a.gif)

**Comment by posva** [comment]
The problem you have comes from 

```js
this.setAttribute('tabindex', '0')
this.style.display = 'inline-block'
```

Which prints the error 

```
Uncaught DOMException: Failed to construct 'CustomElement': The result must not have attributes
```

You probably need to set the attributes and styles on each element instead of `this` but this is related to custom elements and not Vue nor router. BTW the error happens without vue router too.

**Comment by TomasKulhanek** [comment]
This is third-party custom-element, so VUE should not try to create it nor should limit whether custom element may have attributes or not. Based on your comment I tried it out of codesandbox and the full error log contains `q @ vue-router.esm-bundler.js:3140`

<details>
  <summary>runtime-dom.esm-bundler.js:22 Uncaught DOMException:  ...</summary>

```
runtime-dom.esm-bundler.js:22 Uncaught DOMException: Failed to construct 'CustomElement': The result must not have attributes
    at createElement (http://localhost:8080/vue3/js/chunk-vendors.1a019aff.js:6:68165)
    at k (http://localhost:8080/vue3/js/chunk-vendors.1a019aff.js:6:48699)
    at C (http://localhost:8080/vue3/js/chunk-vendors.1a019aff.js:6:48506)
    at O (http://localhost:8080/vue3/js/chunk-vendors.1a019aff.js:6:47957)
    at P (http://localhost:8080/vue3/js/chunk-vendors.1a019aff.js:6:49434)
    at k (http://localhost:8080/vue3/js/chunk-vendors.1a019aff.js:6:48747)
    at C (http://localhost:8080/vue3/js/chunk-vendors.1a019aff.js:6:48506)
    at O (http://localhost:8080/vue3/js/chunk-vendors.1a019aff.js:6:47957)
    at P (http://localhost:8080/vue3/js/chunk-vendors.1a019aff.js:6:49434)
    at k (http://localhost:8080/vue3/js/chunk-vendors.1a019aff.js:6:48747)
createElement @ runtime-dom.esm-bundler.js:22
k @ runtime-core.esm-bundler.js:3889
C @ runtime-core.esm-bundler.js:3868
O @ runtime-core.esm-bundler.js:3788
P @ runtime-core.esm-bundler.js:3975
k @ runtime-core.esm-bundler.js:3896
C @ runtime-core.esm-bundler.js:3868
O @ runtime-core.esm-bundler.js:3788
P @ runtime-core.esm-bundler.js:3975
k @ runtime-core.esm-bundler.js:3896
C @ runtime-core.esm-bundler.js:3868
O @ runtime-core.esm-bundler.js:3788
(anonymous) @ runtime-core.esm-bundler.js:4298
n @ reactivity.esm-bundler.js:42
u @ reactivity.esm-bundler.js:17
B @ runtime-core.esm-bundler.js:4263
L @ runtime-core.esm-bundler.js:4222
I @ runtime-core.esm-bundler.js:4182
O @ runtime-core.esm-bundler.js:3791
(anonymous) @ runtime-core.esm-bundler.js:4368
n @ reactivity.esm-bundler.js:42
Ie @ runtime-core.esm-bundler.js:154
lt @ runtime-core.esm-bundler.js:384
Promise.then (async)
tt @ runtime-core.esm-bundler.js:286
et @ runtime-core.esm-bundler.js:280
h @ reactivity.esm-bundler.js:183
O @ reactivity.esm-bundler.js:189
scheduler @ reactivity.esm-bundler.js:851
h @ reactivity.esm-bundler.js:183
O @ reactivity.esm-bundler.js:189
scheduler @ reactivity.esm-bundler.js:851
h @ reactivity.esm-bundler.js:183
O @ reactivity.esm-bundler.js:189
scheduler @ reactivity.esm-bundler.js:851
h @ reactivity.esm-bundler.js:183
O @ reactivity.esm-bundler.js:189
set value @ reactivity.esm-bundler.js:761
q @ vue-router.esm-bundler.js:3140
(anonymous) @ vue-router.esm-bundler.js:3013
Promise.then (async)
N @ vue-router.esm-bundler.js:2984
R @ vue-router.esm-bundler.js:2918
u @ vue-router.esm-bundler.js:2071
Ie @ runtime-core.esm-bundler.js:154
Le @ runtime-core.esm-bundler.js:163
n @ runtime-dom.esm-bundler.js:333 
```
</details>

 I also noticed that if I refresh the broken page with `#/simplecomponent` in URL - the component is rendered correctly, the problem is when clicked the button - so the router renders new view - this 'refresh' doesn't work in codesandbox.

I have more complex sample demonstrating this error out of the codesandbox at
https://github.com/creative-connections/vue3-bdl2-sample-app
