### ISSUE TITLE
router.push with no path will navigate to the current path which is encoded

### ISSUE THREAD

**Issue by stanfil** [vuejs/vue-router-next#950]
### What problem does this feature solve?
i'm using vite to build a ssr vue app.

the href before is
localhost:8080/h5/test/index.html
when i call
```
$router.push({ query: { x: 1 }})
```
my browser jump to 
localhost:8080/h5%2Ftest%2Findex.html?x=1

it's ugly. i want it to navigate to localhost:8080/h5/test/index.html?x=1. what should i do

### What does the proposed API look like?
in the source code, i see the function
matcher.resolve () {
...
    path = matcher.stringify(params)
...
}
and the params is encoded before. so the path is now encoded

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

You need to use a repeatable param: https://next.router.vuejs.org/guide/essentials/route-matching-syntax.html#custom-regexp-in-params
