### ISSUE TITLE
scrollBehavior API docs would benefit from a link to the advanced guide

### ISSUE THREAD

**Issue by aethr** [vuejs/vue-router-next#953]
### What problem does this feature solve?
I typically go straight to the API docs for Vue tools, but the `scrollBehavior` documentation in vue-router-next is pretty minimal. I didn't realise until I'd spent some time looking at the code that there's a very comprehensive guide available in the docs.

I'm happy to contribute a PR for this very small change.

### scrollBehavior

Function to control scrolling when navigating between pages. Can return:
  - a ScrollPosition object, which can contain:
    - [ScrollToOptions](https://developer.mozilla.org/en-US/docs/Web/API/ScrollToOptions)
    - an `el` property with a selector or reference to an element
  - a Promise to delay scrolling
  
See [Scroll Behaviour](../guide/advanced/scroll-behavior.md) for more details.

**Signature:**

```typescript
scrollBehavior?: RouterScrollBehavior
```

#### Examples

```js
function scrollBehavior(to, from, savedPosition) {
  // `to` and `from` are both route locations
  // `savedPosition` can be null if there isn't one
  return savedPosition || { top: 0 };
}
```

**Comment by posva** [comment]
Thanks for the proposal, no need to open issues for doc PRs, just open the PR directly 🙂
