### ISSUE TITLE
isNavigating slot prop

### ISSUE THREAD

**Issue by jods4** [vuejs/vue-router-next#955]
### What problem does this feature solve?
When using lazy-loaded components, async before guards, or async components, the router needs an easy way to display feedback to users that loading is in progress.

All of those can typically go to the network and last an unknown amount of time. 
During dev, an easy to notice example is going to a lazy-loaded route for the first time. In complex pages, Vite takes 3s or more to return the page. On the UI side nothing happens and user wonders if he clicked, or if the app crashed.

Good UX dictates that an immediate feedback is shown to users on actions, including navigation.

### What does the proposed API look like?
To enable that easily, I suggest that the router exposes an `isNavigating` prop on the router itself (for JS access) and to the slot of `router-view`.
Example usage:
```html
<router-view v-slot="{ Component, isNavigating }">
  <div v-if="isNavigating">Loading...</div>
  <component v-else :is="Component" />
</router-view>
``` 

`isNavigating` would be `true` as soon as an async process starts during navigation. 
It becomes `false` again when navigation is complete (success or failure).

*Why "as soon as an async process starts"?*
The goal is to reduce work when navigation is synchronous, esp. if a `beforeEnter` guard cancels the nav synchronously.
Nothing would be shown in UI as it is updated at the end of JS turn anyway.

### Open issues
I'm afraid async components can't really integrate into this model, because they directly interact with `suspense` rather than the router.
A more complex slot template should be able to account for that.

To support child routes in JS, `router.isNavigating: boolean` might be complemented by more specific properties to indicate which route is currently navigating. This is advanced usage and shouldn't stop adding the basic feature, which has immediate benefits.

### Alternatives
One can try to emulate this using `beforeEach` and `afterEach` global guards, but it's significantly more effort and there's no good place to globally share this state, esp. with child routes and `router-view`.

**Comment by posva** [comment]
This can be fully implemented in user land with `beforeEach`, afterEach and onError. Allowing users to have the implementation that fits their need (e.g. having the pending location instead of a boolean). There are a lot of different possibilities that make this feature a user land feature rather than router level.

> there's no good place to globally share this state

You can:

- Attach it to customProperties in the app
- Provide it from the app and inject it in children

**Comment by jods4** [comment]
I noted that this is a possible alternative, could you please help me a little with the following questions regarding user-land implementation?

- How can you ensure that your `beforeEach` is the very first one to run? If I'm correct this is entirely dependent on being the first one registered when configuring the router, right? is that sufficient?
- `afterEach` can't be async (right?) so the order doesn't matter?
- Can you elaborate on getting access to current state when using child routers or named views? 
Having `router-view` tell you if it's loading or not is obviously the simplest design, if we don't have that, where do you get that information for a specific `router-view`? 
You suggested using injection: where/how would the right value for that level be injected? How can that work if you have 2 different named `router-view` in the same component?

It's significantly more complex than having it ootb for something that's basically required for any app that has async route loading and wants a good UX.

If not built-in, I think having a recipe with a code example in the docs would be nice. 
If would be best to make a reusable library for that but I'm really not sure how to have a clean, general lib for the point about state and child routers/named views.

**Comment by posva** [comment]
- yes
- don't understand but it should work
- app.provide() and it will be available everywhere

**Comment by jods4** [comment]
I think there's a misunderstanding regarding the 3rd point, which IMHO is the most complex and the one justifying this being built into vue-router.

Consider a complex app that makes use of many nested routes and named views.
Let's say my app component looks something like this:

```html
<router-view name="TopNav" />

<router-view name="LeftSide"/>

<router-view>
  <!-- main part -->
  <router-view>
    <!--nested-route -->
  </router-view>
</router-view>
``` 

Consider each router-view could be currently async loading a component and we want to display feedback accordingly.
How should each view find out if it's currently loading or not? 
How can you encapsulate that info in a library that is generic enough and easy to consume?
I don't think a global `provide` works well in such situations.

In fact I believe there is only one component that is in the right place to `provide` the correct information for its scope: `router-view`. This can't be easily faked from user-land in a component has multiple views such as above.

What do you think? Am I missing an easy solution?

### Revised idea
Based on your comment about needing more complex infos, I agree and would suggest a slightly different API.

What if each router-view maintained a (shallow) reactive record with the following shape:
```ts
interface RouterState {
  // Same as router.currentRoute, the exact route that the app is currently at.
  currentRoute: RouteLocationNormalized;
  // The route that is displayed in this router-view. 
  // When using nested routes, this can be a parent of `currentRoute`; otherwise it's just `currentRoute`.
  localRoute: RouteLocationNormalized;
  // The name of the router-view we're in, if we're in a named view.
  name: string;
  // The route that this app is currently navigating to, if a navigation is in progress
  toRoute: RouteLocationNormalized | null;
  // The local route to which we're navigating to.
  // When using nested routes, when the child route is changing, at the parent level `targetLocalRoute` would stay `null`
  toLocalRoute: RouteLocationNormalized | null;
  // For convenience, this is `toLocalRoute !== null`
  isNavigating: boolean;
}
``` 

I think this provides complete information, so you can do whatever you want based on current route, target route, named viewport, etc. If something important is missing the object could be extended in the future.

There would be one such record at each `router-view`, and it would be made available in 2 different ways:
- For JS usage, each router-view would `provide` this record. Maybe `useRouterState()` could be used for easy access.
- For template usage, e.g. my original "loading" feedback example, this would also be provided as `v-slot="{ State }"`.

**Comment by posva** [comment]
> Consider each router-view could be currently async loading a component and we want to display feedback accordingly.

Are you talking about using `Suspense`? There is no integration between RouterView and Suspense. This would require a completely new RouterView component, it's something I started working on some time ago but hit blockers and didn't come back (https://github.com/vuejs/vue-router-next/commits/feat/suspendedrouterview)

> How should each view find out if it's currently loading or not?

I would say that should be handled inside the view component because there are different possible strategies like using 1 or multiple Suspense components and it's not flexible enough when automatically done by the router or, ends up in a bunch of boolean props making the API confusing.

**Comment by jods4** [comment]
> Are you talking about using Suspense? There is no integration between RouterView and Suspense. This would require a completely new RouterView component, it's something I started working on some time ago but hit blockers and didn't come back.

Even without Suspense:
- A route can define its Component as a Promise (typically split point `Component: () => import("my-comp")`.
- Routes can define hooks that return promises (e.g. maybe to load data async. from the network).

> I would say that should be handled inside the view component because there are different possible strategies like using 1 or multiple Suspense components and it's not flexible enough when automatically done by the router or, ends up in a bunch of boolean props making the API confusing.

I'm assuming this answer is with respect to `Suspense` only?
Currently I think that's the only way to handle this -- as you say `Suspense` is not integrated with `router-view` so the template one puts inside `router-view` must handle async components through `Suspense` templates if one is using them.

I don't think it answers my question about how to best know if a `router-view` is currently loading its component or resolving async hooks.

**Comment by posva** [comment]
> Even without Suspense

That wouldn't be possible because the navigation doesn't happen partially. When router.push resolves, every router view updates. This is by design.

> I don't think it answers my question about how to best know if a router-view is currently loading its component or resolving async hooks (in the non trivial case where your app uses more than one router-view).

You can't differentiate them because the lazy loading is part of async navigation and happens before triggering entering hooks because the lazy-loaded routes could have some. It would be problematic to display loading screens and if an error happens revert to the previous view. It would be even more problematic if this happens partially.

You could still create something in userland with custom lazy imports that attach the information of lazy loading (loading, errors) somewhere (like a store) if you want to but I would consider this very app-specific behavior.

**Comment by jods4** [comment]
Ok, thanks, I see.
If you have multiple named views, they would all load and complete as one. That's simpler then.

What about nested routes?
I suppose if you're navigating to a child route, you'd want the child router to display a loading indication but not the parent, which is not navigating. Can you easily differentiate that?

**Comment by posva** [comment]
No, you can't, at least out of the box. Nested routes are navigated at the same time as the parent (if they change) and this is by design for navigation guards. You could probably figure that information in userland by checking the `matched` array.
