### ISSUE TITLE
How difficult is to make vue-router-next agnostic, and used with React?

### ISSUE THREAD

**Issue by diegoleme** [vuejs/vue-router-next#968]
### What problem does this feature solve?

I don't know if this is the best place. Sorry, but...

Looking at the code, I saw that there are few points of coupling with Vue.
- dependency with `@vue/devtools-api`
- `router-link` and `router-view` component
- called `app.use(router)`

Are these just touch points really? How complex is it for me to open a fork to adapt for react?

### What does the proposed API look like?
Not applicable

**Comment by diegoleme** [comment]
I found more links to the vue in the file [src/router.ts](https://github.com/vuejs/vue-router-next/blob/master/src/router.ts#L43-L52).  It looks complex.

**Comment by posva** [comment]
It's doable and I started a project on the side to provide an agnostic client-side router based on vue-router but it will take time. Feel free to fork it and try yourself 🙂

**Comment by diegoleme** [comment]
@posva, is this side project open? Can you share the link?

Anyway, I will try to start a fork project. Tks!

**Comment by posva** [comment]
It's not open yet
