### ISSUE TITLE
如何判断当前路由是前进还是后退

### ISSUE THREAD

**Issue by zbjy** [vuejs/vue-router-next#975]
### What problem does this feature solve?
希望提供能判断路由是前进或者后退的方法，用于显示动画

### What does the proposed API look like?
希望提供能判断路由是前进或者后退的方法，用于显示动画

**Comment by edison1105** [comment]
参考 https://next.router.vuejs.org/zh/guide/advanced/transitions.html#%E5%8D%95%E4%B8%AA%E8%B7%AF%E7%94%B1%E7%9A%84%E8%BF%87%E6%B8%A1

不需要知道是前进还是后退 你也能正确的应用动画。

**Comment by JserWang** [comment]
@zbjy 通过`depth`不一定绝对的准确，在`transition`的使用场景，我是这样做的，也许能够帮到你。

https://github.com/JserWang/vue3-vant-template/blob/main/src/components/VPage/usePageTransition.ts
https://github.com/JserWang/vue3-vant-template/blob/main/src/router/guard/history.ts
https://github.com/JserWang/vue3-vant-template/blob/main/src/utils/history.ts

**Comment by KennanChan** [comment]
> @zbjy 通过`depth`不一定绝对的准确，在`transition`的使用场景，我是这样做的，也许能够帮到你。
> 
> https://github.com/JserWang/vue3-vant-template/blob/main/src/components/VPage/usePageTransition.ts https://github.com/JserWang/vue3-vant-template/blob/main/src/router/guard/history.ts https://github.com/JserWang/vue3-vant-template/blob/main/src/utils/history.ts

如果使用$router.go(-2)来做后退，或者使用$router.replace做路由替换，这种通过路由守卫的history记录会失效。如果vue-router可以开放内部的history供查询就好了
