### ISSUE TITLE
Route pass-through/bypass/skip/move-to-next/re-route

### ISSUE THREAD

**Issue by glen-84** [vuejs/vue-router-next#981]
### What problem does this feature solve?
Our site has top-level sections, for example `/apples` and `/bananas`. The list of sections can be non-trivial in length.

If we simply use a route like `/:fruit?`, then something like `/contact` would match, which we obviously don't want.

To solve this, we're using a regex route like `/:fruit(apples|bananas)?`, but this is very messy when there are a lot of sections.

Using nested routes might work, but it'd require things to be ordered in a specific way, and make it more difficult to import routes from multiple application "modules".

When I first saw the `next` callback in the documentation, I mistakenly believed that it would be similar to middleware and allow you to perform some checks on the currently-matched route, and then call `next` to continue matching other routes, but unfortunately it looks like that is not the case. 😞

This would have been a good/clean solution for this case. Is there a possibility that something like this would be considered?

### What does the proposed API look like?
For a breaking change, maybe re-purposing `next` to mean "ignore this route, continue routing".

For a non-breaking change, maybe adding another value to `next`, like `next(CONTINUE)`, or an additional callback.

**Comment by posva** [comment]
This is unfortunately not possible because route matching is synchronous.

You can also generate static routes at runtime (which can be async)

```js
const fruits = await getFruits() // ['banana', 'apple']
const frutRoutes = fruits.map(fruit => ({ path: '/' + fruit, component: FruitView }))
```

**Comment by glen-84** [comment]
@posva,

Thanks for your reply. Perhaps I was unclear, but I'm not suggesting support for asynchronous route matching (we already have an array of section names), but instead a way of telling vue-router to continue or restart matching.

For example:

```ts
const sectionNames = ["apple", "banana"];

{
    name: "home",
    path: "/:section?",
    component: FruitView,
    beforeEnter: (to, _from, next) => {
        if (sectionNames.includes(to.params.section)) {
            return true; // Route match/confirm.
        }

        next(CONTINUE); // No match, continue to next route.
    }
},
```

**Comment by posva** [comment]
it's not possible because resolving happens before navigation guards and cannot be intercepted. Generate an array of static routes, specially if you have the array at build time, it's the proper way to do it.
