### ISSUE TITLE
Using vue-router in the packaged Electron

### ISSUE THREAD

**Issue by WingDust** [vuejs/vue-router-next#982]
### What problem does this feature solve?
Local files will used In the packaged Electron application.
But Vue-Router-next will use url to switch pages.
Does this indicate the Vue-Router-next can't be used in Electron?
Does have any solution?

### What does the proposed API look like?
just use vue-router in the packaged Electron

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

Use `createMemoryHistory()`

**Comment by WingDust** [comment]
@posva thanks
