### ISSUE TITLE
The behavior of nested routes inside <transition> and keep-alive is different from vue2

### ISSUE THREAD

**Issue by yyyang1996** [vuejs/vue-router-next#983]
### Version
4.0.8

### Reproduction link
[https://codesandbox.io/s/twilight-cherry-0e6w6?file=/src/router.js:151-538](https://codesandbox.io/s/twilight-cherry-0e6w6?file=/src/router.js:151-538)

### Steps to reproduce
My `App.vue` component has the following template.
```
<router-view v-slot="{ Component, route }">
      <template v-if="Component">
        <transition name="fade" appear mode="out-in">
          <keep-alive>
            <component :is="Component" :key="route.fullpath"></component>
          </keep-alive>
        </transition>
      </template>
    </router-view>
```
And I have some routes.
```
const routes = [
  {
    path: "/",
    name: "Home",
    component: Home,
    children: [
      {
        path: "foo",
        component: { render: () => h("div", null, "foo") }
      }
    ]
  },
  {
    path: "/about",
    name: "About",
    component: About,
    children: [
      {
        path: "bar",
        component: { render: () => h("div", null, "bar") }
      }
    ]
  }
];
```
Both the `<Home/>` component and the `<About/>` component have nested `<router-view/>`.

When the current route changes from /foo to /about/bar,  the page has a transition. At this point, you will find that the `<Home>` component has not been unmounted, but the `Bar` component has been mounted. This behavior is different from vue2.

You can see the difference with the following demo.

### Demo
- [vue3](https://codesandbox.io/s/twilight-cherry-0e6w6?file=/src/router.js:151-538)
- [vue2](https://codesandbox.io/s/icy-glade-9k4rj?file=/src/App.vue)

#### vue3 gif
![vue3](https://user-images.githubusercontent.com/34713301/120861358-c59db200-c5b9-11eb-83b8-ce8cf155cc77.gif)
#### vue2 gif
![vue2](https://user-images.githubusercontent.com/34713301/120861363-c898a280-c5b9-11eb-9014-ac5561932911.gif)

---
I don't know if this is a bug. If not, what should I do to get similar behavior like Vue2?

**Comment by PeterAlfredLee** [comment]
@yyyang1996  These might be workarounds:

Remove `keep-alive` tag in `App.vue`.

or 

Also add `transition ` to `Home.vue` and `About.vue`.

**Comment by posva** [comment]
Opened https://github.com/vuejs/vue-next/issues/3950 to track
