### ISSUE TITLE
Uncaught TypeError: Cannot use 'in' operator to search for 'path' in undefined

### ISSUE THREAD

**Issue by 1091287322** [vuejs/vue-router-next#992]
### Version
4.0.8

### Reproduction link
[https://jsfiddle.net/1091287322/6rj3d9gw/4/](https://jsfiddle.net/1091287322/6rj3d9gw/4/)

### Steps to reproduce
很简单的应用，下面是我的代码:
// router.js
const Home = { template: '<div>Home</div>' }
const routes = [
	{ path: '/', component: Home }
]
let router = createRouter({
	history: createWebHistory,
	routes: routes
})
// main.js
const app = createApp(App)
app.use(router)
app.mount('#app')

它可以成功编译，但不能运行
浏览器报了这个错误：

Uncaught TypeError: Cannot use 'in' operator to search for 'path' in undefined
    at resolve (vue-router.esm-bundler.js:2837)
    at pushWithRedirect (vue-router.esm-bundler.js:2942)
    at push (vue-router.esm-bundler.js:2911)
    at Object.install (vue-router.esm-bundler.js:3289)
    at Object.use (runtime-core.esm-bundler.js:4001)
    at Module.Vtdi (main.js:9)
    at __webpack_require__ (bootstrap:789)
    at fn (bootstrap:100)
    at Object.0 (index.js:4)
    at __webpack_require__ (bootstrap:789)

能告诉我如何解决这个问题吗？

### What is expected?
能正常使用

### What is actually happening?
浏览器直接报错，很明显这是4.0.8这个版本最明显的BUG

**Comment by GGwujun** [comment]
createWebHistory should be called as a function. [createrouter](https://next.router.vuejs.org/api/#createrouter)
as follows:

```javascript
let router = createRouter({
  history: createWebHistory(),
  routes: routes
})
```

**Comment by posva** [comment]
Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
Also open issues in English
