### ISSUE TITLE
本地路由没问题，测试环境的路由跳转不了

### ISSUE THREAD

**Issue by shanhan0** [vuejs/vue-router-next#995]
### Version
4.0.0

### Reproduction link
[about:blank](about:blank)

### Steps to reproduce
vue-router4本地没问题，发布测试环境报错，路由切换不了
无法读取 null 的属性 'nextSibling' （runtime-core.esm-bundler.js:225）
无法解构 'e' 的属性 'bum' 因为它是 null （runtime-core.esm-bundler.js:225）

路由的url改变了，但是页面没跳转

### What is expected?
正常跳转

### What is actually happening?
不能正常跳转还报错

**Comment by shanhan0** [comment]
各位大佬帮帮忙，万分感谢

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

Also, please open issues in English and always provide a repro: https://new-issue.vuejs.org/?repo=vuejs/vue-next&lang=zh-cn#why-repro
