### ISSUE TITLE
non-bug, but an issue: Vue 3 currentInstance is not defined when in router guard. Is it possible to do something about that?

### ISSUE THREAD

**Issue by baybal** [vuejs/vue-router-next#996]
### What problem does this feature solve?
By definition, the router instance must be housed at least inside the root component.

Why is this important? Vuex 4 relies on the new inject mechanism for its inner workings.

Thus you get `runtime-core.esm-bundler.js?5c40:38 [Vue warn]: inject() can only be used inside setup() or functional components.` if you attempt to look up the store during router guard execution, and quite a few things will not work.

### What does the proposed API look like?
I don't have much idea of Vue 3 inner workings as I don't know typescript, and can't help.

**Comment by posva** [comment]
It's not possible to change that.

You can attach anything to the router:

```ts
import { createPinia, Pinia } from 'pinia'

const pinia = createPinia()
router.pinia = pinia

declare module 'vue-router' {
  export interface Router {
    pinia: Pinia
  }
}

app.use(pinia).use(router)
```

**Comment by baybal** [comment]
Does that work with Vuex instead of Pinia?
