### ISSUE TITLE
Vue Migration build reports "deprecation WATCH_ARRAY" from RouterView

### ISSUE THREAD

**Issue by mgdodge** [vuejs/vue-router-next#997]
### Version
4.0.8

### Reproduction link
[https://github.com/mgdodge/vue-router-next-bug](https://github.com/mgdodge/vue-router-next-bug)

### Steps to reproduce
Clone repo - vanilla vue cli project upgraded to vue 3.1.1 (migration build),   vue router and @vue/compat
Run `npm ci` to install from package-lock.json
Run `npm run serve` to start up via cli
Open site in browser
Note warning in browser console

### What is expected?
No deprecation warnings

### What is actually happening?
Seeing the following:

```
(deprecation WATCH_ARRAY) "watch" option or vm.$watch on an array value will no longer trigger on
array mutation unless the "deep" option is specified. If current usage is intended, you can disable the
compat behavior and suppress this warning with:

configureCompat({ WATCH_ARRAY: false })
```

---
Stack trace seems to indicate it is coming from [this line](https://github.com/vuejs/vue-router-next/blob/master/src/RouterView.ts#L67) in RouterView.ts

I am in the process of migrating a small site to Vue 3. I have addressed all of the browser warnings with the exception of this one. Since the RouterView is central to the app, it seems a critical place to have a warning about lost reactivity.

**Comment by posva** [comment]
The compat mode is to be used with Vue router 3
That watcher is correct

**Comment by sqal** [comment]
@posva 

> That watcher is correct 

if the usage is corrent and since vue-router v4 is only meant to be with vue 3 can't you remove the warning by adding 

```compatConfig { MODE: 3 }``` 

to RouterView/RouterLink?  I try to upgrade my app to vue 3 but I see a lot of warnings from these components but I don't want to disable WATCH_ARRAY options just yet because I have a lot of stuff to update.
